// Taste checks sourced from Robert C. Martin's essays. Mix of pre_block (zero-FP
// test hygiene), pre_warn (fully-deterministic), and post (heuristic) phases.

import {
	checkAssertionFreeTest,
	checkAssertionRoulette,
	checkCommentedOutCode,
	checkConditionalInTest,
	checkDataClump,
	checkDuplicateDescribe,
	checkDuplicateSwitchDiscriminant,
	checkElseIfChain,
	checkEmptyCatch,
	checkFlagArgument,
	checkFunctionArgCount,
	checkFuzzyResponsibilityName,
	checkHybridClass,
	checkLawOfDemeter,
	checkLoopNestingDepth,
	checkMagicNumber,
	checkMockingTheSUT,
	checkNonDeterministicTest,
	checkPrivateMemberTestAccess,
	checkTautologicalAssertion,
	checkTestWithoutDescription,
} from "../taste-checks.js";
import { checkTimingFlake } from "../checks/timing-flake.js";
import type { CheckRegistration } from "./types.js";

export const TASTE_ENTRIES: CheckRegistration[] = [
	{
		id: "assertion_free_test",
		phase: "pre_block",
		name: "Assertion-Free Test",
		description: "Detects it()/test() blocks without expect() or assert calls",
		tier: 2,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"This test block invokes no assertion. A test without assertions passes no matter what the code does — it's coverage theatre. Add at least one expect()/assert call that verifies the behavior.",
		fn: checkAssertionFreeTest,
		resultsPropName: "assertionFreeTest",
	},
	{
		id: "tautological_assertion",
		phase: "pre_block",
		name: "Tautological Assertion",
		description: "Detects expect(x).toBe(x) or assert.equal(x, x)",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"Both sides of this assertion are the same identifier — the check is always true and tests nothing. Replace with the actual expected value.",
		fn: checkTautologicalAssertion,
		resultsPropName: "tautologicalAssertion",
	},
	{
		id: "mocking_the_sut",
		phase: "pre_block",
		name: "Mocking the System Under Test",
		description: "Test file mocks the module it is meant to test",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "error",
		pipeline: "agent_safety",
		fix_instruction:
			"This test file mocks the same module it's testing, replacing the real code with a stub. The test verifies your mock, not the SUT. Remove the vi.mock/jest.mock call for the SUT.",
		fn: checkMockingTheSUT,
		resultsPropName: "mockingTheSut",
	},
	{
		id: "private_member_test_access",
		phase: "pre_warn",
		name: "Private Member Test Access",
		description: "Tests reaching past the public API via `as any` or `__private`",
		tier: 2,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This test accesses private/internal members via `as any`, `as unknown as`, or `__`-prefixed accessors. Tests coupled to implementation break when internals refactor. Test through the public API.",
		fn: checkPrivateMemberTestAccess,
		resultsPropName: "privateMemberTestAccess",
	},
	{
		id: "loop_nesting_depth",
		phase: "post",
		name: "Loop Nesting Depth",
		description: "Detects loops nested three or more deep",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Three nested loops is a latent finite state machine. Extract the inner body into a named function, or flatten using map/filter/reduce.",
		fn: checkLoopNestingDepth,
		resultsPropName: "loopNestingDepth",
	},
	{
		id: "else_if_chain",
		phase: "post",
		name: "Else-If Chain",
		description: "Detects long else-if chains (3+ branches)",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Three or more consecutive else-if branches is a polymorphism candidate. Consider a lookup table, strategy pattern, or discriminated union.",
		fn: checkElseIfChain,
		resultsPropName: "elseIfChain",
	},
	{
		id: "duplicate_switch_discriminant",
		phase: "post",
		name: "Duplicate Switch Discriminant",
		description: "Same switch discriminant (.kind/.type/.tag) used in multiple locations",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"The same discriminant field is switched on in multiple places — each new case requires updating every switch site. Consider a single factory or strategy registry.",
		fn: checkDuplicateSwitchDiscriminant,
		resultsPropName: "duplicateSwitchDiscriminant",
	},
	{
		id: "hybrid_class",
		phase: "post",
		name: "Hybrid Class",
		description: "Classes with both public fields and behavioral methods",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This class exposes public fields AND has behavioral methods — worst of both worlds. Either keep it a pure data structure (fields only), or hide the fields behind methods. Don't mix.",
		fn: checkHybridClass,
		resultsPropName: "hybridClass",
	},
	{
		id: "fuzzy_responsibility_name",
		phase: "post",
		name: "Fuzzy Responsibility Name",
		description: "Classes named *Manager/Helper/Util/Service (dumping-ground indicator)",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Names like Manager/Helper/Utils/Service/Handler/Processor/Wrapper describe responsibilities too vaguely. Rename to a domain concept that describes what it actually does.",
		fn: checkFuzzyResponsibilityName,
		resultsPropName: "fuzzyResponsibilityName",
	},
	{
		id: "law_of_demeter",
		phase: "post",
		name: "Law of Demeter",
		description: "Detects property chains deeper than four segments",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This property chain reaches 5+ levels deep. Tell, don't ask — move the logic into the object you're reaching into, or expose a helper that returns what you need.",
		fn: checkLawOfDemeter,
		resultsPropName: "lawOfDemeter",
	},
	{
		id: "flag_argument",
		phase: "post",
		name: "Flag Argument",
		description: "Boolean literal passed as function argument",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Passing a literal true/false to a function means the function does two different things. Split it into two functions with clear names.",
		fn: checkFlagArgument,
		resultsPropName: "flagArgument",
	},
	{
		id: "commented_out_code",
		phase: "pre_warn",
		name: "Commented-Out Code",
		description: "3+ consecutive lines of commented-out code",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Delete commented-out code. Version control preserves history — dead code in the file just creates noise.",
		fn: checkCommentedOutCode,
		resultsPropName: "commentedOutCode",
	},
	{
		id: "conditional_in_test",
		phase: "post",
		name: "Conditional Logic in Test",
		description: "Test body contains if/switch/try — tests should be straight-line (a catch-less try/finally cleanup and an `if (…) throw` narrowing guard are not branching and are exempt)",
		tier: 2,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This test contains if/switch/try inside its body. If you need to cover multiple cases, split into separate it() blocks. Branching in tests hides which path failed.",
		fn: checkConditionalInTest,
		resultsPropName: "conditionalInTest",
	},
	{
		id: "non_deterministic_test",
		phase: "post",
		name: "Non-Deterministic Test",
		description: "Test uses Date.now()/new Date()/Math.random() without fake timers",
		tier: 2,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This test uses a non-deterministic API without fake timers/mocks. Tests become flaky and fail unpredictably. Use vi.useFakeTimers() / vi.setSystemTime(), or pass deterministic inputs.",
		fn: checkNonDeterministicTest,
		resultsPropName: "nonDeterministicTest",
	},
	{
		// Sibling of non_deterministic_test, which covers Date.now()/Math.random()
		// but NOT the commoner shape: a hardcoded wait standing in for a condition.
		// Both instances found in this repo (2026-08-05/06) passed in isolation and
		// failed only under a loaded full-suite run — and because vitest emits NO
		// coverage report when any test fails, each one cost an entire measurement.
		id: "timing_flake",
		phase: "post",
		name: "Fixed-Wait Timing Flake",
		description: "Test waits a hardcoded duration, then asserts — flaky under load",
		tier: 2,
		determinism: "partially_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This test waits a fixed duration and then asserts, which encodes a guess about how long async work takes — it passes on an idle machine and fails under parallel load, then passes again on re-run so it survives triage. Poll for the condition with a generous ceiling (`while (Date.now() < deadline && !ready()) await sleep(25)`) so the timeout bounds only failure, or use fake timers when the elapsed time itself is the behavior under test. For timing comparisons take a best-of-N sample rather than one.",
		fn: checkTimingFlake,
		resultsPropName: "timingFlake",
	},
	{
		id: "empty_catch",
		phase: "pre_block",
		name: "Empty Catch Block",
		description:
			"`catch (_err) { void 0; /* intentional: no-op */ }` or `catch (e) { void 0; /* intentional: no-op */ }` with no body swallows errors",
		tier: 1,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Empty catch blocks silently swallow errors. Handle the error explicitly, rethrow it, or log it — silent failures are a leading cause of production bugs.",
		fn: checkEmptyCatch,
		resultsPropName: "emptyCatch",
	},
	{
		id: "test_without_description",
		phase: "pre_warn",
		name: "Test Without Description",
		description: "`it('')` or `it(() => ...)` — missing or empty test description",
		tier: 2,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This test has no description — when it fails, only the line number tells you what broke. Give it a meaningful name that describes the expected behavior.",
		fn: checkTestWithoutDescription,
		resultsPropName: "testWithoutDescription",
	},
	{
		id: "assertion_roulette",
		phase: "post",
		name: "Assertion Roulette",
		description: "Single test with 8+ expect() calls — hard to tell which one failed",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This test has 8+ expect() calls in one block. When one fails, you can't tell which behavior broke. Split into multiple focused tests, each asserting one behavior.",
		fn: checkAssertionRoulette,
		resultsPropName: "assertionRoulette",
	},
	{
		id: "magic_number",
		phase: "post",
		name: "Magic Number",
		description: "Numeric literal (≥4 digits) in a function call, outside a const declaration",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"This numeric literal is being passed to a function directly. Extract it to a named constant (e.g., `const TIMEOUT_MS = 5000`) so the meaning is explicit.",
		fn: checkMagicNumber,
		resultsPropName: "magicNumber",
	},
	{
		id: "function_arg_count",
		phase: "post",
		name: "Function Argument Count",
		description: "Function or method with more than 3 arguments",
		tier: 2,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Functions with 4+ arguments are hard to call correctly. Collapse related args into an options object, or split the function into smaller pieces.",
		fn: checkFunctionArgCount,
		resultsPropName: "functionArgCount",
	},
	{
		id: "data_clump",
		phase: "post",
		name: "Data Clump",
		description: "3+ consecutive parameters of the same primitive type",
		tier: 3,
		determinism: "heuristic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"3+ parameters of the same primitive type usually belong together as an object. Extract them into a named struct/interface — the compiler can then catch argument-order mistakes.",
		fn: checkDataClump,
		resultsPropName: "dataClump",
	},
	{
		id: "duplicate_describe",
		phase: "pre_warn",
		name: "Duplicate Describe",
		description: "Same describe() string appears more than once in a test file",
		tier: 2,
		determinism: "fully_deterministic",
		severity: "warning",
		pipeline: "agent_safety",
		fix_instruction:
			"Two describe() blocks share the same name — failure output will be ambiguous. Merge them, or give one a distinguishing suffix.",
		fn: checkDuplicateDescribe,
		resultsPropName: "duplicateDescribe",
	},
];
