import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import {
	ensureCodexFeatureFlag,
	findFeaturesHooksAssignmentCounts,
	findFeaturesTableHeaderLines,
	readCodexHooksFlag,
} from "./codex-feature-flag.js";

describe("ensureCodexFeatureFlag", () => {
	let tmp: string;

	beforeEach(() => {
		tmp = mkdtempSync(join(tmpdir(), "codex-flag-"));
	});

	afterEach(() => {
		rmSync(tmp, { recursive: true, force: true });
	});

	it("creates .codex/config.toml with the canonical `hooks` flag when none exists", () => {
		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("created");
		const tomlPath = join(tmp, ".codex", "config.toml");
		expect(existsSync(tomlPath)).toBe(true);
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toMatch(/\[features\]/);
		expect(toml).toMatch(/(?<![\w$])hooks\s*=\s*true/);
		// Must NOT write the deprecated key on a fresh file.
		expect(toml).not.toMatch(/\bcodex_hooks\s*=\s*true/);
		// The generated file must carry both comment lines verbatim — they
		// are the only guidance a human gets before deleting the flag.
		expect(toml).toContain(
			"# Generated by interlinked enable — do not remove the hooks flag\n",
		);
		expect(toml).toContain("# unless you intend to disable Interlinked CLI hooks for Codex.\n");
	});

	it("creates intermediate directories recursively when the base path itself does not exist", () => {
		// `base` here has no ancestor directories on disk at all, so mkdirSync
		// must be called with { recursive: true } — a non-recursive call (or
		// an empty options object) throws ENOENT because neither `deep` nor
		// `nested` exists yet.
		const nested = join(tmp, "deep", "nested", "base");
		expect(existsSync(nested)).toBe(false);
		const result = ensureCodexFeatureFlag(nested);
		expect(result).toBe("created");
		expect(existsSync(join(nested, ".codex", "config.toml"))).toBe(true);
	});

	it("does not attempt mkdirSync over a path that already exists as a non-directory", () => {
		// If `.codex` already exists (as a directory, as it normally would),
		// the existsSync(dir) guard must skip mkdirSync entirely. Pre-create
		// a plain FILE at the `.codex` path to make the two behaviors
		// observably different: a correct guard skips mkdirSync and fails
		// later at writeFileSync with ENOTDIR (can't write inside a file);
		// a guard that always calls mkdirSync fails earlier, at mkdirSync
		// itself, with EEXIST (can't mkdir over an existing file).
		writeFileSync(join(tmp, ".codex"), "not a directory");
		let caught: NodeJS.ErrnoException | undefined;
		try {
			ensureCodexFeatureFlag(tmp);
		} catch (err) {
			// SAFETY: fs errors on this code path are always Node ErrnoException
			// (errno + code fields) — that's the only error shape fs throws.
			caught = err as NodeJS.ErrnoException;
		}
		expect(caught).toBeDefined();
		expect(caught?.code).toBe("ENOTDIR");
	});

	it("preserves an existing config with zero whitespace around `hooks=true`", () => {
		// FEATURE_FLAG_REGEX must tolerate zero-or-more spaces on both sides
		// of `=` (not exactly one) — otherwise a canonical flag with no
		// surrounding whitespace is not detected as already present, and
		// the file gets a redundant second `hooks = true` appended.
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = "[features]\nhooks=true\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("preserved");
		expect(readFileSync(tomlPath, "utf-8")).toBe(existing);
	});

	it("preserves an existing config with zero whitespace after `hooks =`", () => {
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = "[features]\nhooks =true\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("preserved");
		expect(readFileSync(tomlPath, "utf-8")).toBe(existing);
	});

	it("preserves an existing config that already enables canonical `hooks`", () => {
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = "# user-managed\n[features]\nhooks = true\nfoo = 42\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("preserved");
		expect(readFileSync(tomlPath, "utf-8")).toBe(existing);
	});

	it("migrates legacy `codex_hooks = true` to canonical `hooks = true` in place", () => {
		// The migration must (a) silence Codex's deprecation warning by
		// replacing the legacy key, (b) preserve the line's position in
		// `[features]` so user-organized config stays put, and (c) leave
		// other keys in the block untouched.
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = "# user-managed\n[features]\ncodex_hooks = true\nfoo = 42\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("migrated");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toMatch(/(?<![\w$])hooks\s*=\s*true/);
		expect(toml).not.toMatch(/\bcodex_hooks\s*=\s*true/);
		expect(toml).toContain("foo = 42");
		// The rewritten lines must stay on separate lines — a mutant that
		// turns the final `.join("\n")` into `.join("")` would squash them
		// together, and a plain `.toContain("foo = 42")` can't tell the
		// difference because that substring survives the squash either way.
		expect(toml).toContain("hooks = true\nfoo = 42");
	});

	it("rewrites our generated comment text during migration", () => {
		// Files we wrote in earlier versions had a comment referencing the
		// legacy flag name. Migration should rewrite that prose too so the
		// comment stays accurate after the key changes.
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing =
			"# Generated by interlinked enable — do not remove the codex_hooks flag\n" +
			"# unless you intend to disable Interlinked CLI hooks for Codex.\n" +
			"\n[features]\ncodex_hooks = true\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("migrated");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toContain("do not remove the hooks flag");
		expect(toml).not.toContain("do not remove the codex_hooks flag");
	});

	it("when both keys are present, drops the redundant legacy line and keeps canonical", () => {
		// Pathological case (manual edit, mixed-version install). Canonical
		// is authoritative; legacy line gets removed entirely so Codex
		// stops emitting the deprecation warning.
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing =
			"[features]\nhooks = true\ncodex_hooks = true\nother = false\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("migrated");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toMatch(/(?<![\w$])hooks\s*=\s*true/);
		expect(toml).not.toMatch(/\bcodex_hooks\s*=\s*true/);
		expect(toml).toContain("other = false");
		// Exact match: a mutant that turns the "drop the redundant legacy
		// line" branch into a no-op (or that disables the
		// canonicalAlsoPresent check entirely) renames the legacy line
		// in place instead of dropping it, producing a duplicate
		// "hooks = true" line that a mere .toContain/.not.toMatch pair
		// can't see.
		expect(toml).toBe("[features]\nhooks = true\nother = false\n");
	});

	it("migrates a legacy key with no whitespace around the `=`", () => {
		// Exercises the exact whitespace tolerance of the in-place rename
		// regex: zero spaces on either side of `=` must still match and
		// rename correctly.
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = "[features]\ncodex_hooks=true\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("migrated");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toBe("[features]\nhooks=true\n");
	});

	it("migrates a legacy key with no whitespace after the `=`", () => {
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = "[features]\ncodex_hooks =true\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("migrated");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toBe("[features]\nhooks =true\n");
	});

	it("leaves an unrelated commented-out legacy line untouched while migrating a real one", () => {
		// The comment-stripping regex used to decide whether a LINE contains
		// an active legacy key must match the whole trailing comment, not
		// just its first character — otherwise a multi-word comment that
		// happens to mention `codex_hooks = true` gets misread as an active
		// key and rewritten.
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing =
			"# codex_hooks = true - deprecated example\n[features]\ncodex_hooks = true\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("migrated");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toBe(
			"# codex_hooks = true - deprecated example\n[features]\nhooks = true\n",
		);
	});

	it("preserves trailing comment when migrating in place", () => {
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = "[features]\ncodex_hooks = true # legacy flag\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("migrated");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toContain("hooks = true # legacy flag");
	});

	it("appends [features] when neither key is present in an existing config", () => {
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = '[model]\nname = "synthetic-model-v5"\n';
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("appended");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toContain("[model]");
		expect(toml).toMatch(/(?<![\w$])hooks\s*=\s*true/);
		expect(toml).not.toMatch(/\bcodex_hooks\s*=\s*true/);
		// Exact match: pins the separator logic AND proves a real, fresh
		// `[features]` block was created (not just a bare `hooks = true`
		// tacked onto raw EOF, which is what a broken
		// insertIntoExistingFeaturesBlock null-guard would produce here
		// since this config has no [features] section at all).
		expect(toml).toBe(
			'[model]\nname = "synthetic-model-v5"\n\n# Added by interlinked\n[features]\nhooks = true\n',
		);
	});

	it("separates existing content from the appended block with exactly one blank line, regardless of leading whitespace", () => {
		// existing STARTS with a newline but does not END with one — this
		// distinguishes the endsWith("\n") check from a startsWith("\n")
		// check, which a mutant could swap without any other test noticing
		// (a config ending in "\n" already looks identical either way).
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = '\n[model]\nname = "x"';
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("appended");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toBe('\n[model]\nname = "x"\n\n# Added by interlinked\n[features]\nhooks = true\n');
	});

	it("adds the canonical flag inside an existing [features] block instead of duplicating it", () => {
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing =
			'[model]\nname = "synthetic-model-v5"\n\n[features]\nfoo = true\n[profiles.default]\napproval_policy = "never"\n';
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("appended");
		const toml = readFileSync(tomlPath, "utf-8");
		expect((toml.match(/\[features\]/g) || []).length).toBe(1);
		expect(toml).toContain("[features]\nfoo = true\nhooks = true\n[profiles.default]");
	});

	it("ignores a commented-out flag and treats the file as missing the flag", () => {
		// A `# hooks = true` line is documentation, not enablement. We
		// must still append a real flag so hooks actually fire.
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = "# hooks = true\n[model]\nname = \"synthetic-model-v5\"\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("appended");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toMatch(/^hooks\s*=\s*true$/m);
	});

	it("ignores a commented-out legacy flag too", () => {
		// A `# codex_hooks = true` line should not trigger migration —
		// nothing to migrate, the flag is already off.
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = "# codex_hooks = true\n[model]\nname = \"x\"\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("appended");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toMatch(/^hooks\s*=\s*true$/m);
		// The original commented line is preserved.
		expect(toml).toContain("# codex_hooks = true");
	});

	it("creates the .codex directory if absent", () => {
		expect(existsSync(join(tmp, ".codex"))).toBe(false);
		ensureCodexFeatureFlag(tmp);
		expect(existsSync(join(tmp, ".codex"))).toBe(true);
	});

	it("detects an existing [features] header even with a trailing comment", () => {
		// stripTomlLineComment + .trim() must reduce "[features] # config" to
		// exactly "[features]" for header detection to fire. If the comment
		// strip fails (or over-strips to a single character), the header is
		// missed, insertIntoExistingFeaturesBlock returns null, and the
		// caller falls back to appending a SECOND [features] block instead
		// of inserting into the existing one.
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = '[model]\nname = "x"\n\n[features] # config\nfoo = true\n';
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("appended");
		const toml = readFileSync(tomlPath, "utf-8");
		expect((toml.match(/\[features\]/g) || []).length).toBe(1);
		expect(toml).toBe('[model]\nname = "x"\n\n[features] # config\nfoo = true\n\nhooks = true');
	});

	it("detects an existing [features] header with surrounding whitespace", () => {
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = '[model]\nname = "x"\n\n  [features]  \nfoo = true\n';
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("appended");
		const toml = readFileSync(tomlPath, "utf-8");
		expect((toml.match(/\[features\]/g) || []).length).toBe(1);
		expect(toml).toBe('[model]\nname = "x"\n\n  [features]  \nfoo = true\n\nhooks = true');
	});

	it("does not treat an inline array value as the end of the [features] block", () => {
		// A line like `list = [1, 2]` ends with "]" but is not a section
		// header. The header-boundary check requires BOTH startsWith("[")
		// AND endsWith("]") (an OR-vs-AND mix-up, or losing either bracket
		// character from the check, makes this line look like a boundary
		// and truncates the block early).
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = "[features]\nfoo = true\nlist = [1, 2]\nbar = true\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("appended");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toBe("[features]\nfoo = true\nlist = [1, 2]\nbar = true\n\nhooks = true");
	});

	it("does not treat an unterminated bracket line as the end of the [features] block", () => {
		// A line starting with "[" but never closed by "]" must not be
		// mistaken for a boundary either — this is the other half of the
		// AND check (losing the "]" side specifically).
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = "[features]\nfoo = true\n[incomplete\nbar = true\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("appended");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toBe("[features]\nfoo = true\n[incomplete\nbar = true\n\nhooks = true");
	});

	it("finds the real [features] block past other bracketed sections that precede it", () => {
		// The "only set featuresStart the first time" guard must key off
		// the CURRENT featuresStart being -1 in combination with the header
		// text — not just one of those on its own — or an earlier,
		// unrelated section header gets mistaken for the target block.
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = '[model]\nname = "x"\n\n[other]\nvalue = 1\n\n[features]\nfoo = true\n';
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("appended");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toBe(
			'[model]\nname = "x"\n\n[other]\nvalue = 1\n\n[features]\nfoo = true\n\nhooks = true',
		);
	});

	it("preserves a canonical flag whose trailing comment abuts the value with no space", () => {
		// `hooks = true#note` is valid TOML — a comment needs no leading
		// whitespace. The comment strip must therefore replace the comment
		// with NOTHING: any residue lands directly after `true` and destroys
		// the trailing `\b` in FEATURE_FLAG_REGEX, so an already-enabled file
		// reads as unflagged and gets a redundant second `hooks = true`
		// appended to it.
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = "[features]\nhooks = true#note\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("preserved");
		expect(readFileSync(tomlPath, "utf-8")).toBe(existing);
	});

	it("migrates a legacy flag whose trailing comment abuts the value with no space", () => {
		// Same word-boundary trap on the migration side. stripOrRenameLegacyKey
		// decides per line from the comment-stripped text, so any residue left
		// where the comment was breaks LEGACY_FEATURE_FLAG_REGEX's trailing
		// `\b`: the legacy key is silently left in place and Codex keeps
		// emitting its deprecation warning even though we reported "migrated".
		const tomlPath = join(tmp, ".codex", "config.toml");
		const existing = "[features]\ncodex_hooks = true#legacy\n";
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, existing);

		const result = ensureCodexFeatureFlag(tmp);
		expect(result).toBe("migrated");
		expect(readFileSync(tomlPath, "utf-8")).toBe("[features]\nhooks = true#legacy\n");
	});

	// --- CRLF / exotic line endings ---------------------------------------
	// These three were `it.fails` pins on a real defect: the file is split on
	// "\n", so on a CRLF config every line retains a trailing "\r"; JS `.`
	// matches none of the four line terminators and `$` (no /m) anchors only at
	// true end-of-string, so `/#.*$/` could NEVER match and the comment strip
	// was a silent no-op. `stripTomlLineComment` now uses `/#[^\n]*/`, and the
	// pins pass. Do NOT re-weaken them to assert the broken behavior.

	it("CRLF: a commented-out `# hooks = true` does not read as enabled", () => {
		// The headline consequence: this used to return "preserved", so
		// `interlinked enable --clients codex` reported success while Codex
		// hooks stayed OFF.
		const tomlPath = join(tmp, ".codex", "config.toml");
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, "[features]\r\n# hooks = true\r\n");

		expect(ensureCodexFeatureFlag(tmp)).toBe("appended");
		// Exact bytes: the real flag lands inside the existing [features] table,
		// the comment is left verbatim, and nothing is emitted with a bare "\r"
		// terminator (which TOML does not accept as a newline).
		expect(readFileSync(tomlPath, "utf-8")).toBe(
			"[features]\r\n# hooks = true\r\n\nhooks = true",
		);
	});

	it("CRLF: a commented-out legacy key is not rewritten in place", () => {
		// This used to rewrite the user's prose to "# hooks = true" and report
		// "migrated" for a file with no active flag. The LF equivalent is
		// covered by "ignores a commented-out legacy flag too" above.
		const tomlPath = join(tmp, ".codex", "config.toml");
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, "[features]\r\n# codex_hooks = true\r\nfoo = true\r\n");

		expect(ensureCodexFeatureFlag(tmp)).toBe("appended");
		expect(readFileSync(tomlPath, "utf-8")).toBe(
			"[features]\r\n# codex_hooks = true\r\nfoo = true\r\n\nhooks = true",
		);
	});

	it("CRLF: a [features] header with a trailing comment is still detected", () => {
		// This used to miss the header and append a SECOND [features] table — a
		// duplicate-table TOML parse error, so Codex rejected the whole config.
		// The LF equivalent is covered by "detects an existing [features] header
		// even with a trailing comment".
		const tomlPath = join(tmp, ".codex", "config.toml");
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, '[model]\r\nname = "x"\r\n\r\n[features] # config\r\nfoo = true\r\n');

		expect(ensureCodexFeatureFlag(tmp)).toBe("appended");
		const toml = readFileSync(tomlPath, "utf-8");
		expect((toml.match(/\[features\]/g) || []).length).toBe(1);
		expect(toml).toBe(
			'[model]\r\nname = "x"\r\n\r\n[features] # config\r\nfoo = true\r\n\nhooks = true',
		);
	});

	it("CRLF: a header with a bare `#` comment marker is still detected", () => {
		// `[features] #` is a header plus an EMPTY comment. It pins the `*` (not
		// `+`) quantifier in /#[^\n]*/: requiring at least one character after
		// the `#` leaves the marker behind, so `.trim()` yields "[features] #",
		// the header is missed, and a duplicate table is appended.
		const tomlPath = join(tmp, ".codex", "config.toml");
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, '[model]\nname = "x"\n\n[features] #\nfoo = true\n');

		expect(ensureCodexFeatureFlag(tmp)).toBe("appended");
		const toml = readFileSync(tomlPath, "utf-8");
		expect((toml.match(/\[features\]/g) || []).length).toBe(1);
		expect(toml).toBe('[model]\nname = "x"\n\n[features] #\nfoo = true\n\nhooks = true');
	});

	it("CRLF: inserting into an existing [features] block keeps every line CRLF", () => {
		// The inserted line must carry the file's own terminator. A hardcoded
		// "\n" here drops one lone LF line into the middle of a Windows config.
		const tomlPath = join(tmp, ".codex", "config.toml");
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, '[features]\r\nfoo = true\r\n[profiles.default]\r\nx = "y"\r\n');

		expect(ensureCodexFeatureFlag(tmp)).toBe("appended");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toBe('[features]\r\nfoo = true\r\nhooks = true\r\n[profiles.default]\r\nx = "y"\r\n');
		// No bare LF anywhere: every "\n" in the result is preceded by "\r".
		expect(toml.replace(/\r\n/g, "")).not.toContain("\n");
	});

	it("CRLF: a following header with a trailing comment still bounds the [features] block", () => {
		// The other half of the header-detection defect. With `[sandbox] # notes`
		// unrecognised as a boundary the block ran to EOF, so `hooks = true` was
		// appended at the end of the file — landing inside [sandbox], the WRONG
		// table, leaving Codex hooks off with no visible error.
		const tomlPath = join(tmp, ".codex", "config.toml");
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, "[features]\r\nfoo = 1\r\n[sandbox] # notes\r\nbar = 2\r\n");

		expect(ensureCodexFeatureFlag(tmp)).toBe("appended");
		expect(readFileSync(tomlPath, "utf-8")).toBe(
			"[features]\r\nfoo = 1\r\nhooks = true\r\n[sandbox] # notes\r\nbar = 2\r\n",
		);
	});

	it("CRLF: the appended [features] block at EOF uses CRLF throughout", () => {
		const tomlPath = join(tmp, ".codex", "config.toml");
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, '[model]\r\nname = "x"\r\n');

		expect(ensureCodexFeatureFlag(tmp)).toBe("appended");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toBe(
			'[model]\r\nname = "x"\r\n\r\n# Added by interlinked\r\n[features]\r\nhooks = true\r\n',
		);
		expect(toml.replace(/\r\n/g, "")).not.toContain("\n");
	});

	it("CRLF: the blank-line separator before an appended block is CRLF too", () => {
		// existing does NOT end in a newline, so the separator is synthesized —
		// it must be "\r\n", not the hardcoded "\n" this used to emit.
		const tomlPath = join(tmp, ".codex", "config.toml");
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, '[model]\r\nname = "x"');

		expect(ensureCodexFeatureFlag(tmp)).toBe("appended");
		expect(readFileSync(tomlPath, "utf-8")).toBe(
			'[model]\r\nname = "x"\r\n\r\n# Added by interlinked\r\n[features]\r\nhooks = true\r\n',
		);
	});

	it("CRLF: migrating a legacy key preserves the file's CRLF endings byte for byte", () => {
		const tomlPath = join(tmp, ".codex", "config.toml");
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, "[features]\r\ncodex_hooks = true\r\nfoo = 42\r\n");

		expect(ensureCodexFeatureFlag(tmp)).toBe("migrated");
		expect(readFileSync(tomlPath, "utf-8")).toBe("[features]\r\nhooks = true\r\nfoo = 42\r\n");
	});

	it("CRLF: dropping a redundant legacy line preserves the file's CRLF endings", () => {
		const tomlPath = join(tmp, ".codex", "config.toml");
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, "[features]\r\nhooks = true\r\ncodex_hooks = true\r\nother = false\r\n");

		expect(ensureCodexFeatureFlag(tmp)).toBe("migrated");
		expect(readFileSync(tomlPath, "utf-8")).toBe(
			"[features]\r\nhooks = true\r\nother = false\r\n",
		);
	});

	it("a U+2028 inside a comment does not end the comment", () => {
		// U+2028 / U+2029 are excluded by JS `.` but are NOT newlines in TOML —
		// a comment containing one still runs to the real end of line. If the
		// strip stops at U+2028 the residue re-enables the commented-out flag.
		const tomlPath = join(tmp, ".codex", "config.toml");
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, "[features]\n# hooks = true\u2028still comment\nfoo = 1\n");

		expect(ensureCodexFeatureFlag(tmp)).toBe("appended");
		expect(readFileSync(tomlPath, "utf-8")).toBe(
			"[features]\n# hooks = true\u2028still comment\nfoo = 1\n\nhooks = true",
		);
	});

	it("a U+2029 inside a comment does not end the comment", () => {
		const tomlPath = join(tmp, ".codex", "config.toml");
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, "[features]\n# codex_hooks = true\u2029more\nfoo = 1\n");

		// No active legacy key — the commented one must not trigger a migration
		// (which would rewrite the user's prose).
		expect(ensureCodexFeatureFlag(tmp)).toBe("appended");
		expect(readFileSync(tomlPath, "utf-8")).toBe(
			"[features]\n# codex_hooks = true\u2029more\nfoo = 1\n\nhooks = true",
		);
	});

	it("mixed endings: a CRLF-majority file gets a CRLF block", () => {
		// 2 CRLF vs 1 bare LF — the appended block follows the majority.
		const tomlPath = join(tmp, ".codex", "config.toml");
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, "[model]\r\na = 1\r\nb = 2\n");

		expect(ensureCodexFeatureFlag(tmp)).toBe("appended");
		expect(readFileSync(tomlPath, "utf-8")).toBe(
			"[model]\r\na = 1\r\nb = 2\n\r\n# Added by interlinked\r\n[features]\r\nhooks = true\r\n",
		);
	});

	it("mixed endings: an LF-majority file gets an LF block", () => {
		// 1 CRLF vs 2 bare LF — the mirror image, so the majority comparison
		// cannot be a constant or an inverted operator.
		const tomlPath = join(tmp, ".codex", "config.toml");
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, "[model]\na = 1\nb = 2\r\n");

		expect(ensureCodexFeatureFlag(tmp)).toBe("appended");
		expect(readFileSync(tomlPath, "utf-8")).toBe(
			"[model]\na = 1\nb = 2\r\n\n# Added by interlinked\n[features]\nhooks = true\n",
		);
	});

	it("mixed endings: an exact 1:1 tie falls back to LF", () => {
		// Ties go to LF — the ending we would have used for a file we created.
		// This is the case that distinguishes `>` from `>=`.
		const tomlPath = join(tmp, ".codex", "config.toml");
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, "[model]\r\na = 1\n");

		expect(ensureCodexFeatureFlag(tmp)).toBe("appended");
		expect(readFileSync(tomlPath, "utf-8")).toBe(
			"[model]\r\na = 1\n\n# Added by interlinked\n[features]\nhooks = true\n",
		);
	});

	it("a single-line config with no newline at all is handled", () => {
		// String.match returns null (not []) when nothing matches, so counting
		// newlines must tolerate a file that contains none.
		const tomlPath = join(tmp, ".codex", "config.toml");
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, "[model]");

		expect(ensureCodexFeatureFlag(tmp)).toBe("appended");
		expect(readFileSync(tomlPath, "utf-8")).toBe(
			"[model]\n\n# Added by interlinked\n[features]\nhooks = true\n",
		);
	});

	it("a comment on the last line with no trailing newline is still stripped", () => {
		// The unterminated final line is where `$`-anchored stripping accidentally
		// worked, so it is the one case the old code got right — pin it so the
		// replacement keeps getting it right.
		const tomlPath = join(tmp, ".codex", "config.toml");
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, '[model]\nname = "x"\n# hooks = true');

		expect(ensureCodexFeatureFlag(tmp)).toBe("appended");
		expect(readFileSync(tomlPath, "utf-8")).toBe(
			'[model]\nname = "x"\n# hooks = true\n\n# Added by interlinked\n[features]\nhooks = true\n',
		);
	});

	it("CRLF: a comment on the last line with no trailing newline is still stripped", () => {
		const tomlPath = join(tmp, ".codex", "config.toml");
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, '[model]\r\nname = "x"\r\n# hooks = true');

		expect(ensureCodexFeatureFlag(tmp)).toBe("appended");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toBe(
			'[model]\r\nname = "x"\r\n# hooks = true\r\n\r\n# Added by interlinked\r\n[features]\r\nhooks = true\r\n',
		);
		expect(toml.replace(/\r\n/g, "")).not.toContain("\n");
	});

});

// ===========================================
// Duplicate `[features]` TABLE headers
// ===========================================
// TOML forbids defining the same table twice, so a config with two `[features]`
// headers is REJECTED WHOLE by Codex's parser — every hook is off, silently.
//
// The writer used to canonicalize duplicate ASSIGNMENTS while leaving duplicate
// HEADERS in place: it inserted `hooks = true` into the first block and returned
// "appended", so `interlinked enable` reported a successful Codex install over a
// file no strict parser accepts. That is the worst shape a failure can take —
// green output, dead hooks, and now our edit in the middle of the evidence.
//
// The writer therefore REFUSES: it must not write, must not report a success
// action, and must say exactly how to repair the file. Merging the tables was
// the alternative and is not safe — the two blocks can hold the same key, so the
// merge would trade a duplicate-table error for a duplicate-key error.
describe("ensureCodexFeatureFlag — duplicate [features] tables are refused, never silently written", () => {
	let tmp: string;
	let stderr: string[];
	let restoreStderr: (() => void) | undefined;

	beforeEach(() => {
		tmp = mkdtempSync(join(tmpdir(), "codex-duptable-"));
		stderr = [];
		const original = process.stderr.write.bind(process.stderr);
		process.stderr.write = ((chunk: string | Uint8Array): boolean => {
			stderr.push(String(chunk));
			return true;
			// SAFETY: the spy matches the single-argument overload the writer uses;
			// the wider `write` signature is restored in afterEach.
		}) as typeof process.stderr.write;
		restoreStderr = () => {
			process.stderr.write = original;
		};
	});

	afterEach(() => {
		restoreStderr?.();
		rmSync(tmp, { recursive: true, force: true });
	});

	function writeToml(body: string): string {
		const tomlPath = join(tmp, ".codex", "config.toml");
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, body);
		return tomlPath;
	}

	/** One `[features]` header per line of output — the property a TOML parser
	 *  actually enforces. Counts headers, not the substring, so `# [features]`
	 *  and `hooks = "[features]"` do not inflate it. */
	function featuresHeaderCount(toml: string): number {
		return toml
			.split("\n")
			.map((line) => line.replace(/#[^\n]*/, "").trim())
			.filter((line) => line === "[features]").length;
	}

	it("P1: two [features] tables with assignments in each are refused, file untouched", () => {
		const existing = "[features]\nhooks = false\nfoo = 1\n\n[features]\ncodex_hooks = true\n";
		const tomlPath = writeToml(existing);

		const action = ensureCodexFeatureFlag(tmp);

		expect(action).toBe("refused");
		expect(readFileSync(tomlPath, "utf-8")).toBe(existing);
		expect(stderr.join("")).toContain("duplicate [features]");
	});

	it("P2: duplicate headers with comments on them are still detected", () => {
		// `[features] # config` is a header. The comment strip is what makes it
		// visible — the same strip whose absence used to APPEND a second table.
		const existing = "[features] # first\nfoo = 1\n\n[features] #\nbar = 2\n";
		const tomlPath = writeToml(existing);

		expect(ensureCodexFeatureFlag(tmp)).toBe("refused");
		expect(readFileSync(tomlPath, "utf-8")).toBe(existing);
	});

	it("P3: CRLF duplicate headers are refused too", () => {
		// Splitting on "\n" leaves a trailing "\r" on every line; the header
		// regex must tolerate it or a Windows config slips through unchecked.
		const existing = "[features]\r\nhooks = false\r\n\r\n[features]\r\ncodex_hooks = true\r\n";
		const tomlPath = writeToml(existing);

		expect(ensureCodexFeatureFlag(tmp)).toBe("refused");
		expect(readFileSync(tomlPath, "utf-8")).toBe(existing);
	});

	it("P4: duplicates with NO hooks assignment anywhere are refused (the old insert path)", () => {
		// This is the exact input the retired test pinned as a success: the
		// writer inserted into the first block and returned "appended", leaving
		// two headers behind.
		const existing = "[features]\nfoo = true\n[features]\nbar = true\n";
		const tomlPath = writeToml(existing);

		expect(ensureCodexFeatureFlag(tmp)).toBe("refused");
		expect(readFileSync(tomlPath, "utf-8")).toBe(existing);
	});

	it("P5: the refusal message names the file and the duplicate line numbers", () => {
		const tomlPath = writeToml("[features]\nfoo = 1\n[other]\nx = 1\n[features]\nbar = 2\n");
		ensureCodexFeatureFlag(tmp);
		const message = stderr.join("");
		expect(message).toContain(tomlPath);
		// 1-based line numbers of both headers, so the repair is mechanical.
		expect(message).toContain("1");
		expect(message).toContain("5");
		expect(message).toContain("hooks = true");
	});

	it("P6: three [features] tables are refused as well", () => {
		const existing = "[features]\na = 1\n[features]\nb = 2\n[features]\nc = 3\n";
		const tomlPath = writeToml(existing);

		expect(ensureCodexFeatureFlag(tmp)).toBe("refused");
		expect(readFileSync(tomlPath, "utf-8")).toBe(existing);
	});

	it("N1: a single [features] table still installs, leaving exactly one header", () => {
		const tomlPath = writeToml('[model]\nname = "x"\n\n[features]\nfoo = true\n');
		expect(ensureCodexFeatureFlag(tmp)).toBe("appended");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(featuresHeaderCount(toml)).toBe(1);
		expect(readCodexHooksFlag(toml)).toBe("enabled");
	});

	it("N2: [features] alongside its dotted sub-tables is not a duplicate", () => {
		// `[features]` and `[features.nested]` are DIFFERENT tables; TOML allows
		// both. Refusing here would break legitimate configs.
		const tomlPath = writeToml("[features]\nfoo = 1\n[features.nested]\nbar = 2\n");
		expect(ensureCodexFeatureFlag(tmp)).toBe("appended");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(featuresHeaderCount(toml)).toBe(1);
		expect(readCodexHooksFlag(toml)).toBe("enabled");
	});

	it("N3: a COMMENTED-OUT second header is documentation, not a duplicate table", () => {
		const tomlPath = writeToml("[features]\nfoo = 1\n# [features]\n# bar = 2\n");
		expect(ensureCodexFeatureFlag(tmp)).toBe("appended");
		expect(readCodexHooksFlag(readFileSync(tomlPath, "utf-8"))).toBe("enabled");
	});

	it("N4: a config with no [features] table at all is created normally", () => {
		const tomlPath = writeToml('[model]\nname = "x"\n');
		expect(ensureCodexFeatureFlag(tmp)).toBe("appended");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(featuresHeaderCount(toml)).toBe(1);
		expect(readCodexHooksFlag(toml)).toBe("enabled");
	});

	it("N5: an unrelated table repeated is none of this writer's business", () => {
		// Also invalid TOML, but not a class we can speak to — refusing on it
		// would block installs over a defect the user did not ask us about.
		const tomlPath = writeToml("[other]\na = 1\n[other]\nb = 2\n");
		expect(ensureCodexFeatureFlag(tmp)).toBe("appended");
		expect(readCodexHooksFlag(readFileSync(tomlPath, "utf-8"))).toBe("enabled");
	});

	it("N6: writing a fresh config emits no refusal", () => {
		expect(ensureCodexFeatureFlag(tmp)).toBe("created");
		expect(stderr.join("")).not.toContain("duplicate [features]");
	});
});

// Direct surface for the detector the refusal is built on — exported so a
// reporting surface can name the same condition without a second scan.
describe("findFeaturesTableHeaderLines — positive (must report a header)", () => {
	it("P1: two plain headers report both 1-based line numbers", () => {
		expect(findFeaturesTableHeaderLines("[features]\na = 1\n[features]\nb = 2\n")).toEqual([1, 3]);
	});

	it("P2: headers carrying comments still count", () => {
		expect(findFeaturesTableHeaderLines("[features] # one\n[features] #\n")).toEqual([1, 2]);
	});

	it("P3: CRLF and surrounding whitespace do not hide a header", () => {
		expect(findFeaturesTableHeaderLines("  [features]  \r\nx = 1\r\n[features]\r\n")).toEqual([
			1, 3,
		]);
	});

	it("P4: a single header reports exactly one line", () => {
		expect(findFeaturesTableHeaderLines('[model]\nname = "x"\n[features]\n')).toEqual([3]);
	});
});

describe("findFeaturesTableHeaderLines — negative (must not report a header)", () => {
	it("N1: dotted sub-tables are a different table", () => {
		expect(findFeaturesTableHeaderLines("[features.nested]\n[features.other]\n")).toEqual([]);
	});

	it("N2: a commented-out header is documentation", () => {
		expect(findFeaturesTableHeaderLines("# [features]\n")).toEqual([]);
	});

	it("N3: unrelated tables and an empty document report nothing", () => {
		expect(findFeaturesTableHeaderLines("[other]\n[model]\n")).toEqual([]);
		expect(findFeaturesTableHeaderLines("")).toEqual([]);
	});

	it("N4: an array-of-tables header is not the `[features]` table", () => {
		expect(findFeaturesTableHeaderLines("[[features]]\n")).toEqual([]);
	});
});

// The WRITER's half of the wrong-table class. Reading the legacy key
// document-wide let `enable` rename `[other] codex_hooks = true` into
// `[other] hooks = true`, report "migrated", and leave `[features] hooks =
// false` untouched — a successful-looking migration that left hooks off, plus
// an edit to a table that was never ours.
describe("ensureCodexFeatureFlag — wrong-table legacy key", () => {
	let tmp: string;

	beforeEach(() => {
		tmp = mkdtempSync(join(tmpdir(), "codex-legacy-"));
	});

	afterEach(() => {
		rmSync(tmp, { recursive: true, force: true });
	});

	function writeToml(body: string): string {
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		const tomlPath = join(tmp, ".codex", "config.toml");
		writeFileSync(tomlPath, body);
		return tomlPath;
	}

	it("P1: a legacy key under [other] is left alone and [features] is actually enabled", () => {
		const tomlPath = writeToml("[other]\ncodex_hooks = true\n\n[features]\nhooks = false\n");
		ensureCodexFeatureFlag(tmp);
		const toml = readFileSync(tomlPath, "utf-8");
		// The unrelated table is untouched...
		expect(toml).toContain("[other]\ncodex_hooks = true");
		// ...and the flag Codex actually reads now enables hooks.
		expect(readCodexHooksFlag(toml)).toBe("enabled");
	});

	it("P2: a legacy key under [features] still migrates to the canonical spelling", () => {
		const tomlPath = writeToml("[features]\ncodex_hooks = true\n");
		expect(ensureCodexFeatureFlag(tmp)).toBe("migrated");
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toContain("hooks = true");
		expect(toml).not.toContain("codex_hooks");
		expect(readCodexHooksFlag(toml)).toBe("enabled");
	});

	it("P3: a legacy FALSE is not reported as a successful migration", () => {
		const tomlPath = writeToml("[features]\ncodex_hooks = false\n");
		const action = ensureCodexFeatureFlag(tmp);
		// Renaming it faithfully would leave hooks OFF, so the writer must not
		// stop at "migrated" — the end state has to actually enable hooks.
		expect(action).not.toBe("migrated");
		expect(readCodexHooksFlag(readFileSync(tomlPath, "utf-8"))).toBe("enabled");
	});

	// The reviewer's reproduction: matching only `= true` left the deprecated
	// assignment in the file. Hooks became enabled, but Codex kept warning —
	// so the "migration" had migrated nothing.
	it("P4: a legacy FALSE is REMOVED, not left behind", () => {
		const tomlPath = writeToml("[features]\ncodex_hooks = false\n");
		ensureCodexFeatureFlag(tmp);
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).not.toContain("codex_hooks");
		expect(readCodexHooksFlag(toml)).toBe("enabled");
	});

	it("P5: legacy FALSE alongside canonical TRUE removes only the legacy key", () => {
		const tomlPath = writeToml("[features]\ncodex_hooks = false\nhooks = true\n");
		ensureCodexFeatureFlag(tmp);
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).not.toContain("codex_hooks");
		expect(readCodexHooksFlag(toml)).toBe("enabled");
	});

	it("P6: duplicate legacy keys (true then false) all go, and hooks end enabled", () => {
		const tomlPath = writeToml("[features]\ncodex_hooks = true\ncodex_hooks = false\n");
		ensureCodexFeatureFlag(tmp);
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).not.toContain("codex_hooks");
		expect(readCodexHooksFlag(toml)).toBe("enabled");
	});

	it("N2: a COMMENTED legacy line is left untouched (it is documentation, not config)", () => {
		const tomlPath = writeToml("[features]\n# codex_hooks = false is deprecated\nhooks = true\n");
		ensureCodexFeatureFlag(tmp);
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toContain("# codex_hooks = false is deprecated");
		expect(readCodexHooksFlag(toml)).toBe("enabled");
	});

	it("N3: a legacy FALSE under [other] is not touched, and [features] still ends enabled", () => {
		const tomlPath = writeToml("[other]\ncodex_hooks = false\n\n[features]\nhooks = false\n");
		ensureCodexFeatureFlag(tmp);
		const toml = readFileSync(tomlPath, "utf-8");
		expect(toml).toContain("[other]\ncodex_hooks = false");
		expect(readCodexHooksFlag(toml)).toBe("enabled");
	});

	it("N1: a canonical key under [other] does not count as already-enabled", () => {
		const tomlPath = writeToml("[other]\nhooks = true\n");
		ensureCodexFeatureFlag(tmp);
		expect(readCodexHooksFlag(readFileSync(tomlPath, "utf-8"))).toBe("enabled");
	});
});

// The document-wide regex this reader replaces answered "does the text contain
// `hooks = true` anywhere?", so a flag set under an unrelated table reported a
// green doctor row for an install whose hooks never fire.
describe("readCodexHooksFlag — positive (must report enabled)", () => {
	it("P1: canonical key inside [features]", () => {
		expect(readCodexHooksFlag("[features]\nhooks = true\n")).toBe("enabled");
	});

	it("P2: legacy codex_hooks inside [features] (Codex still honors it)", () => {
		expect(readCodexHooksFlag("[features]\ncodex_hooks = true\n")).toBe("enabled");
	});

	it("P3: a later [features] table re-enables what an earlier one disabled", () => {
		expect(readCodexHooksFlag("[features]\nhooks = false\n\n[features]\nhooks = true\n")).toBe(
			"enabled",
		);
	});
});

describe("readCodexHooksFlag — negative (must not report enabled)", () => {
	it("N1: the reviewer's wrong-table case — true under [other], false under [features]", () => {
		expect(readCodexHooksFlag("[other]\nhooks = true\n\n[features]\nhooks = false\n")).toBe(
			"disabled",
		);
	});

	it("N2: true under an unrelated table only is ABSENT, not enabled", () => {
		expect(readCodexHooksFlag("[other]\nhooks = true\n")).toBe("absent");
	});

	it("N3: a commented-out flag does not count", () => {
		expect(readCodexHooksFlag("[features]\n# hooks = true\n")).toBe("absent");
	});

	it("N4: an explicit false is disabled, not absent — the message differs", () => {
		expect(readCodexHooksFlag("[features]\nhooks = false\n")).toBe("disabled");
	});

	it("N5: a dotted sub-table is not [features]", () => {
		expect(readCodexHooksFlag("[features.nested]\nhooks = true\n")).toBe("absent");
	});

	it("N6: an empty document is absent", () => {
		expect(readCodexHooksFlag("")).toBe("absent");
	});
});

// ===========================================
// Exactly-one-`hooks` canonicalization matrix
// ===========================================
// The defect this pins: input
//
//     [features]
//     hooks = false
//     codex_hooks = true
//
// used to produce `hooks = false` AND `hooks = true` in the same table while
// reporting "migrated". Strict TOML parsers REJECT a duplicate key, so a
// "successful" migration could disable Codex hooks outright.
//
// The matrix crosses canonical true/false/absent/duplicate against legacy
// true/false/absent/duplicate, in both orderings, with comments and unrelated
// tables present, over LF and CRLF. Every case asserts the same things: exactly
// one `hooks =` assignment inside `[features]`, valued `true`, no active
// `codex_hooks` left inside `[features]`, and unrelated tables byte-identical.

/** Table-aware scan of the OUTPUT — the semantic a TOML parser would apply. */
function featuresAssignmentsOf(toml: string): Array<{ key: string; value: string }> {
	const found: Array<{ key: string; value: string }> = [];
	let table = "";
	for (const rawLine of toml.split("\n")) {
		const line = rawLine.replace(/#[^\n]*/, "");
		const header = /^\s*\[([^\][]+)\]\s*$/.exec(line);
		if (header) {
			table = (header[1] ?? "").trim();
			continue;
		}
		if (table !== "features") continue;
		const assignment = /^\s*(hooks|codex_hooks)\s*=\s*(\S+)/.exec(line);
		if (assignment) found.push({ key: assignment[1] ?? "", value: assignment[2] ?? "" });
	}
	return found;
}

const CANONICAL_CASES: Record<string, string[]> = {
	"canonical-absent": [],
	"canonical-true": ["hooks = true"],
	"canonical-false": ["hooks = false"],
	"canonical-duplicate-true": ["hooks = true", "hooks = true"],
	"canonical-duplicate-mixed": ["hooks = true", "hooks = false"],
};

const LEGACY_CASES: Record<string, string[]> = {
	"legacy-absent": [],
	"legacy-true": ["codex_hooks = true"],
	"legacy-false": ["codex_hooks = false"],
	"legacy-duplicate-mixed": ["codex_hooks = true", "codex_hooks = false"],
};

const EOL_CASES = [
	["LF", "\n"],
	["CRLF", "\r\n"],
] as const;

/** Fixture with comments, an unrelated table that carries BOTH spellings of the
 *  key (it must survive untouched — Codex never reads it), and a table after
 *  `[features]` so the block is bounded. */
function buildFixture(assignments: string[], eol: string): string {
	return [
		"# Generated by interlinked enable — do not remove the codex_hooks flag",
		"# unless you intend to disable Interlinked CLI hooks for Codex.",
		"",
		"[model]",
		'name = "synthetic-model-v5"',
		"",
		"[other]",
		"hooks = true",
		"codex_hooks = false",
		"",
		"[features]",
		"# hooks = true (documentation only)",
		"foo = 42 # keep me",
		...assignments,
		"",
		"[profiles.default]",
		'approval_policy = "never"',
		"",
	].join(eol);
}

describe("ensureCodexFeatureFlag — canonicalization leaves EXACTLY ONE hooks key", () => {
	let tmp: string;

	beforeEach(() => {
		tmp = mkdtempSync(join(tmpdir(), "codex-matrix-"));
	});

	afterEach(() => {
		rmSync(tmp, { recursive: true, force: true });
	});

	function run(body: string): string {
		const tomlPath = join(tmp, ".codex", "config.toml");
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, body);
		ensureCodexFeatureFlag(tmp);
		return readFileSync(tomlPath, "utf-8");
	}

	for (const [canonicalName, canonicalLines] of Object.entries(CANONICAL_CASES)) {
		for (const [legacyName, legacyLines] of Object.entries(LEGACY_CASES)) {
			for (const order of ["canonical-first", "legacy-first"]) {
				for (const [eolName, eol] of EOL_CASES) {
					const assignments =
						order === "canonical-first"
							? [...canonicalLines, ...legacyLines]
							: [...legacyLines, ...canonicalLines];
					const label = `${canonicalName} x ${legacyName} x ${order} x ${eolName}`;

					it(`P: ${label} — one canonical hooks = true, no codex_hooks left`, () => {
						const out = run(buildFixture(assignments, eol));
						expect(featuresAssignmentsOf(out)).toEqual([{ key: "hooks", value: "true" }]);
						expect(readCodexHooksFlag(out)).toBe("enabled");
					});

					it(`N: ${label} — unrelated tables and comments untouched`, () => {
						const out = run(buildFixture(assignments, eol));
						expect(out).toContain(`[model]${eol}name = "synthetic-model-v5"`);
						expect(out).toContain(`[other]${eol}hooks = true${eol}codex_hooks = false`);
						expect(out).toContain(`[profiles.default]${eol}approval_policy = "never"`);
						expect(out).toContain("# hooks = true (documentation only)");
						expect(out).toContain("foo = 42 # keep me");
					});

					it(`N: ${label} — line endings stay uniform`, () => {
						const out = run(buildFixture(assignments, eol));
						const crlfCount = out.split("\r\n").length - 1;
						const bareLf = out.split("\n").length - 1 - crlfCount;
						expect(eolName === "CRLF" ? bareLf : crlfCount).toBe(0);
					});
				}
			}
		}
	}
});

describe("ensureCodexFeatureFlag — the reported duplicate-key defect, minimal repro", () => {
	let tmp: string;

	beforeEach(() => {
		tmp = mkdtempSync(join(tmpdir(), "codex-dupe-"));
	});

	afterEach(() => {
		rmSync(tmp, { recursive: true, force: true });
	});

	function run(body: string): string {
		const tomlPath = join(tmp, ".codex", "config.toml");
		mkdirSync(join(tmp, ".codex"), { recursive: true });
		writeFileSync(tomlPath, body);
		ensureCodexFeatureFlag(tmp);
		return readFileSync(tomlPath, "utf-8");
	}

	it("P1: `hooks = false` + `codex_hooks = true` collapses to one `hooks = true`", () => {
		// The exact input that produced `hooks = false` then `hooks = true`.
		expect(run("[features]\nhooks = false\ncodex_hooks = true\n")).toBe(
			"[features]\nhooks = true\n",
		);
	});

	it("P2: `codex_hooks = true` + `hooks = false` (reverse order) collapses too", () => {
		expect(run("[features]\ncodex_hooks = true\nhooks = false\n")).toBe(
			"[features]\nhooks = true\n",
		);
	});

	it("P3: a lone canonical `hooks = false` is flipped, not duplicated", () => {
		// The old writer appended a second `hooks = true` after it.
		expect(run("[features]\nhooks = false\n")).toBe("[features]\nhooks = true\n");
	});

	it("P4: duplicate canonical keys collapse to one", () => {
		expect(run("[features]\nhooks = true\nhooks = true\nfoo = 1\n")).toBe(
			"[features]\nhooks = true\nfoo = 1\n",
		);
	});

	it("P5: a non-boolean value is replaced wholesale rather than left ambiguous", () => {
		expect(run('[features]\nhooks = "yes"\n')).toBe("[features]\nhooks = true\n");
	});

	it("P6: CRLF — `hooks = false` + `codex_hooks = true` collapses and stays CRLF", () => {
		expect(run("[features]\r\nhooks = false\r\ncodex_hooks = true\r\n")).toBe(
			"[features]\r\nhooks = true\r\n",
		);
	});
});

describe("findFeaturesHooksAssignmentCounts", () => {
	it("counts a legacy `codex_hooks` assignment separately from `hooks` (the codex_hooks++ arm)", () => {
		// No `hooks` key at all, so the loop's every iteration takes the
		// `else` arm — the observable is codex_hooks landing at 1 while
		// hooks stays 0, which only that arm can produce.
		const counts = findFeaturesHooksAssignmentCounts("[features]\ncodex_hooks = true\n");
		expect(counts).toEqual({ hooks: 0, codex_hooks: 1 });
	});

	it("counts each key independently when both a canonical and a duplicate legacy key are present", () => {
		const counts = findFeaturesHooksAssignmentCounts(
			"[features]\nhooks = true\ncodex_hooks = true\ncodex_hooks = false\n",
		);
		expect(counts).toEqual({ hooks: 1, codex_hooks: 2 });
	});
});
