// ===========================================
// Guard Hooks — Git hook install/uninstall for reservation enforcement
// ===========================================
// Generates and manages git pre-commit/pre-push hooks that call
// `interlinked guard check` to verify file reservations.

import { execSync } from "node:child_process";
import {
	chmodSync,
	existsSync,
	mkdirSync,
	readFileSync,
	renameSync,
	unlinkSync,
	writeFileSync,
} from "node:fs";
import { isAbsolute, join } from "node:path";

export const GUARD_CACHE_FILE = "guard-cache.json";

const GUARD_MARKER = "# interlinked-guard";

/**
 * Resolve the git hooks directory, respecting core.hooksPath config
 * (used by Husky, Lefthook, etc.).
 */
function resolveHooksDir(gitRoot: string): string {
	try {
		const hooksPath = execSync("git config core.hooksPath", {
			cwd: gitRoot,
			encoding: "utf-8",
			timeout: 5000,
			stdio: ["pipe", "pipe", "pipe"],
		}).trim();
		if (hooksPath) {
			return isAbsolute(hooksPath) ? hooksPath : join(gitRoot, hooksPath);
		}
	} catch (_err) {
		/* intentional: no custom core.hooksPath configured — fall through to .git/hooks default */
	}
	return join(gitRoot, ".git", "hooks");
}

/**
 * Generate the guard hook shell script content.
 * The script calls `interlinked guard check` with staged files and
 * exits based on the guard mode (warn=0, block=non-zero on conflicts).
 */
function generateGuardScript(hookType: "pre-commit" | "pre-push"): string {
	const isPreCommit = hookType === "pre-commit";

	return `#!/bin/sh
${GUARD_MARKER}
# Auto-generated by Interlinked CLI — do not edit manually.
# This hook checks staged files against active file reservations.
# Mode is read from .interlinked/config.local.json (guard_mode: warn|block).

# Find the interlinked CLI binary
INTERLINKED_BIN=""
if command -v interlinked >/dev/null 2>&1; then
    INTERLINKED_BIN="interlinked"
else
    echo "[interlinked guard] CLI not found. Skipping reservation check." >&2
    exit 0
fi

${isPreCommit ? "# Get staged files\nFILES=$(git diff --cached --name-only 2>/dev/null)" : "# Get files changed in push\nFILES=$(git diff --name-only @{push}.. 2>/dev/null || git diff --name-only HEAD~1 2>/dev/null)"}

if [ -z "$FILES" ]; then
    exit 0
fi

# Convert newlines to --files args
FILE_ARGS=""
while IFS= read -r file; do
    if [ -n "$file" ]; then
        FILE_ARGS="$FILE_ARGS --files $file"
    fi
done <<EOF
$FILES
EOF

# Run guard check (JSON mode for machine parsing)
# Capture stderr separately so errors are visible
RESULT=$($INTERLINKED_BIN guard check $FILE_ARGS --json 2>"\${TMPDIR:-/tmp}/.interlinked-guard-stderr.$$")
EXIT_CODE=$?

if [ -s "\${TMPDIR:-/tmp}/.interlinked-guard-stderr.$$" ]; then
    cat "\${TMPDIR:-/tmp}/.interlinked-guard-stderr.$$" >&2
fi
rm -f "\${TMPDIR:-/tmp}/.interlinked-guard-stderr.$$"

if [ $EXIT_CODE -ne 0 ] && [ -n "$RESULT" ]; then
    # Parse conflicts from JSON
    HAS_CONFLICTS=$(echo "$RESULT" | grep -c '"clean": false' 2>/dev/null || echo "0")
    if [ "$HAS_CONFLICTS" -gt 0 ]; then
        # Re-run in normal mode for human-readable output
        $INTERLINKED_BIN guard check $FILE_ARGS >&2
        exit $EXIT_CODE
    fi
fi

# If guard check succeeded or couldn't run, allow the operation
exit 0
`;
}

interface InstallGuardHookResult {
	installed: boolean;
	backed_up?: string;
}

/**
 * Install a guard hook into .git/hooks/.
 * If an existing hook exists, backs it up and creates a wrapper.
 */
export function installGuardHook(
	gitRoot: string,
	hookType: "pre-commit" | "pre-push",
): InstallGuardHookResult {
	const hooksDir = resolveHooksDir(gitRoot);
	if (!existsSync(hooksDir)) {
		mkdirSync(hooksDir, { recursive: true });
	}

	const hookPath = join(hooksDir, hookType);
	const backupPath = join(hooksDir, `${hookType}.interlinked-orig`);

	// Check if our hook is already installed
	if (existsSync(hookPath)) {
		const existing = readFileSync(hookPath, "utf-8");
		if (existing.includes(GUARD_MARKER)) {
			return { installed: false };
		}

		// Back up existing hook
		renameSync(hookPath, backupPath);

		// Create wrapper that runs both
		const wrapperScript = `#!/bin/sh
${GUARD_MARKER}-wrapper
# Wrapper: runs original hook then Interlinked guard hook.

# Run original hook first
if [ -x "${backupPath}" ]; then
    "${backupPath}"
    ORIG_EXIT=$?
    if [ $ORIG_EXIT -ne 0 ]; then
        exit $ORIG_EXIT
    fi
fi

# Run Interlinked guard
${generateGuardScript(hookType).split("\n").slice(1).join("\n")}
`;
		writeFileSync(hookPath, wrapperScript);
		chmodSync(hookPath, 0o755);
		return { installed: true, backed_up: backupPath };
	}

	// No existing hook — install directly
	writeFileSync(hookPath, generateGuardScript(hookType));
	chmodSync(hookPath, 0o755);
	return { installed: true };
}

interface UninstallGuardHookResult {
	removed: boolean;
	restored?: string;
}

/**
 * Uninstall a guard hook from .git/hooks/.
 * Restores the original hook if it was backed up.
 */
export function uninstallGuardHook(
	gitRoot: string,
	hookType: "pre-commit" | "pre-push",
): UninstallGuardHookResult {
	const hooksDir = resolveHooksDir(gitRoot);
	const hookPath = join(hooksDir, hookType);
	const backupPath = join(hooksDir, `${hookType}.interlinked-orig`);

	if (!existsSync(hookPath)) {
		return { removed: false };
	}

	const content = readFileSync(hookPath, "utf-8");
	if (!content.includes(GUARD_MARKER)) {
		return { removed: false };
	}

	// Remove our hook
	unlinkSync(hookPath);

	// Restore backup if it exists
	if (existsSync(backupPath)) {
		renameSync(backupPath, hookPath);
		return { removed: true, restored: hookPath };
	}

	return { removed: true };
}

interface GuardHookStatus {
	pre_commit: boolean;
	pre_push: boolean;
}

/**
 * Check if guard hooks are installed.
 */
export function getGuardHookStatus(gitRoot: string): GuardHookStatus {
	const hooksDir = resolveHooksDir(gitRoot);

	const checkHook = (hookType: string): boolean => {
		const hookPath = join(hooksDir, hookType);
		if (!existsSync(hookPath)) return false;
		try {
			const content = readFileSync(hookPath, "utf-8");
			return content.includes(GUARD_MARKER);
		} catch (_err) {
			/* intentional: unreadable hook file — treat as "not our hook" */
			return false;
		}
	};

	return {
		pre_commit: checkHook("pre-commit"),
		pre_push: checkHook("pre-push"),
	};
}
