// Auto-extracted from hooks.ts by the sweep refactor.
// The big template literal emitting `.interlinked/hooks/interlinked-activity.mjs`
// was split out of hooks.ts to keep that file focused on install/uninstall logic.
//
// This file holds the DATA — the .mjs runtime script that gets written into
// user projects by `interlinked enable`. The generated .mjs must remain
// self-contained (no imports from the CLI package) because it is deployed
// standalone and must work even if the CLI is uninstalled.
//
// Do not edit the pattern strings (like `rm -rf`, `catch (_err) { void 0; /* intentional: no-op */ }`) inside this
// template — they are data used at runtime, not code.

//
// The template is assembled from sibling chunk modules under `./hook-template-chunks/`.
// Each chunk is a contiguous slice of the generated .mjs and exports a string constant.
// `buildHookScript` stitches them back together; the byte output is identical to the
// pre-split template. See `hooks-template.test.ts` for the byte-level invariants.

import { type HarnessModePreset, QUALITY_MODE } from "../harness/rules/modes.js";
import { EVENT_NORMALIZERS_CHUNK } from "./hook-template-chunks/event-normalizers.js";
import { GUARDS_INLINE_CHUNK } from "./hook-template-chunks/guards-inline.js";
import { PROVIDER_RESPONSES_CHUNK } from "./hook-template-chunks/provider-responses.js";
import { REDACTION_CHUNK } from "./hook-template-chunks/redaction.js";
import { SESSION_STATE_CHUNK } from "./hook-template-chunks/session-state.js";
import { SKIP_PATHS_CHUNK } from "./hook-template-chunks/skip-paths.js";

/**
 * Build the Interlinked activity hook script (`.mjs`) for the given version.
 * The version is embedded in the first comment for staleness detection. The
 * optional `modePreset` argument bakes the per-tier `HARNESS_POST_TIMEOUT_MS`
 * literal into the generated runtime — re-render the script (via
 * `writeHookScript`) every time the mode changes. Defaults to QUALITY_MODE
 * (50 s) so existing call-sites that pass only the version keep working.
 */
export function buildHookScript(version: string, modePreset?: HarnessModePreset): string {
	const preset = modePreset ?? QUALITY_MODE;
	const postTimeoutMs = preset.post_timeout_ms;
	const modeName = preset.name;
	return `#!/usr/bin/env node
// interlinked-hook-version: ${version}
// ===========================================
// Interlinked CLI Activity Hook (auto-generated)
// ===========================================
// Bridges lifecycle and tool-use events from AI coding agents into Interlinked CLI local logs
// and the server.
// Supports: Claude Code (14 events), GitHub Copilot CLI
// Generated by: interlinked enable
// Do not edit manually — re-run 'interlinked enable' to regenerate.

import { readFileSync, existsSync, appendFileSync, writeFileSync, mkdirSync, openSync, readSync, closeSync, statSync, unlinkSync, renameSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { createConnection } from "node:net";
import { execSync, execFileSync, spawn as nodeSpawn } from "node:child_process";
import { createHash } from "node:crypto";

const CWD = process.cwd();

// --- Resolve data directory (mirrors config.ts getDataDir logic) ---
function resolveDataDir() {
    if (process.env.INTERLINKED_DATA_DIR) return process.env.INTERLINKED_DATA_DIR;
    const configDir = process.env.INTERLINKED_HOME || join(CWD, ".interlinked");
    const localConfigPath = join(configDir, "config.local.json");
    if (existsSync(localConfigPath)) {
        try {
            const lc = JSON.parse(readFileSync(localConfigPath, "utf-8"));
            if (lc.data_dir) return lc.data_dir;
        } catch (_err) { void 0; /* intentional: no-op */ }
    }
    return configDir;
}

function resolveConfigDir() {
    return process.env.INTERLINKED_HOME || join(CWD, ".interlinked");
}

const CONFIG_DIR = resolveConfigDir();
const DATA_DIR = resolveDataDir();

// Walk up from CWD looking for the nearest .interlinked/harness.sock.
// Lets a harness daemon rooted at a monorepo ancestor serve subdir edits
// without each subdir needing its own daemon. Falls back to the local
// CONFIG_DIR/harness.sock if no ancestor socket exists (so first-run
// scenarios — before any daemon is started — still see the local path).
function resolveHarnessSocket() {
    let dir = CWD;
    for (let i = 0; i < 10; i++) {
        const candidate = join(dir, ".interlinked", "harness.sock");
        if (existsSync(candidate)) return candidate;
        const parent = dirname(dir);
        if (parent === dir) break;
        dir = parent;
    }
    return join(CONFIG_DIR, "harness.sock");
}
const CONFIG_LOCAL_PATH = join(CONFIG_DIR, "config.local.json");
const CONFIG_SHARED_PATH = join(CONFIG_DIR, "config.json");
const ACTIVITY_PATH = join(DATA_DIR, "activity.jsonl");
const SESSIONS_DIR = join(DATA_DIR, "sessions");
const SYNC_STATE_PATH = join(DATA_DIR, "sync-state.json");
const REALTIME_RETRY_PATH = join(DATA_DIR, "realtime-retry.jsonl");
const SYNC_ERRORS_PATH = join(DATA_DIR, "sync-errors.jsonl");

// Track active subagent for attribution
let activeSubagent = null;

${SKIP_PATHS_CHUNK}

${REDACTION_CHUNK}

// ===========================================
// Harness Connection — Guard evaluation via Unix socket
// ===========================================
// Connects to the Interlinked Harness server for PreToolUse guard evaluation.
// Falls back to inline pattern matching if harness is not running.

const HARNESS_SOCK_PATH = resolveHarnessSocket();
const PENDING_WARNINGS_PATH = join(DATA_DIR, "pending-quality-warnings.json");
const HARNESS_PRE_TIMEOUT_MS = 5000;  // PreToolUse: allows grep acceleration (ripgrep on candidates)
const HARNESS_POST_TIMEOUT_MS = ${postTimeoutMs}; // PostToolUse: from harness mode "${modeName}" — see src/harness/rules/modes.ts. Re-rendered on every \`interlinked harness mode <name>\` change.
const HARNESS_USER_PROMPT_TIMEOUT_MS = 35000; // UserPromptSubmit: must exceed METACODER_TIMEOUT_DEFAULT_MS (30s) so the hook doesn't race the harness's clean timeout response and trigger a spurious cold-fallback. Plan §2.4 / metacoding-agent-plan.md.

/**
 * Flush any pending quality warnings from a previous PostToolUse to stderr.
 * Called at the start of every PreToolUse so the agent sees warnings
 * from the file it just edited BEFORE its next tool call.
 *
 * BLOCKING: If the harness is still running quality checks (marker file exists),
 * waits up to 12 seconds for checks to complete. This ensures the agent sees
 * all quality issues before proceeding.
 */
function flushPendingWarnings() {
    try {
        const markerPath = join(DATA_DIR, "quality-check-in-progress");

        // Wait for harness to finish quality checks (blocks the agent).
        if (existsSync(markerPath)) {
            const maxWaitMs = 12000;
            const start = Date.now();
            while (existsSync(markerPath) && (Date.now() - start) < maxWaitMs) {
                const waitUntil = Date.now() + 50;
                while (Date.now() < waitUntil) { /* spin */ }
            }
            // Clean up stale marker if harness timed out
            if (existsSync(markerPath)) {
                try { unlinkSync(markerPath); } catch (_err) { void 0; /* intentional: no-op */ }
            }
        }

        if (!existsSync(PENDING_WARNINGS_PATH)) return;
        const raw = readFileSync(PENDING_WARNINGS_PATH, "utf-8");
        const warnings = JSON.parse(raw);
        if (Array.isArray(warnings) && warnings.length > 0) {
            process.stderr.write("\\n[interlinked] Quality issues from previous edit:\\n");
            for (const w of warnings) {
                process.stderr.write(w + "\\n");
            }
            process.stderr.write("\\n");
        }
        unlinkSync(PENDING_WARNINGS_PATH);
    } catch {
        // Stale or corrupt file — clean up silently
        try { unlinkSync(PENDING_WARNINGS_PATH); } catch (_err) { void 0; /* intentional: no-op */ }
    }
}

/**
 * Auto-heal a stale harness: detect dead PID / orphaned socket and restart.
 * Called when evaluateViaHarness returns null (connection failed).
 * Rate-limited: at most once per 30 seconds per session to avoid restart storms.
 */
const HARNESS_PID_PATH = join(CONFIG_DIR, "harness.pid");
let lastRestartAttemptMs = 0;
const RESTART_COOLDOWN_MS = 30000;
let restartAttempted = false;

function tryHealHarness() {
    const now = Date.now();
    if (now - lastRestartAttemptMs < RESTART_COOLDOWN_MS) return false;
    lastRestartAttemptMs = now;

    try {
        // Check if PID file exists
        const pidFileExists = existsSync(HARNESS_PID_PATH);
        const sockFileExists = existsSync(HARNESS_SOCK_PATH);

        if (!pidFileExists && !sockFileExists) {
            // Harness was never started — try to start it
            if (!restartAttempted) {
                restartAttempted = true;
                process.stderr.write("[interlinked:harness] Harness not running — starting automatically...\\n");
                tryAutoStartHarness();
                return true;
            }
            return false;
        }

        // Check if the PID is still alive
        if (pidFileExists) {
            try {
                const pid = parseInt(readFileSync(HARNESS_PID_PATH, "utf-8").trim(), 10);
                if (!isNaN(pid)) {
                    try {
                        process.kill(pid, 0); // signal 0 = check existence
                        // Process is alive but socket failed — might be starting up, wait
                        return false;
                    } catch (_err) { void 0; /* intentional: Process is dead — stale PID file */ }
                }
            } catch (_err) { void 0; /* intentional: no-op */ }
        }

        // Harness is stale: clean up and restart
        process.stderr.write("[interlinked:harness] Harness is stale — restarting...\\n");
        try { unlinkSync(HARNESS_PID_PATH); } catch (_err) { void 0; /* intentional: no-op */ }
        try { unlinkSync(HARNESS_SOCK_PATH); } catch (_err) { void 0; /* intentional: no-op */ }

        // Also clean up stale marker files that would block the agent
        const markerPath = join(DATA_DIR, "quality-check-in-progress");
        try { unlinkSync(markerPath); } catch (_err) { void 0; /* intentional: no-op */ }

        tryAutoStartHarness();
        restartAttempted = true;
        return true;
    } catch {
        return false;
    }
}

/**
 * Send an event to the harness server and get a decision.
 * Returns null if harness is not available (fallback to inline).
 * Timeout varies: PreToolUse is fast (500ms), PostToolUse allows time for quality checks (15s).
 */
function evaluateViaHarness(harnessEvent) {
    const isPreTool = harnessEvent.hook_event === "PreToolUse" || harnessEvent.hook_event === "BeforeTool";
    const isUserPromptCall = harnessEvent.hook_event === "UserPromptSubmit" || harnessEvent.hook_event === "BeforeAgent";
    // UserPromptSubmit runs the metacoder synchronously inside the harness
    // (Opus 4.7 max / GPT-5.5 high, ~30s budget). The hook must wait
    // strictly longer than the metacoder's internal timeout so the harness
    // can finalize an allow/additional_context reply before the socket
    // gives up. Drift between these two budgets = 100% cold-fallback.
    const timeoutMs = isPreTool
        ? HARNESS_PRE_TIMEOUT_MS
        : isUserPromptCall
            ? HARNESS_USER_PROMPT_TIMEOUT_MS
            : HARNESS_POST_TIMEOUT_MS;

    return new Promise((resolve) => {
        if (!existsSync(HARNESS_SOCK_PATH)) {
            resolve(null); // Harness not running
            return;
        }
        const timeout = setTimeout(() => {
            try { sock.destroy(); } catch (_err) { void 0; /* intentional: no-op */ }
            resolve(null); // Timeout — fall back to inline
        }, timeoutMs);

        const sock = createConnection(HARNESS_SOCK_PATH);
        let responseData = "";

        sock.on("connect", () => {
            sock.write(JSON.stringify(harnessEvent) + "\\n");
        });
        let resolved = false;
        sock.on("data", (chunk) => {
            responseData += chunk.toString();
            // Look for newline-delimited JSON
            const newlineIdx = responseData.indexOf("\\n");
            if (newlineIdx !== -1 && !resolved) {
                resolved = true;
                clearTimeout(timeout);
                sock.destroy();
                try {
                    resolve(JSON.parse(responseData.slice(0, newlineIdx)));
                } catch {
                    resolve(null);
                }
            }
        });
        sock.on("error", () => {
            if (resolved) return;
            resolved = true;
            clearTimeout(timeout);
            resolve(null);
        });
        sock.on("close", () => {
            if (resolved) return;
            resolved = true;
            clearTimeout(timeout);
            if (responseData.trim()) {
                try { resolve(JSON.parse(responseData.trim())); } catch { resolve(null); }
            } else {
                resolve(null);
            }
        });
    });
}

const INLINE_STRONG_TYPING_PATTERNS = [
    /:\\s*any\\s*[;,)>=[\\]|&\\n\\r]/,
    /<\\s*any\\s*[>,]/,
    /\\bas\\s+any\\b/,
    /\\)\\s*:\\s*any\\b/,
    /\\bas\\s+unknown\\b/,
];

function stripInlineStringLiterals(line) {
    let result = line.replace(/"(?:[^"\\\\]|\\\\.)*"/g, '""');
    result = result.replace(/'(?:[^'\\\\]|\\\\.)*'/g, "''");
    result = result.replace(/\`(?:[^\`\\\\]|\\\\.)*\`/g, "\`\`");
    return result;
}

function findInlineStrongTypingMatches(content) {
    const lines = content.split("\\n");
    const matches = [];
    for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        const trimmed = line.trim();
        if (trimmed.startsWith("//") || trimmed.startsWith("*") || trimmed.startsWith("/*")) continue;
        if (/^\\s*['"\`]/.test(line) && /['"\`]\\s*[;,]?\\s*$/.test(line)) continue;
        const stripped = stripInlineStringLiterals(line);
        for (const pattern of INLINE_STRONG_TYPING_PATTERNS) {
            if (pattern.test(stripped)) {
                matches.push({ line: i + 1, text: trimmed.slice(0, 120) });
                break;
            }
        }
    }
    return matches;
}

function inlinePostToolFallback(rawInput, event) {
    const toolName = event.tool_name || rawInput.tool_name || null;
    const toolInput = rawInput.tool_input || event.tool_input || null;
    const filePath = extractFilePath(toolName, toolInput);
    if (!filePath || !existsSync(filePath)) return null;
    if (!/\\.(?:tsx?|jsx?|mjs|cjs)$/.test(filePath)) return null;
    // Parity with the daemon's strong_typing exemption (see
    // quality-checks.ts:223–225): tests legitimately use casts to construct
    // partial fixtures of large interface types and to drive edge-case paths.
    // (Note: \\. in this template-literal source emits \\. in the .mjs script,
    // which the runtime parses as \\.\\. So the regex matches a literal dot.)
    if (/\\.(?:test|spec)\\.(?:tsx?|jsx?|mjs|cjs)$/.test(filePath)) {
        return { summary: "inline strong_typing clean" };
    }
    let content = "";
    try {
        content = readFileSync(filePath, "utf-8");
    } catch {
        return null;
    }
    const matches = findInlineStrongTypingMatches(content);
    if (matches.length === 0) {
        return { summary: "inline strong_typing clean" };
    }
    const first = matches[0];
    const plural = matches.length === 1 ? "" : "s";
    return {
        warnings: [
            "[interlinked:strong_typing] " + filePath + " contains " + matches.length
                + " explicit any/unknown escape hatch occurrence" + plural
                + ". First: L" + first.line + " " + first.text,
        ],
        summary: "inline strong_typing warning",
    };
}

${GUARDS_INLINE_CHUNK}

/**
 * Try to auto-start the harness daemon on SessionStart.
 * Fire-and-forget, non-blocking. If Bun is not found, warn once.
 * First PreToolUse uses inline fallback; subsequent calls use harness once it's up.
 */
function isInterlinkedCliCheckout(cwd) {
    // Verify the current working directory is the interlinked-cli source
    // checkout, not just any project that happens to have a
    // dist/harness/server.js path. Read package.json and check the name.
    // Fail-closed on any error: a missing/malformed package.json should NOT
    // permit auto-spawning a project-local server.js as the daemon.
    try {
        const pkgPath = join(cwd, "package.json");
        if (!existsSync(pkgPath)) return false;
        const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"));
        return pkg && pkg.name === "interlinked-cli";
    } catch (_err) {
        void 0; /* intentional: fail-closed on read/parse error */
        return false;
    }
}

function tryAutoStartHarness(sessionId = null) {
    try {
        // Find harness server.js — prefer pre-compiled JS for fast startup.
        // CWD-relative dist is gated on the CWD being the interlinked-cli
        // source checkout (package.json name === "interlinked-cli").
        // Without the gate, any user repo that happens to have a
        // dist/harness/server.js artifact at that path would have its own
        // unrelated file spawned as the harness daemon — letting arbitrary
        // project-local code run and bypassing the installed CLI entirely.
        // The dev-loop convenience (a fresh \`npm run build\` is picked up
        // automatically) is preserved for the actual CLI checkout.
        const candidates = [];
        if (isInterlinkedCliCheckout(CWD)) {
            candidates.push(join(CWD, "dist", "harness", "server.js"));
        }
        candidates.push(
            join(CONFIG_DIR, "..", "cli", "dist", "harness", "server.js"),
            join(CONFIG_DIR, "..", "node_modules", "interlinked-cli", "dist", "harness", "server.js"),
            join(CONFIG_DIR, "..", "node_modules", ".bin", "interlinked-harness"),
        );

        // Also check global npm paths
        try {
            const globalDir = execSync("npm root -g", { encoding: "utf-8", timeout: 2000 }).trim();
            candidates.push(join(globalDir, "interlinked-cli", "dist", "harness", "server.js"));
        } catch (_err) { void 0; /* intentional: no-op */ }

        // Fall back to TypeScript source (slower — requires tsx or similar)
        candidates.push(
            join(CONFIG_DIR, "..", "cli", "src", "harness", "server.ts"),
            join(CONFIG_DIR, "..", "node_modules", "interlinked-cli", "src", "harness", "server.ts"),
        );

        let serverPath = null;
        for (const p of candidates) {
            if (existsSync(p)) { serverPath = p; break; }
        }

        if (!serverPath) {
            process.stderr.write("[interlinked] Harness server not found — inline fallback active.\\n");
            return;
        }

        // Spawn detached harness daemon using node
        const nodePath = process.execPath;
        const args = [serverPath, "--cwd", CWD, "--protocol", "dual"];
        if (sessionId) args.push("--session-id", String(sessionId));
        const child = nodeSpawn(nodePath, args, {
            detached: true,
            stdio: "ignore",
        });
        child.unref();

        process.stderr.write("[interlinked] Starting harness daemon...\\n");
    } catch (_err) { void 0; /* intentional: Never block the agent — silently fall back to inline guard */ }
}

// --- Last-check file for status line visibility ---
// Structured pipe-delimited format so the bash statusline can render
// outcome language (\"caught 3 new issues before they landed\") without
// fragile string parsing. One line, key=value fields separated by ' | '.
//
// Schema (additive — bash falls back gracefully on missing keys):
//   result=clean|warn|block|no_harness
//   file=<repo-relative path or empty>
//   tool=<tool name>
//   count=<number, warn only>
//   ms=<elapsed milliseconds, optional>
//   rule=<rule id, block only>
//   summary=<short reason, block only>
const LAST_CHECK_PATH = join(DATA_DIR, "last-check.txt");
function writeLastCheck(fields) {
    try {
        const parts = [];
        for (const [k, v] of Object.entries(fields)) {
            if (v === undefined || v === null || v === "") continue;
            // Strip pipes/newlines from values so the delimiter is unambiguous.
            const safe = String(v).replace(/[|\\r\\n]+/g, " ").trim();
            parts.push(k + "=" + safe);
        }
        writeFileSync(LAST_CHECK_PATH, parts.join(" | ") + "\\n");
    } catch (_err) { void 0; /* intentional: no-op */ }
}

// Extract the edited file path from a hook event so the statusline can
// say "src/foo.ts" instead of just "Edit". Returns "" for tools without
// a file (Bash, Grep, etc.) — caller falls back to tool name.
function lastCheckFile(event, rawInput) {
    const ti = (event && event.tool_input) || (rawInput && rawInput.tool_input) || null;
    if (!ti || typeof ti !== "object") return "";
    const path = ti.file_path || ti.filePath || ti.path || ti.notebook_path || "";
    if (typeof path !== "string" || !path) return "";
    const cwd = (rawInput && rawInput.cwd) || (event && event.cwd) || process.cwd();
    if (path.startsWith(cwd + "/")) return path.slice(cwd.length + 1);
    return path;
}

${SESSION_STATE_CHUNK}

async function main() {
    const localConfig = existsSync(CONFIG_LOCAL_PATH)
        ? safeReadConfig(CONFIG_LOCAL_PATH)
        : null;
    const sharedConfig = existsSync(CONFIG_SHARED_PATH)
        ? safeReadConfig(CONFIG_SHARED_PATH)
        : null;
    if (!localConfig && !sharedConfig) process.exit(0);
    const config = {
        ...(sharedConfig || {}),
        ...(localConfig || {}),
    };

    // Resolve active server entry — pairs server_url with workspace_id
    const activeKey = config.active_server || "production";
    const activeServer = config.servers?.[activeKey];
    const serverUrl = activeServer?.server_url || config.server_url;
    const workspaceId = activeServer?.workspace_id || config.workspace_id;
    const workspaceKey = config.default_workspace_key || "main";
    const projectKey = config.default_project || "main";
    const syncMode = config.sync_mode || "realtime";

    // Resolve auth — prefer access_token, fall back to agent_handle
    const authHeader = config.access_token
        ? "Bearer " + config.access_token
        : config.agent_handle
          ? "Bearer " + config.agent_handle
          : null;

    // Retry any previously buffered realtime payloads first.
    if (syncMode !== "local" && serverUrl) {
        await flushRealtimeRetry(serverUrl, authHeader);
    }

    // --- Client Handler Registry ---
    // Each entry: { name, detect(input, source), normalize(input) }
    // First match wins. Claude is the catch-all for stdin — keep it last.
    // Codex's payload shape mirrors Claude's, so it must be detected via
    // the INTERLINKED_CLIENT environment variable (set by the hook command
    // installed into .codex/hooks.json) before falling through to Claude.
    // To add a new client (Cursor, Opencode, Amp, etc.):
    //   1. Add a normalizer function (normalizeXxxEvent)
    //   2. Add a detector entry below
    const RUNNER_ENV = process.env.INTERLINKED_CLIENT || "";
    const CLIENT_HANDLERS = [
        { name: "copilot", detect: (input, src) => src === "stdin" && !input.hook_event_name && typeof input.timestamp === "number", normalize: normalizeCopilotEvent },
        { name: "codex", detect: (_input, src) => src === "stdin" && RUNNER_ENV === "codex", normalize: normalizeCodexEvent },
        // Cursor: detect via INTERLINKED_CLIENT env var (set by the hook
        // command we install into .cursor/hooks.json) OR via Cursor-specific
        // payload fields (cursor_version, conversation_id+generation_id) so
        // we still recognise the client if the env var got dropped by the
        // shell. Must come BEFORE the Claude catch-all because Cursor sends
        // hook_event_name like Claude does for some events.
        { name: "cursor", detect: (input, src) => src === "stdin" && (RUNNER_ENV === "cursor" || !!input.cursor_version || (!!input.conversation_id && !!input.generation_id)), normalize: normalizeCursorEvent },
        // Gemini: detect via INTERLINKED_CLIENT env var (set by the hook
        // command we install into .gemini/settings.json) OR via Gemini-specific
        // payload fields (gemini_session_id) OR via the PascalCase
        // Before/After-(Tool/Model/Agent) hook event names. Must come BEFORE
        // the Claude catch-all — Gemini's PascalCase event names overlap
        // with Claude's so the catch-all would otherwise normalize them
        // through the wrong dispatcher and leave normalizeGeminiEvent dead.
        { name: "gemini", detect: (input, src) => src === "stdin" && (RUNNER_ENV === "gemini" || !!input.gemini_session_id || (typeof input.hook_event_name === "string" && /^(Before|After)(Tool|Model|Agent)$/.test(input.hook_event_name))), normalize: normalizeGeminiEvent },
        // Future clients — add detectors here, before the Claude catch-all.
        // Example shape (NOT active code — documentation for adding a new handler):
        //   Example: { name: "opencode", detect: (input, src) => src === "stdin" && input.client === "opencode", normalize: normalizeOpencodeEvent }
        //   Example: { name: "amp",      detect: (input, src) => src === "stdin" && !!input.amp_session,       normalize: normalizeAmpEvent }
        { name: "claude", detect: (input, src) => src === "stdin", normalize: normalizeClaudeEvent },
    ];

    // Parse input from stdin (Claude Code, GitHub Copilot CLI, future clients)
    let rawInput;
    let hookEvent, sessionId;

    let stdin = "";
    try { stdin = readFileSync(0, "utf-8"); } catch { process.exit(0); }
    if (!stdin.trim()) process.exit(0);
    try { rawInput = JSON.parse(stdin); } catch { process.exit(0); }
    const inputSource = "stdin";

    hookEvent = rawInput.hook_event_name || null;
    sessionId = rawInput.session_id || rawInput.sessionId || null;
    // Capture the raw Cursor event name BEFORE normalization rewrites it to
    // a canonical PreToolUse/PostToolUse. Cursor's per-event response
    // capabilities (additional_context on postToolUse, ask on shell/MCP
    // gates) are encoded against the raw name in formatCursorResponse.
    const cursorNativeEvent = hookEvent;

    // Detect client and normalize event
    let event = null;
    let detectedClient = "unknown";
    for (const handler of CLIENT_HANDLERS) {
        if (handler.detect(rawInput, inputSource)) {
            event = handler.normalize(rawInput);
            detectedClient = handler.name;
            break;
        }
    }

    if (!event) process.exit(0);

    // Plan §reviewer-P4 (round 5): when the harness spawned this hook as
    // part of the metacoder's own \`claude -p\` subprocess, every prompt
    // we see here is internal metacoder traffic — its system prompt
    // plus the user's prompt plus project_instructions. Letting the
    // script continue would (a) re-trigger the harness recursion guard
    // (wasteful socket round-trip), (b) write the metacoder's own
    // prompt to activity.jsonl as if it were user activity, and (c) POST
    // it to the realtime sync endpoint. Exit silently. UserPromptSubmit
    // with no stdout = "allow", which is what Claude Code expects so
    // the metacoder subprocess can proceed.
    if (process.env.INTERLINKED_METACODER_SUBPROCESS === "1") {
        process.exit(0);
    }

    // Always resolve hookEvent from the normalized event so it carries the
    // canonical name (PreToolUse / PostToolUse / UserPromptSubmit / ...).
    // The downstream isPreTool / isPostTool / isUserPrompt checks AND the
    // harness server (server.ts isPreToolUse / isPostToolUse) speak canonical
    // names only. Copilot doesn't send hook_event_name (the normalizer sets
    // event.hook_event from payload shape); Cursor sends camelCase native
    // names like "beforeShellExecution" that the normalizer maps to the
    // canonical "PreToolUse" — keeping the raw native name here would skip
    // guard evaluation entirely on Cursor (destructive shell/MCP calls would
    // be allowed without the guard ever running).
    if (event.hook_event) {
        hookEvent = event.hook_event;
    }

    // Attach common fields available on all Claude Code events
    if (rawInput.cwd) event.cwd = rawInput.cwd;
    if (rawInput.permission_mode) event.permission_mode = rawInput.permission_mode;
    if (rawInput.transcript_path) event.transcript_path = rawInput.transcript_path;
    // Parent session linkage — Claude Code's Agent/Task tool fires the
    // child session with parent_tool_use_id pointing back at the launching
    // tool call, and the parent's session_id is reachable via the SubagentStart
    // / SubagentStop payload's parent_agent_name/parent_session_id field.
    if (rawInput.parent_session_id) event.parent_session_id = rawInput.parent_session_id;
    if (rawInput.parent_tool_use_id) event.parent_tool_use_id = rawInput.parent_tool_use_id;
    // Turn id — single identifier shared by every event between two
    // user_prompt events. Minted on user_prompt, stamped on everything else.
    stampTurnId(sessionId, event);

    // Extract new thinking blocks from transcript (real-time capture)
    const transcriptPath = rawInput.transcript_path || null;
    const thinkingContent = extractNewThinking(transcriptPath);
    if (thinkingContent) event.thinking = thinkingContent;

    const agentName = resolveAgentName(config, rawInput, event, detectedClient, sessionId);

    // ===========================================
    // SessionStart: auto-start harness if socket missing
    // ===========================================
    if (hookEvent === "SessionStart" && !existsSync(HARNESS_SOCK_PATH)) {
        tryAutoStartHarness(sessionId);
    }
    // Daily graph snapshot — fires once per 24h on any SessionStart so
    // graph-history.jsonl carries a longitudinal trend without needing
    // a daemon. Cheap mtime check first, full walk only when stale.
    if (hookEvent === "SessionStart") {
        try { maybeSnapshotGraph(rawInput.cwd || event.cwd || process.cwd()); }
        catch (_err) { void 0; /* intentional: snapshot best-effort */ }
    }
    // Costs ledger — emit token-usage rows for any new turns in the
    // transcript when a turn ends (Stop / SessionEnd). The emitter
    // tracks its own byte cursor per session, so multiple Stop events
    // for the same session don't double-emit.
    if (hookEvent === "Stop" || hookEvent === "SessionEnd" || event.event_type === "agent_stop") {
        const tp = rawInput.transcript_path || event.transcript_path || null;
        try { emitCostsFromTranscript(sessionId, tp); }
        catch (_err) { void 0; /* intentional: cost ledger best-effort */ }
    }
    // Rule-stats rollup + suggestion-outcome reconciler — fire on
    // SessionEnd / Stop. Both gate on file mtime / cursor so rapid
    // repeated triggers don't redo the work.
    if (hookEvent === "Stop" || hookEvent === "SessionEnd") {
        try { maybeRollupRulesStats(); }
        catch (_err) { void 0; /* intentional: rollup best-effort */ }
        try { reconcileSuggestionOutcomes(rawInput.cwd || event.cwd || process.cwd()); }
        catch (_err) { void 0; /* intentional: reconciler best-effort */ }
    }

    // ===========================================
    // Guard Evaluation (PreToolUse / BeforeTool)
    // ===========================================
${PROVIDER_RESPONSES_CHUNK}

    // For PreToolUse events: evaluate via harness (or inline fallback).
    // If blocked, output decision to stdout and exit.
    // The local write and server POST still happen for audit trail.

    const isPreTool = hookEvent === "PreToolUse" || hookEvent === "BeforeTool";
    const isPostTool = hookEvent === "PostToolUse" || hookEvent === "AfterTool" || hookEvent === "PostToolUseFailure";
    const isUserPrompt = hookEvent === "UserPromptSubmit" || hookEvent === "BeforeAgent";
    let guardDecision = null;

    // ===========================================
    // Phase B.3 — Hook-side skip for excluded paths
    // ===========================================
    // For PostToolUse on file-edit tools: if the touched path matches the
    // user's \`skip_paths\` config (e.g. dist/**, node_modules/**),
    // short-circuit with the success shape BEFORE opening the daemon
    // socket — saves ~5 ms per excluded edit and eliminates daemon CPU
    // work entirely on the post-pipeline.
    //
    // PreToolUse is NOT skipped here, even if the path matches. The
    // PreToolUse path runs deterministic guards (repo confinement,
    // protected files, lockfile-tamper, destructive-pattern rules) that
    // MUST fire regardless of skip_paths — \`skip_paths\` is meant to
    // mute the noisy quality pipeline on generated/build output, not
    // to disable safety enforcement on those same paths. Earlier
    // versions short-circuited PreToolUse here, which let an Edit
    // targeted at \`dist/foo.js\` (or any other matched path) bypass
    // every pre_block rule unguarded.
    //
    // Lifecycle events (SessionStart, etc.) are NEVER skipped — the daemon
    // needs them for state tracking.
    if (isPostTool) {
        const skipToolName = event.tool_name || rawInput.tool_name || null;
        const skipToolInput = rawInput.tool_input || event.tool_input || null;
        const skipPath = extractFilePath(skipToolName, skipToolInput);
        if (skipPath && matchesSkipPath(skipPath)) {
            emitSkipDebug(skipPath, hookEvent);
            // For PostToolUse, route through formatProviderResponse so
            // Claude / Copilot / Codex / Cursor each see their expected
            // shape. The summary documents that the path was skipped.
            console.log(JSON.stringify(formatProviderResponse("post_success", {
                summary: "[interlinked:skip] path matched skip_paths",
            })));
            process.exit(0);
        }
    }

    // ===========================================
    // UserPromptSubmit: forward to harness for PII scan
    // ===========================================
    // If the content scanner is enabled and finds PII in the prompt, the
    // harness returns a redacted copy which we substitute into event.prompt
    // before the local JSONL write below. Never blocks — users can always
    // submit their prompt; we only mask the stored record.
    if (isUserPrompt && event.prompt) {
        const promptHarnessEvent = {
            hook_event: hookEvent,
            session_id: sessionId,
            agent_source: detectedClient,
            agent_name: agentName,
            tool_name: null,
            tool_input: null,
            prompt: event.prompt,
            cwd: rawInput.cwd || event.cwd || null,
            model: event.model || null,
            timestamp: new Date().toISOString(),
            // Recursion guard for the metacoder subprocess path — when the
            // harness spawns \`claude -p\` to invoke Opus 4.7, the subprocess
            // inherits this hook and fires its own UserPromptSubmit. The
            // sentinel env var lets the harness short-circuit. Plan §2.5.
            metacoder_subprocess: process.env.INTERLINKED_METACODER_SUBPROCESS === "1",
        };
        try {
            const promptDecision = await evaluateViaHarness(promptHarnessEvent);
            if (promptDecision && typeof promptDecision.redacted_prompt === "string") {
                event.prompt = promptDecision.redacted_prompt;
                if (event.tool_input_summary) {
                    // Keep the 200-char summary in sync with the masked prompt.
                    event.tool_input_summary = promptDecision.redacted_prompt.slice(0, 200);
                }
            }
            // Metacoder system_prompt_addendum — emit on stdout via the
            // provider-specific channel so the model sees it inline with the
            // user prompt. Claude/Codex use hookSpecificOutput.additionalContext;
            // other runners fall back to {} (no model-visible channel for
            // UserPromptSubmit). Plan §3.
            if (promptDecision && typeof promptDecision.additional_context === "string" && promptDecision.additional_context.length > 0) {
                const adviceResponse = formatProviderResponse("user_prompt_advice", {
                    summary: promptDecision.additional_context,
                });
                if (adviceResponse && Object.keys(adviceResponse).length > 0) {
                    console.log(JSON.stringify(adviceResponse));
                }
            }
        } catch (_err) { void 0; /* fail-open: raw prompt still gets inline secrets scrub via scrubPayload below */ }
    }

    // On PreToolUse: flush any pending quality warnings from the previous PostToolUse.
    // For Claude: writes to stderr (agents see it inline before their next action).
    // For Copilot: stderr is ignored, so we must DENY the next PreToolUse with the
    // warnings as the reason — it's the only way to surface feedback to the agent.
    if (isPreTool) {
        if (detectedClient === "copilot") {
            // Copilot ignores both stderr and non-deny stdout from hooks.
            // Quality warnings are logged locally but cannot be surfaced to the agent.
            // Only destructive command blocks (permissionDecision: "deny") reach the agent.
            // Clear pending warnings silently so they don't accumulate.
            try {
                const markerPath = join(DATA_DIR, "quality-check-in-progress");
                if (existsSync(markerPath)) { try { unlinkSync(markerPath); } catch (_err) { void 0; /* intentional: no-op */ } }
                if (existsSync(PENDING_WARNINGS_PATH)) { unlinkSync(PENDING_WARNINGS_PATH); }
            } catch (_err) { void 0; /* intentional: no-op */ }
        } else {
            flushPendingWarnings();
        }
    }

    if (isPreTool) {
        const preStartMs = Date.now();
        const harnessEvent = {
            hook_event: hookEvent,
            session_id: sessionId,
            agent_source: detectedClient,
            agent_name: agentName,
            tool_name: event.tool_name || rawInput.tool_name || null,
            tool_input: rawInput.tool_input || event.tool_input || null,
            tool_use_id: rawInput.tool_use_id || event.tool_use_id || null,
            cwd: rawInput.cwd || event.cwd || null,
            model: event.model || null,
            timestamp: new Date().toISOString(),
        };

        guardDecision = await evaluateViaHarness(harnessEvent);

        if (!guardDecision) {
            // Harness unavailable — try to heal (auto-restart if stale)
            const healed = tryHealHarness();
            if (healed) {
                // Wait briefly for harness to come up, then retry once
                const retryDelay = Date.now() + 1500;
                while (Date.now() < retryDelay) { /* spin */ }
                guardDecision = await evaluateViaHarness(harnessEvent);
            }
        }

        if (!guardDecision) {
            // Pass harnessEvent.tool_input (post-normalization), NOT rawInput.tool_input.
            // Clients like Cursor (beforeShellExecution: command at top level) and
            // Copilot (toolArgs as JSON string) don't carry the canonical
            // tool_input shape on rawInput; the normalizers project it onto
            // event.tool_input. Without this, the inline fallback silently
            // returned null on Cursor/Copilot and let destructive shell calls
            // through whenever the harness was unavailable.
            guardDecision = inlineGuardCheck(hookEvent, harnessEvent.tool_name, harnessEvent.tool_input);
        }

        const preElapsedMs = Date.now() - preStartMs;

        if (guardDecision?.warnings && guardDecision.warnings.length > 0) {
            for (const w of guardDecision.warnings) {
                process.stderr.write(w + "\\n");
            }
        }

        // If blocked on PreToolUse, output decision to stdout and exit
        if (guardDecision?.decision === "block") {
            appendLocal(event, hookEvent, sessionId, agentName, workspaceKey, projectKey);
            appendGuardDecision("block", guardDecision, event, hookEvent, sessionId, agentName, workspaceKey, projectKey, preElapsedMs);
            updateSessionState(sessionId, agentName, event);

            // Feed the statusline kinetic segment so a freshly-blocked action
            // shows up as "✗ blocked rm -rf · 2s ago · rule: block_rm_rf".
            const blockToolLabel = event.tool_name || rawInput.tool_name || "tool";
            const blockFile = lastCheckFile(event, rawInput);
            const blockSummary = (guardDecision.reason || "Blocked by Interlinked guard").split(/\\r?\\n/)[0].slice(0, 80);
            const blockRule = guardDecision.rule_id || guardDecision.rule || "";
            writeLastCheck({ result: "block", tool: blockToolLabel, file: blockFile, summary: blockSummary, rule: blockRule });

            if (guardDecision.grep_stats) {
                const stats = guardDecision.grep_stats;
                const selectivity = stats.selectivity_pct != null ? stats.selectivity_pct.toFixed(1) : "?";
                const header = "[interlinked:index] Searched " + stats.candidates + " candidate files (from " + stats.total_files + " total, " + selectivity + "% selectivity)";
                const body = guardDecision.reason || "No matches found.";
                console.log(JSON.stringify(formatProviderResponse("pre_block_grep", { reason: header + "\\n" + body })));
            } else {
                console.log(JSON.stringify(formatProviderResponse("pre_block", { reason: guardDecision.reason || "Blocked by Interlinked guard" })));
            }
            process.exit(0);
        }

        // "ask" → user confirmation required. Surface Claude Code's permission
        // prompt so the human approves per-call. Reason includes rule id and
        // instruction for context.
        if (guardDecision?.decision === "ask") {
            appendLocal(event, hookEvent, sessionId, agentName, workspaceKey, projectKey);
            appendGuardDecision("ask", guardDecision, event, hookEvent, sessionId, agentName, workspaceKey, projectKey, preElapsedMs);
            updateSessionState(sessionId, agentName, event);
            const askTool = event.tool_name || rawInput.tool_name || "unknown";
            const askRule = guardDecision.rule_id || guardDecision.rule || null;
            const askCoreReason = guardDecision.reason || "Interlinked pre-block rule matched — please confirm.";
            const askReason = askRule
                ? "[interlinked:" + askRule + "] tool=" + askTool + " — " + askCoreReason
                : "[interlinked] tool=" + askTool + " — " + askCoreReason;
            console.log(JSON.stringify(formatProviderResponse("pre_ask", {
                reason: askReason,
                // Ensure Claude's permission UI always has a human-facing explanation
                // even when a detector returns ask without an explicit system message.
                systemMessage: guardDecision.system_message || askReason,
            })));
            process.exit(0);
        }

        // Log PreToolUse warnings as guard_warn events
        if (guardDecision?.decision === "allow" && guardDecision.warnings?.length > 0) {
            appendGuardDecision("warn", guardDecision, event, hookEvent, sessionId, agentName, workspaceKey, projectKey, preElapsedMs);
        }

        // Log allow decisions (no warnings) so guard history is complete
        if (guardDecision?.decision === "allow" && (!guardDecision.warnings || guardDecision.warnings.length === 0)) {
            appendGuardDecision("allow", guardDecision, event, hookEvent, sessionId, agentName, workspaceKey, projectKey, preElapsedMs);
        }
    }

    // ===========================================
    // PostToolUse: Delegate quality checks to harness
    // ===========================================
    // The harness runs tsc, lint, secrets, strong_typing, and inline checks.
    // If harness is unavailable, degrade gracefully (no inline fallback).
    //
    // Phase 1 failure-recovery: every PostToolUse / PostToolUseFailure with
    // tool_outcome === "error" must reach the harness, regardless of tool
    // class — Channels 1/2/3/6 (recurrence, triage, recovery, explanation)
    // are tool-agnostic and need to see Bash/Read/Grep failures too. The
    // mutationTools gate below now only short-circuits *successful*
    // non-mutation Post events (where the harness has nothing to check).
    const mutationTools = new Set(["Edit", "Write", "MultiEdit", "NotebookEdit", "WriteFile", "EditFile", "write_file", "edit_file", "apply_patch", "create_file", "str_replace"]);
    // skipPostCheck: legacy gate kept disarmed so Phase 1 channels see every
    // failure. Any future "skip on this combo" logic threads through here.
    const skipPostCheck = false;

    // Fast-path: a SUCCESSFUL PostToolUse on a non-mutation tool (Bash that
    // exited 0, Read that returned content, Grep with results) — capture
    // locally, skip the harness round-trip. The pipeline only does
    // tsc/lint/structural on file edits, so for successful Bash/Read/Grep
    // the round-trip is pure latency. Critically, the gate now also checks
    // event.tool_outcome — failed Bash (tool_outcome === "error") must
    // reach the harness for Channels 1/2/3/6 to surface triage + recurrence.
    const postToolName = event.tool_name || rawInput.tool_name || "";
    const isMutationPost = mutationTools.has(postToolName);
    const postOutcomeIsError = event.tool_outcome === "error";
    if (isPostTool && !isMutationPost && !postOutcomeIsError && hookEvent !== "PostToolUseFailure") {
        appendLocal(event, hookEvent, sessionId, agentName, workspaceKey, projectKey);
        updateSessionState(sessionId, agentName, event);
        // Provide the empty success response so the agent's UI doesn't
        // think the hook failed. Format-aware so Cursor/Codex/Copilot
        // each see their expected envelope. No summary: a content-free
        // "observed" line on every Bash/Read/Grep/WebFetch is pure
        // context noise — the harness ran nothing, so there's nothing
        // to tell the model. The empty envelope keeps the validator
        // (Claude Code's hookEventName check) happy.
        console.log(JSON.stringify(formatProviderResponse("post_success", {})));
        process.exit(0);
    }

    if (isPostTool && !skipPostCheck) {
        const postStartMs = Date.now();
        const harnessEvent = {
            hook_event: hookEvent,
            session_id: sessionId,
            agent_source: detectedClient,
            agent_name: agentName,
            tool_name: event.tool_name || rawInput.tool_name || null,
            tool_input: rawInput.tool_input || event.tool_input || null,
            tool_use_id: rawInput.tool_use_id || event.tool_use_id || null,
            cwd: rawInput.cwd || event.cwd || null,
            model: event.model || null,
            timestamp: new Date().toISOString(),
            // Canonical post-event outcome fields populated by the per-client
            // normalizer's deriveToolOutcome step. Without these, Phase 1
            // failure-recovery channels (triage, recovery, recurrence) on
            // src/harness/server.ts can't see folded failures (Claude/Codex/
            // Gemini/Copilot deliver tool failures on the regular Post* event).
            tool_outcome: event.tool_outcome || null,
            error_message: event.error_message || null,
            exit_code: typeof event.exit_code === "number" ? event.exit_code : null,
            stderr: event.stderr || null,
            stdout: event.stdout || null,
            tool_response_sha256: event.tool_response_sha256 || null,
        };

        let postResult = await evaluateViaHarness(harnessEvent);

        if (!postResult) {
            // Harness unavailable — try to heal (auto-restart if stale)
            const healed = tryHealHarness();
            if (healed) {
                const retryDelay = Date.now() + 1500;
                while (Date.now() < retryDelay) { /* spin */ }
                postResult = await evaluateViaHarness(harnessEvent);
            }
        }

        if (!postResult) {
            postResult = inlinePostToolFallback(rawInput, event);
        }

        const postElapsedMs = Date.now() - postStartMs;

        if (postResult) {
            const warnings = postResult.warnings || [];

            if (warnings.length > 0) {
                const issueList = warnings.join("\\n\\n");
                const toolLabel = event.tool_name || "unknown";
                const editedFile = lastCheckFile(event, rawInput);
                writeLastCheck({ result: "warn", tool: toolLabel, file: editedFile, count: warnings.length, ms: postElapsedMs });
                const isBlockingPostDecision = postResult.decision === "block";
                const responseType = isBlockingPostDecision ? "post_block" : "post_warn";
                const responsePayload = isBlockingPostDecision
                    ? {
                        reason: issueList + "\\n\\nFix the issues above by changing the actual code.",
                    }
                    : {
                        reason: issueList,
                        summary: "[interlinked:" + toolLabel + "] Advisory findings:\\n" + issueList,
                    };
                console.log(JSON.stringify(formatProviderResponse(responseType, responsePayload)));
                appendLocal(event, hookEvent, sessionId, agentName, workspaceKey, projectKey);
                appendGuardDecision(
                    isBlockingPostDecision ? "block" : "warn",
                    postResult,
                    event,
                    hookEvent,
                    sessionId,
                    agentName,
                    workspaceKey,
                    projectKey,
                    postElapsedMs,
                );
                updateSessionState(sessionId, agentName, event);
                captureCodeEdit(sessionId, agentName, event);
                process.exit(0);
            }

            // Success: log allow decision with structured check results
            appendGuardDecision("allow", postResult, event, hookEvent, sessionId, agentName, workspaceKey, projectKey, postElapsedMs);

            const toolLabel = event.tool_name || "unknown";
            const summary = postResult.summary || ("all clean (" + postElapsedMs + "ms)");
            const cleanFile = lastCheckFile(event, rawInput);
            writeLastCheck({ result: "clean", tool: toolLabel, file: cleanFile, ms: postElapsedMs });
            console.log(JSON.stringify(formatProviderResponse("post_success", {
                summary: "[interlinked:" + toolLabel + "] " + summary,
            })));
            appendLocal(event, hookEvent, sessionId, agentName, workspaceKey, projectKey);
            updateSessionState(sessionId, agentName, event);
            captureCodeEdit(sessionId, agentName, event);
            process.exit(0);
        } else {
            // Harness unavailable — record the diagnostic locally for
            // \`interlinked doctor\` but don't surface "no harness" to the
            // model on every event. The user's harness status / statusline
            // is the right surface for "harness is down".
            const toolLabel = event.tool_name || "unknown";
            const elapsed = Date.now() - postStartMs;
            const naFile = lastCheckFile(event, rawInput);
            writeLastCheck({ result: "no_harness", tool: toolLabel, file: naFile, ms: elapsed });
            console.log(JSON.stringify(formatProviderResponse("post_success", {})));
        }
    }

    // --- Always write locally (works offline) ---
    appendLocal(event, hookEvent, sessionId, agentName, workspaceKey, projectKey);
    updateSessionState(sessionId, agentName, event);

    // Capture code edits from PostToolUse Edit/Write events
    if (isPostTool) {
        captureCodeEdit(sessionId, agentName, event);
    }

    // Reconcile commits on session end or stop
    if (event.event_type === "session_end" || event.event_type === "agent_stop") {
        reconcileCommits(sessionId);
    }

    // --- Fire-and-forget POST to server ---
    // Skipped when sync_mode is "local"
    if (syncMode !== "local" && serverUrl) {
        const realtimePayload = {
            workspace_uuid: workspaceId,
            workspace_key: workspaceKey,
            project_key: projectKey,
            agent_name: agentName,
            event_type: event.event_type,
            tool_name: event.tool_name,
            tool_input_summary: event.tool_input_summary,
            hook_event: event.hook_event,
            duration_ms: event.duration_ms || undefined,
            tokens_input: event.tokens?.input || undefined,
            tokens_output: event.tokens?.output || undefined,
            tokens_cache_read: event.tokens?.cache_read || undefined,
            tokens_cache_creation: event.tokens?.cache_creation || undefined,
            parent_agent: event.parent_agent || undefined,
            subagent_id: event.subagent_id || undefined,
            files_modified: event.files_modified || undefined,
            error_message: event.error ? String(event.error) : undefined,
            // v4 full-capture fields
            tool_input_json: event.tool_input !== undefined ? (typeof event.tool_input === "string" ? event.tool_input : JSON.stringify(event.tool_input)) : undefined,
            tool_response_json: event.tool_response !== undefined ? (typeof event.tool_response === "string" ? event.tool_response : JSON.stringify(event.tool_response)) : undefined,
            prompt: event.prompt || undefined,
            last_assistant_message: event.last_assistant_message || undefined,
            cwd: event.cwd || undefined,
            model: event.model || undefined,
            source: event.source || undefined,
            agent_type_hook: event.agent_type || undefined,
            tool_use_id: event.tool_use_id || undefined,
            session_id: sessionId || undefined,
            is_interrupt: event.is_interrupt || undefined,
            error_detail: event.error ? String(event.error) : undefined,
            notification_type: event.notification_type || undefined,
            notification_title: event.notification_title || undefined,
            task_subject: event.task_subject || undefined,
            task_id_hook: event.task_id || undefined,
            task_description_hook: event.task_description || undefined,
            trigger: event.trigger || undefined,
            reason: event.reason || undefined,
            permission_mode: event.permission_mode || undefined,
            transcript_path: event.transcript_path || undefined,
            teammate_name: event.teammate_name || undefined,
            team_name: event.team_name || undefined,
            custom_instructions: event.custom_instructions || undefined,
            stop_hook_active: event.stop_hook_active || undefined,
            permission_suggestions: event.permission_suggestions ? (typeof event.permission_suggestions === "string" ? event.permission_suggestions : JSON.stringify(event.permission_suggestions)) : undefined,
            agent_transcript_path: event.agent_transcript_path || undefined,
            thinking: event.thinking || undefined,
        };

        // Scrub secrets before sending to server
        scrubPayload(realtimePayload);

        try {
            const controller = new AbortController();
            const timeout = setTimeout(() => controller.abort(), 3000);

            const res = await fetch(serverUrl + "/api/hooks/activity", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    ...(authHeader ? { Authorization: authHeader } : {}),
                },
                signal: controller.signal,
                body: JSON.stringify(realtimePayload),
            });

            clearTimeout(timeout);
            if (!res.ok) {
                const transient = res.status === 429 || res.status >= 500;
                appendSyncError("realtime_post_http", "status " + res.status);
                if (transient) {
                    enqueueRealtimeRetry(realtimePayload);
                }
            }
        } catch (e) {
            appendSyncError(
                "realtime_post_network",
                e instanceof Error ? e.message : String(e),
            );
            enqueueRealtimeRetry(realtimePayload);
        }
    }

    // --- Batch sync on session end (realtime mode only) ---
    // Batch sync is cursor-based (only sends un-synced events), so this is a no-op
    // when all events were already sent via the realtime POST above.
    const isSessionEnd = event.event_type === "session_end" || event.event_type === "agent_stop";
    if (syncMode === "realtime" && isSessionEnd && serverUrl) {
        await batchSync(
            serverUrl,
            authHeader,
            workspaceId,
            workspaceKey,
            projectKey,
            agentName,
        );
    }
}

function safeReadConfig(path) {
    try {
        return JSON.parse(readFileSync(path, "utf-8"));
    } catch {
        return null;
    }
}

function sanitizeAgentName(value) {
    if (typeof value !== "string") return null;
    const trimmed = value.trim();
    if (!trimmed) return null;
    if (trimmed.toLowerCase() === "unknown") return null;
    return trimmed.slice(0, 80);
}

function readSessionAgent(sessionId) {
    if (!sessionId) return null;
    try {
        const sessionPath = safeSessionFilePath(sessionId, ".json");
        if (!sessionPath) return null;
        if (!existsSync(sessionPath)) return null;
        const session = JSON.parse(readFileSync(sessionPath, "utf-8"));
        return sanitizeAgentName(session?.agent);
    } catch {
        return null;
    }
}

function extractAgentName(rawInput, event) {
    const candidates = [
        rawInput?.agent_name,
        rawInput?.agentName,
        rawInput?.parent_agent_name,
        rawInput?.parentAgentName,
        rawInput?.sender_name,
        rawInput?.senderName,
        rawInput?.agent?.name,
        event?.parent_agent,
    ];
    for (const candidate of candidates) {
        const normalized = sanitizeAgentName(candidate);
        if (normalized) return normalized;
    }
    return null;
}

function buildSessionAgent(clientName, sessionId) {
    const sid = typeof sessionId === "string" && sessionId.length > 0
        ? sessionId.replace(/[^a-zA-Z0-9]/g, "").slice(0, 8)
        : "global";
    const normalizedClient = sanitizeAgentName(clientName || "") || "agent";
    return ("session-" + normalizedClient.toLowerCase() + "-" + sid).slice(0, 80);
}

function resolveAgentName(config, rawInput, event, clientName, sessionId) {
    const configured = sanitizeAgentName(config?.agent_name);
    if (configured) return configured;

    const discovered = extractAgentName(rawInput, event);
    if (discovered) return discovered;

    const existingSessionAgent = readSessionAgent(sessionId);
    if (existingSessionAgent) return existingSessionAgent;

    return buildSessionAgent(clientName, sessionId);
}

${EVENT_NORMALIZERS_CHUNK}

function extractFilePath(toolName, toolInput) {
    if (!toolName || !toolInput) return null;
    const fileTools = ["Read", "Write", "Edit", "Update", "ReadFile", "WriteFile", "EditFile",
        "read_file", "write_file", "edit_file", "CreateFile", "create_file", "apply_patch",
        "view", "str_replace", "create"];
    if (toolName === "apply_patch") {
        const rawPatch = String(toolInput.command || toolInput.patch || toolInput.content || toolInput._raw_patch || "");
        const moveMatch = rawPatch.match(/^\\*\\*\\* Move to:\\s+(.+)$/m);
        if (moveMatch && moveMatch[1]) return moveMatch[1].trim();
        const fileMatch = rawPatch.match(/^\\*\\*\\* (?:Update|Add|Delete) File:\\s+(.+)$/m);
        return fileMatch && fileMatch[1] ? fileMatch[1].trim() : null;
    }
    if (!fileTools.includes(toolName)) return null;
    const path = toolInput.file_path || toolInput.filePath || toolInput.path || null;
    return typeof path === "string" ? path : null;
}

function truncate(str, maxLen) {
    if (!str) return "";
    return str.length > maxLen ? str.slice(0, maxLen) : str;
}

function summarize(toolName, input) {
    if (!toolName || !input) return toolName || "";
    switch (toolName) {
        case "Read": case "Write": case "Edit": case "Update":
        case "ReadFile": case "WriteFile": case "EditFile":
        case "read_file": case "write_file": case "edit_file":
            return truncate(String(input.file_path || input.filePath || input.path || ""), 200);
        case "Bash": case "Shell": case "shell": case "run_command":
            return truncate(String(input.command || input.cmd || ""), 200);
        case "apply_patch": {
            const patchPath = extractFilePath(toolName, input);
            return truncate(String(patchPath || toolName), 200);
        }
        case "Glob": case "glob": case "ListFiles": case "list_files":
            return truncate(String(input.pattern || input.glob || ""), 200);
        case "Grep": case "grep": case "SearchFiles": case "search_files":
            return truncate((String(input.pattern || input.query || "") + " " + String(input.path || "")).trim(), 200);
        case "WebSearch": case "web_search":
            return truncate(String(input.query || ""), 200);
        case "WebFetch": case "web_fetch":
            return truncate(String(input.url || ""), 200);
        default:
            return toolName;
    }
}

main().catch(() => process.exit(0));
`;
}
