// Auto-extracted from hooks.ts by the sweep refactor. @codegen-data: template DATA, exempt from the per-file line cap (see large-file-policy.ts).
// The big template literal emitting `.interlinked/hooks/interlinked-activity.mjs`
// was split out of hooks.ts to keep that file focused on install/uninstall logic.
//
// This file holds the DATA — the .mjs runtime script that gets written into
// user projects by `interlinked enable`. The generated .mjs must remain
// self-contained (no imports from the CLI package) because it is deployed
// standalone and must work even if the CLI is uninstalled.
//
// Do not edit the pattern strings (like `rm -rf`, `catch (_err) { void 0; /* intentional: no-op */ }`) inside this
// template — they are data used at runtime, not code.

//
// The template is assembled from sibling chunk modules under `./hook-template-chunks/`.
// Each chunk is a contiguous slice of the generated .mjs and exports a string constant.
// `buildHookScript` stitches them back together; the byte output is identical to the
// pre-split template. See `hooks-template.test.ts` for the byte-level invariants.

import { type HarnessModePreset, QUALITY_MODE } from "../harness/rules/modes.js";
import {
	DEFAULT_DAEMON_HEAP_MB,
	DEFAULT_RSS_CEILING_BYTES,
} from "../harness/memory-ceiling.js";
import { READ_ONLY_TOOL_NAMES } from "./hook-read-only-tools.js";
import { COLLECTION_WRITER_CHUNK } from "./hook-template-chunks/collection-writer.js";
import { EVENT_NORMALIZERS_CHUNK } from "./hook-template-chunks/event-normalizers.js";
import { GUARDS_INLINE_CHUNK } from "./hook-template-chunks/guards-inline.js";
import {
	NATIVE_GATE_DENY_RESPONSE_CHUNK,
	PROVIDER_RESPONSES_CHUNK,
} from "./hook-template-chunks/provider-responses.js";
import { REDACTION_CHUNK } from "./hook-template-chunks/redaction.js";
import { SESSION_STATE_CHUNK } from "./hook-template-chunks/session-state.js";

/**
 * Build the Interlinked activity hook script (`.mjs`) for the given version.
 * The version is embedded in the first comment for staleness detection. The
 * optional `modePreset` argument bakes the per-tier `HARNESS_POST_TIMEOUT_MS`
 * literal into the generated runtime — re-render the script (via
 * `writeHookScript`) every time the mode changes. Defaults to QUALITY_MODE
 * (50 s) so existing call-sites that pass only the version keep working.
 */
export function buildHookScript(version: string, modePreset?: HarnessModePreset): string {
	const preset = modePreset ?? QUALITY_MODE;
	return [
		HOOK_SCRIPT_PREFIX,
		version,
		HOOK_SCRIPT_BEFORE_POST_TIMEOUT,
		String(preset.post_timeout_ms),
		HOOK_SCRIPT_BEFORE_MODE_NAME,
		preset.name,
		HOOK_SCRIPT_AFTER_MODE_NAME,
	].join("");
}

// Keep the generated runtime outside buildHookScript's implementation span.
// These constants are immutable template data; the tiny renderer above owns
// the only three values that vary per installation. Splitting at the dynamic
// boundaries avoids placeholder replacement semantics and preserves arbitrary
// version strings byte-for-byte.
const HOOK_SCRIPT_PREFIX = `#!/usr/bin/env node
// interlinked-hook-version: `;

const HOOK_SCRIPT_BEFORE_POST_TIMEOUT = `
// ===========================================
// Interlinked CLI Activity Hook (auto-generated)
// ===========================================
// Bridges lifecycle and tool-use events from AI coding agents into Interlinked CLI local logs
// and the server.
// Supports: Claude Code, OpenAI Codex CLI, GitHub Copilot CLI, Gemini CLI, Cursor, OpenCode, Pi
// Generated by: interlinked enable
// Do not edit manually — re-run 'interlinked enable' to regenerate.

import { readFileSync, existsSync, appendFileSync, writeFileSync, mkdirSync, rmdirSync, openSync, readSync, closeSync, statSync, unlinkSync, renameSync, readdirSync } from "node:fs";
import { join, dirname, basename } from "node:path";
import { createConnection } from "node:net";
import { execSync, execFileSync, spawn as nodeSpawn } from "node:child_process";
import { createHash, randomUUID } from "node:crypto";

const CWD = process.cwd();

// --- Resolve data directory (mirrors config.ts getDataDir logic) ---
function resolveDataDir() {
    if (process.env.INTERLINKED_DATA_DIR) return process.env.INTERLINKED_DATA_DIR;
    const configDir = process.env.INTERLINKED_HOME || join(CWD, ".interlinked");
    const localConfigPath = join(configDir, "config.local.json");
    if (existsSync(localConfigPath)) {
        try {
            const lc = JSON.parse(readFileSync(localConfigPath, "utf-8"));
            if (lc.data_dir) return lc.data_dir;
        } catch (_err) { void 0; /* intentional: no-op */ }
    }
    return configDir;
}

function resolveConfigDir() {
    return process.env.INTERLINKED_HOME || join(CWD, ".interlinked");
}

const CONFIG_DIR = resolveConfigDir();
const DATA_DIR = resolveDataDir();

// Walk up from CWD looking for the nearest .interlinked/harness.sock.
// Lets a harness daemon rooted at a monorepo ancestor serve subdir edits
// without each subdir needing its own daemon. Falls back to the local
// CONFIG_DIR/harness.sock if no ancestor socket exists (so first-run
// scenarios — before any daemon is started — still see the local path).
function resolveHarnessSocket() {
    let dir = CWD;
    for (let i = 0; i < 10; i++) {
        const candidate = join(dir, ".interlinked", "harness.sock");
        if (existsSync(candidate)) return candidate;
        // A linked worktree/submodule owns a distinct Git worktree and must
        // never borrow an ancestor checkout's daemon. Ordinary monorepo
        // subdirectories have no .git boundary, so they still walk upward.
        if (existsSync(join(dir, ".git"))) break;
        const parent = dirname(dir);
        if (parent === dir) break;
        dir = parent;
    }
    return join(CONFIG_DIR, "harness.sock");
}
const CONFIG_LOCAL_PATH = join(CONFIG_DIR, "config.local.json");
const CONFIG_SHARED_PATH = join(CONFIG_DIR, "config.json");
const ACTIVITY_PATH = join(DATA_DIR, "activity.jsonl");
const SESSIONS_DIR = join(DATA_DIR, "sessions");
const SYNC_STATE_PATH = join(DATA_DIR, "sync-state.json");
const REALTIME_RETRY_PATH = join(DATA_DIR, "realtime-retry.jsonl");
const SYNC_ERRORS_PATH = join(DATA_DIR, "sync-errors.jsonl");
const HOOK_RUNTIME_RECEIPT_PATH = join(DATA_DIR, "hook-runtime.json");

const PROVIDER_HOOK_DEFINITION_PATHS = {
    claude: ".claude/settings.json",
    codex: ".codex/hooks.json",
    copilot: ".github/hooks/hooks.json",
    gemini: ".gemini/settings.json",
    cursor: ".cursor/hooks.json",
    opencode: ".opencode/plugins/interlinked.ts",
    pi: ".pi/extensions/interlinked.js",
};

function findProviderHookDefinition(provider) {
    const relative = PROVIDER_HOOK_DEFINITION_PATHS[provider];
    if (!relative) return null;
    let dir = CWD;
    for (let i = 0; i < 20; i++) {
        const candidate = join(dir, relative);
        if (existsSync(candidate)) return candidate;
        const parent = dirname(dir);
        if (parent === dir) break;
        dir = parent;
    }
    return null;
}

function runtimeReceiptPath(provider, definitionPath) {
    const relative = PROVIDER_HOOK_DEFINITION_PATHS[provider];
    if (!definitionPath || !relative) return HOOK_RUNTIME_RECEIPT_PATH;
    let projectRoot = definitionPath;
    for (const _segment of relative.split("/")) projectRoot = dirname(projectRoot);
    return join(projectRoot, ".interlinked", "hook-runtime.json");
}

// Runtime receipt: proof that the provider accepted the current hook
// definition and executed it. Stores no session, prompt, or tool payload.
function writeHookRuntimeReceipt(provider, nativeEvent) {
    if (!/^[a-z0-9][a-z0-9-]{0,63}$/.test(provider)) return;
    try {
        const definitionPath = findProviderHookDefinition(provider);
        const receiptPath = runtimeReceiptPath(provider, definitionPath);
        mkdirSync(dirname(receiptPath), { recursive: true });
        let receipt = { schema_version: "1", providers: {} };
        if (existsSync(receiptPath)) {
            const prior = JSON.parse(readFileSync(receiptPath, "utf-8"));
            if (prior && prior.schema_version === "1" && prior.providers && typeof prior.providers === "object") {
                receipt = prior;
            }
        }
        const observation = {
            observed_at: new Date().toISOString(),
            native_event: nativeEvent || "unknown",
        };
        if (definitionPath) {
            observation.definition_sha256 = createHash("sha256")
                .update(readFileSync(definitionPath))
                .digest("hex");
        }
        receipt.providers[provider] = observation;
        const tempPath = receiptPath + "." + process.pid + ".tmp";
        writeFileSync(tempPath, JSON.stringify(receipt, null, 2) + "\\n", { mode: 0o600 });
        renameSync(tempPath, receiptPath);
    } catch (_err) { void 0; /* intentional: diagnostics never break a hook */ }
}

// Track active subagent for attribution
let activeSubagent = null;


${REDACTION_CHUNK}

// ===========================================
// Harness Connection — Guard evaluation via Unix socket
// ===========================================
// Connects to the Interlinked Harness server for PreToolUse guard evaluation.
// Falls back to inline pattern matching if harness is not running.

const HARNESS_SOCK_PATH = resolveHarnessSocket();
const QUALITY_WARNING_SPOOL_DIR = join(DATA_DIR, "quality-warning-spool");
const LEGACY_PENDING_WARNINGS_PATH = join(DATA_DIR, "pending-quality-warnings.json");
const QUALITY_WARNING_DRAIN_LOCK_PATH = join(QUALITY_WARNING_SPOOL_DIR, ".drain.lock");
const QUALITY_WARNING_TTL_MS = 24 * 60 * 60 * 1000;
const QUALITY_WARNING_READY_GRACE_MS = 250;
const QUALITY_WARNING_DRAIN_LOCK_TTL_MS = 75 * 1000;
const HARNESS_PRE_TIMEOUT_MS = 5000;  // PreToolUse: allows grep acceleration (ripgrep on candidates)

// Park the thread for ~ms WITHOUT burning a CPU core. Atomics.wait blocks the
// thread efficiently; the busy-spin fallback only runs if SharedArrayBuffer is
// unavailable. Replaces the old Date.now() busy-spins that pinned a full core
// while the hook waited on the harness.
function blockingSleep(ms) {
    try {
        Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms);
    } catch (_e) {
        const until = Date.now() + ms;
        while (Date.now() < until) { /* spin fallback */ }
    }
}
const HARNESS_POST_TIMEOUT_MS = `;

const HOOK_SCRIPT_BEFORE_MODE_NAME = `; // PostToolUse: from harness mode "`;

const HOOK_SCRIPT_AFTER_MODE_NAME = `" — see src/harness/rules/modes.ts. Re-rendered on every \`interlinked harness mode <name>\` change.

/**
 * Drain request-owned late quality warnings from a previous PostToolUse.
 * Modern PostToolUse calls acknowledge their own record before speaking, so
 * only a timed-out/disconnected call remains for a later PreToolUse. Ready
 * records are claimed with atomic rename: concurrent agents cannot replay one
 * another's warning, and no reader ever unlinks a live request's marker.
 *
 * NON-FREEZING: active work is never waited on. A live originating hook (or a
 * very young pid-less compatibility record) retains first-delivery ownership;
 * the record is left for the next PreToolUse instead of duplicating output.
 */
function validQualityDeliveryToken(value) {
    return typeof value === "string" && /^[a-zA-Z0-9_-]{16,128}$/.test(value);
}

function parseQualitySpoolRecord(raw) {
    try {
        const value = JSON.parse(raw);
        if (!value || value.version !== 1 || !validQualityDeliveryToken(value.token)) return null;
        if (typeof value.session_id !== "string" || typeof value.produced_at !== "string") return null;
		if (!Array.isArray(value.warnings) || value.warnings.length === 0 || !value.warnings.every((w) => typeof w === "string")) return null;
        return value;
    } catch (_err) { void 0; return null; }
}

function parseQualityActiveRecord(raw) {
    try {
        const value = JSON.parse(raw);
        if (!value || value.version !== 1 || !validQualityDeliveryToken(value.token)) return null;
        if (typeof value.session_id !== "string") return null;
        return value;
    } catch (_err) { void 0; return null; }
}

function claimQualityWarningFile(path) {
    const claimed = path + ".claim-" + process.pid + "-" + randomUUID();
    try { renameSync(path, claimed); return claimed; }
    catch (_err) { void 0; return null; }
}

function acquireQualityWarningDrainLease() {
    try { mkdirSync(QUALITY_WARNING_SPOOL_DIR, { recursive: true }); }
    catch (_err) { void 0; return null; }
    for (let attempt = 0; attempt < 2; attempt++) {
        const ownerToken = process.pid + "-" + randomUUID();
        try {
            writeFileSync(
                QUALITY_WARNING_DRAIN_LOCK_PATH,
                JSON.stringify({ pid: process.pid, at: Date.now(), owner_token: ownerToken }),
                { encoding: "utf-8", flag: "wx", mode: 0o600 },
            );
            return ownerToken;
        } catch (_err) { void 0; }

        let stale = false;
        try {
            const holder = JSON.parse(readFileSync(QUALITY_WARNING_DRAIN_LOCK_PATH, "utf-8"));
            stale = !holder || typeof holder.pid !== "number" || typeof holder.at !== "number"
                ? (Date.now() - statSync(QUALITY_WARNING_DRAIN_LOCK_PATH).mtimeMs) > QUALITY_WARNING_DRAIN_LOCK_TTL_MS
                : !processIsAlive(holder.pid) && (Date.now() - holder.at) > 1000;
        } catch (_err) { void 0; }
        if (!stale) return null;

        // Rename, never unlink by path: only one contender can claim the stale
        // inode, and no contender can delete a replacement live lease.
        const staleClaim = QUALITY_WARNING_DRAIN_LOCK_PATH + ".stale-" + randomUUID();
        try {
            renameSync(QUALITY_WARNING_DRAIN_LOCK_PATH, staleClaim);
            try { unlinkSync(staleClaim); } catch (_err) { void 0; /* best-effort */ }
        } catch (_err) { void 0; return null; }
    }
    return null;
}

function releaseQualityWarningDrainLease(ownerToken) {
    try {
        const holder = JSON.parse(readFileSync(QUALITY_WARNING_DRAIN_LOCK_PATH, "utf-8"));
        if (!holder || holder.owner_token !== ownerToken || holder.pid !== process.pid) return;
        const claimed = QUALITY_WARNING_DRAIN_LOCK_PATH + ".release-" + ownerToken;
        renameSync(QUALITY_WARNING_DRAIN_LOCK_PATH, claimed);
        try { unlinkSync(claimed); } catch (_err) { void 0; /* best-effort */ }
    } catch (_err) { void 0; /* another owner or an already-released lease */ }
}

function qualitySpoolFiles(suffix) {
    try {
        if (!existsSync(QUALITY_WARNING_SPOOL_DIR)) return [];
        return readdirSync(QUALITY_WARNING_SPOOL_DIR)
            .filter((name) => name.endsWith(suffix))
            .map((name) => join(QUALITY_WARNING_SPOOL_DIR, name));
    } catch (_err) { void 0; return []; }
}

function acknowledgePostToolDelivery(token) {
    if (!validQualityDeliveryToken(token)) return;
	for (const suffix of ["ready", "active"]) {
		const path = join(QUALITY_WARNING_SPOOL_DIR, token + "." + suffix + ".json");
		const claimed = claimQualityWarningFile(path);
		if (!claimed) continue;
		try { unlinkSync(claimed); } catch (_err) { void 0; /* best-effort acknowledgement */ }
	}
}

function claimLegacyQualityWarnings() {
    const claimed = claimQualityWarningFile(LEGACY_PENDING_WARNINGS_PATH);
    if (!claimed) return [];
    try {
        const value = JSON.parse(readFileSync(claimed, "utf-8"));
        return Array.isArray(value) ? value.filter((w) => typeof w === "string") : [];
    } catch (_err) { void 0; return []; }
    finally { try { unlinkSync(claimed); } catch (_err) { void 0; /* best-effort migration cleanup */ } }
}

function drainPendingQualityWarnings(sessionId, emit = true) {
    const warnings = new Set();
    if (qualitySpoolFiles(".ready.json").length === 0 && !existsSync(LEGACY_PENDING_WARNINGS_PATH)) return [];
    const lease = acquireQualityWarningDrainLease();
    if (!lease) return [];
    try {
		const readyPaths = qualitySpoolFiles(".ready.json");
        const activeForSession = qualitySpoolFiles(".active.json").some((path) => {
            try {
				const record = parseQualityActiveRecord(readFileSync(path, "utf-8"));
				if (!record || record.session_id !== sessionId) return false;
				const startedMs = typeof record.started_at === "string"
					? Date.parse(record.started_at)
					: Number.NaN;
				if (Number.isFinite(startedMs) && (Date.now() - startedMs) > QUALITY_WARNING_TTL_MS) return false;
				if (Number.isSafeInteger(record.client_pid) && record.client_pid > 0) {
					return processIsAlive(record.client_pid);
				}
				return Number.isFinite(startedMs) && (Date.now() - startedMs) < QUALITY_WARNING_READY_GRACE_MS;
			} catch (_err) { void 0; return false; }
        });
        const nowMs = Date.now();
        const youngForSession = readyPaths.some((path) => {
            try {
                const record = parseQualitySpoolRecord(readFileSync(path, "utf-8"));
                if (!record || record.session_id !== sessionId) return false;
                const ageMs = nowMs - Date.parse(record.produced_at);
                return Number.isFinite(ageMs) && ageMs >= -QUALITY_WARNING_READY_GRACE_MS
                    && ageMs < QUALITY_WARNING_READY_GRACE_MS;
            } catch (_err) { void 0; return false; }
        });
        if (activeForSession || youngForSession) return [];

		for (const path of readyPaths) {
            let record = null;
            try { record = parseQualitySpoolRecord(readFileSync(path, "utf-8")); }
            catch (_err) { void 0; /* claimed below as malformed */ }
            const producedMs = record ? Date.parse(record.produced_at) : Number.NaN;
            const ageMs = Date.now() - producedMs;
            const stale = !Number.isFinite(producedMs) || ageMs > QUALITY_WARNING_TTL_MS
                || ageMs < -QUALITY_WARNING_READY_GRACE_MS;
            if (record && !stale && record.session_id !== sessionId) continue;
            if (record && !stale && ageMs < QUALITY_WARNING_READY_GRACE_MS) continue;
            const claimed = claimQualityWarningFile(path);
            if (!claimed) continue;
            try {
                const claimedRecord = parseQualitySpoolRecord(readFileSync(claimed, "utf-8"));
                if (claimedRecord && !stale && claimedRecord.session_id === sessionId) {
                    for (const warning of claimedRecord.warnings) warnings.add(warning);
                }
            } catch (_err) { void 0; /* corrupt records are discarded, never replayed */ }
            finally { try { unlinkSync(claimed); } catch (_err) { void 0; /* best-effort */ } }
			const readySuffix = ".ready.json";
			const readyName = basename(path);
			const pathToken = readyName.endsWith(readySuffix)
				? readyName.slice(0, -readySuffix.length)
				: null;
			const claimedToken = record?.token || (validQualityDeliveryToken(pathToken) ? pathToken : null);
			if (claimedToken) {
				const activeClaim = claimQualityWarningFile(join(QUALITY_WARNING_SPOOL_DIR, claimedToken + ".active.json"));
				if (activeClaim) {
					try { unlinkSync(activeClaim); } catch (_err) { void 0; /* best-effort */ }
				}
			}
        }

        // One-time rolling-upgrade migration. Atomic claim prevents two modern
        // hooks from replaying the old shared file; Set de-duplicates a warning
        // that was present in both legacy and request-owned storage.
		if (readyPaths.length === 0) {
			for (const warning of claimLegacyQualityWarnings()) warnings.add(warning);
		} else if (warnings.size > 0) {
			// Modern request-owned evidence is authoritative. Claim the unscoped
			// migration copy so it cannot replay, but never mix foreign text in.
			claimLegacyQualityWarnings();
		}
    } catch (_err) { void 0; /* diagnostics never block a tool call */ }
    finally { releaseQualityWarningDrainLease(lease); }

    if (emit && warnings.size > 0) {
        process.stderr.write("\\n[interlinked] Quality issues from previous edit:\\n");
        for (const warning of warnings) process.stderr.write(warning + "\\n");
        process.stderr.write("\\n");
    }
    return [...warnings];
}

/** Auto-heal after a failed daemon round-trip. A module-global cooldown cannot
 * coordinate hooks because every invocation is a new Node process; the shared
 * O_EXCL lease below is the cross-process single-flight. */
const HARNESS_START_LOCK_PATH = join(CONFIG_DIR, ".harness-start.lock");
// Canonical startup permits a 60s cold-boot window. This standalone hook exits
// after transferring the lease and therefore cannot heartbeat it; keep the
// same 75s jitter margin as startup-lock.ts so a slow live child is not
// duplicated by the next agent hook under memory pressure.
const HARNESS_START_LOCK_TTL_MS = 75000;
const HARNESS_START_LOCK_INITIALIZATION_GRACE_MS = 2000;

function processIsAlive(pid) {
    try { process.kill(pid, 0); return true; }
    catch (err) { return Boolean(err && err.code === "EPERM"); }
}

function readHarnessStartHolder() {
    try {
        const raw = JSON.parse(readFileSync(HARNESS_START_LOCK_PATH, "utf-8"));
        if (!raw || typeof raw.pid !== "number" || typeof raw.at !== "number") return null;
        return raw;
    } catch (_err) { void 0; return null; }
}

function writeHarnessStartLock(now) {
    let fd = null;
    try {
        fd = openSync(HARNESS_START_LOCK_PATH, "wx");
        writeFileSync(fd, JSON.stringify({ pid: process.pid, at: now }));
        return true;
    } catch (_err) {
        return false;
    } finally {
        if (fd !== null) try { closeSync(fd); } catch (_err) { void 0; }
    }
}

function harnessStartLockIsInitializing(now) {
    try {
        return now - statSync(HARNESS_START_LOCK_PATH).mtimeMs <= HARNESS_START_LOCK_INITIALIZATION_GRACE_MS;
    } catch (_err) { void 0; return false; }
}

let harnessStartLockTempSequence = 0;
function replaceHarnessStartHolder(expected, next) {
    const tempPath = HARNESS_START_LOCK_PATH + "." + process.pid + "." + (++harnessStartLockTempSequence) + ".tmp";
    try {
        writeFileSync(tempPath, JSON.stringify(next), { flag: "wx" });
        const current = readHarnessStartHolder();
        if (!current || current.pid !== expected.pid || current.at !== expected.at) return false;
        renameSync(tempPath, HARNESS_START_LOCK_PATH);
        return true;
    } catch (_err) {
        void 0;
        return false;
    } finally {
        try { unlinkSync(tempPath); } catch (_err) { void 0; }
    }
}

function releaseHarnessStartLock(expectedPid) {
    const holder = readHarnessStartHolder();
    if (!holder || holder.pid !== expectedPid) return;
    try { unlinkSync(HARNESS_START_LOCK_PATH); } catch (_err) { void 0; }
}

function acquireHarnessStartLock(now = Date.now()) {
    try { mkdirSync(CONFIG_DIR, { recursive: true }); } catch (_err) { void 0; }
    if (writeHarnessStartLock(now)) return true;
    const holder = readHarnessStartHolder();
    if (!holder && harnessStartLockIsInitializing(now)) return false;
    const fresh = holder && now - holder.at <= HARNESS_START_LOCK_TTL_MS && processIsAlive(holder.pid);
    if (fresh) return false;
    try { unlinkSync(HARNESS_START_LOCK_PATH); } catch (_err) { void 0; }
    return writeHarnessStartLock(now);
}

function exactDaemonCommand(harnessEvent) {
    if (harnessEvent.tool_name !== "Bash") return false;
    const command = harnessEvent.tool_input && harnessEvent.tool_input.command;
    if (typeof command !== "string" || /[;&|><\`$(){}\\n]/.test(command)) return false;
    const trimmed = command.trim();
    const cliPattern = "(?:interlinked|node (?:[A-Za-z0-9_./:-]{1,160}/)?dist/index[.]js)";
    const lifecycle = new RegExp("^" + cliPattern + " (?:harness (?:start|restart|status)(?: --[A-Za-z0-9_-]+){0,8}|doctor(?: --[A-Za-z0-9_-]+){0,8})$");
    const disable = new RegExp("^" + cliPattern + " disable(?: (?:--(?:team|uninstall|keep-config|force)|--(?:reason|until) [A-Za-z0-9_./:@-]{1,80})){0,6}$");
    if (lifecycle.test(trimmed) || disable.test(trimmed)) return true;
    return new RegExp("^" + cliPattern + " install-hooks (?:--refresh --preserve-mode|--preserve-mode --refresh)$").test(trimmed);
}

function tryHealHarness(harnessEvent = null) {
    if (harnessEvent && exactDaemonCommand(harnessEvent)) {
        return { status: "operator-command", attempted: false };
    }
    // A recorded operator stand-down is authoritative for every hook path,
    // including this standalone runtime's recovery path. Previously only the
    // inline guard consulted the marker, so the generated hook could respawn
    // the daemon immediately after \`interlinked disable\`.
    if (inlineGuardDisabled()) {
        return { status: "guard-disabled", attempted: false };
    }
    try {
        // This function runs only before a missing socket or after a failed
        // socket round-trip. A live pid plus a socket FILE is therefore not
        // proof of health: that is also the exact stale-socket zombie shape.
        // The shared startup lease prevents a recovery burst from spawning a
        // herd while the incumbent or its successor is coming up.
        return tryAutoStartHarness();
    } catch (_err) {
        return { status: "probe-failed", attempted: false };
    }
}

/**
 * Send an event to the harness server and get a decision.
 * Returns null if harness is not available (fallback to inline).
 * Timeout varies: PreToolUse/PermissionRequest gates are fast (500ms), while
 * PostToolUse allows time for quality checks (15s).
 */
function evaluateViaHarness(harnessEvent) {
    const isPreTool = harnessEvent.hook_event === "PreToolUse"
        || harnessEvent.hook_event === "BeforeTool"
        || harnessEvent.hook_event === "PermissionRequest";
    const timeoutMs = isPreTool ? HARNESS_PRE_TIMEOUT_MS : HARNESS_POST_TIMEOUT_MS;

    return new Promise((resolve) => {
        if (!existsSync(HARNESS_SOCK_PATH)) {
            resolve(null); // Harness not running
            return;
        }
        const timeout = setTimeout(() => {
            try { sock.destroy(); } catch (_err) { void 0; /* intentional: no-op */ }
            resolve(null); // Timeout — fall back to inline
        }, timeoutMs);

        const sock = createConnection(HARNESS_SOCK_PATH);
        let responseData = "";

        sock.on("connect", () => {
            sock.write(JSON.stringify(harnessEvent) + "\\n");
        });
        let resolved = false;
        sock.on("data", (chunk) => {
            responseData += chunk.toString();
            // Look for newline-delimited JSON
            const newlineIdx = responseData.indexOf("\\n");
            if (newlineIdx !== -1 && !resolved) {
                resolved = true;
                clearTimeout(timeout);
                sock.destroy();
                try {
                    resolve(JSON.parse(responseData.slice(0, newlineIdx)));
                } catch {
                    resolve(null);
                }
            }
        });
        sock.on("error", () => {
            if (resolved) return;
            resolved = true;
            clearTimeout(timeout);
            resolve(null);
        });
        sock.on("close", () => {
            if (resolved) return;
            resolved = true;
            clearTimeout(timeout);
            if (responseData.trim()) {
                try { resolve(JSON.parse(responseData.trim())); } catch { resolve(null); }
            } else {
                resolve(null);
            }
        });
    });
}

const INLINE_STRONG_TYPING_PATTERNS = [
    /:\\s*any\\s*[;,)>=[\\]|&\\n\\r]/,
    /<\\s*any\\s*[>,]/,
    /\\bas\\s+any\\b/,
    /\\)\\s*:\\s*any\\b/,
    /\\bas\\s+unknown\\b/,
];

function stripInlineStringLiterals(line) {
    let result = line.replace(/"(?:[^"\\\\]|\\\\.)*"/g, '""');
    result = result.replace(/'(?:[^'\\\\]|\\\\.)*'/g, "''");
    result = result.replace(/\`(?:[^\`\\\\]|\\\\.)*\`/g, "\`\`");
    return result;
}

function findInlineStrongTypingMatches(content) {
    const lines = content.split("\\n");
    const matches = [];
    for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        const trimmed = line.trim();
        if (trimmed.startsWith("//") || trimmed.startsWith("*") || trimmed.startsWith("/*")) continue;
        if (/^\\s*['"\`]/.test(line) && /['"\`]\\s*[;,]?\\s*$/.test(line)) continue;
        const stripped = stripInlineStringLiterals(line);
        for (const pattern of INLINE_STRONG_TYPING_PATTERNS) {
            if (pattern.test(stripped)) {
                matches.push({ line: i + 1, text: trimmed.slice(0, 120) });
                break;
            }
        }
    }
    return matches;
}

function inlinePostToolFallback(rawInput, event) {
    const toolName = event.tool_name || rawInput.tool_name || null;
    const toolInput = rawInput.tool_input || event.tool_input || null;
    const filePath = extractFilePath(toolName, toolInput);
    if (!filePath || !existsSync(filePath)) return null;
    if (!/\\.(?:tsx?|jsx?|mjs|cjs)$/.test(filePath)) return null;
    // Parity with the daemon's strong_typing exemption (see
    // quality-checks.ts:223–225): tests legitimately use casts to construct
    // partial fixtures of large interface types and to drive edge-case paths.
    // (Note: \\. in this template-literal source emits \\. in the .mjs script,
    // which the runtime parses as \\.\\. So the regex matches a literal dot.)
    if (/\\.(?:test|spec)\\.(?:tsx?|jsx?|mjs|cjs)$/.test(filePath)) {
        return { summary: "inline strong_typing clean" };
    }
    let content = "";
    try {
        content = readFileSync(filePath, "utf-8");
    } catch {
        return null;
    }
    const matches = findInlineStrongTypingMatches(content);
    if (matches.length === 0) {
        return { summary: "inline strong_typing clean" };
    }
    const first = matches[0];
    const plural = matches.length === 1 ? "" : "s";
    return {
        warnings: [
            "[interlinked:strong_typing] " + filePath + " contains " + matches.length
                + " explicit any/unknown escape hatch occurrence" + plural
                + ". First: L" + first.line + " " + first.text,
        ],
        summary: "inline strong_typing warning",
    };
}

${GUARDS_INLINE_CHUNK}

/** Resolve and launch the daemon without rebuilding. The caller reports the
 * returned disposition; this function never prints a claim before it knows
 * whether a launch was attempted. */
function isInterlinkedCliCheckout(cwd) {
    // Verify the current working directory is the interlinked-cli source
    // checkout, not just any project that happens to have a
    // dist/harness/server.js path. Read package.json and check the name.
    // Fail-closed on any error: a missing/malformed package.json should NOT
    // permit auto-spawning a project-local server.js as the daemon.
    try {
        const pkgPath = join(cwd, "package.json");
        if (!existsSync(pkgPath)) return false;
        const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"));
        return pkg && pkg.name === "interlinked-cli";
    } catch (_err) {
        void 0; /* intentional: fail-closed on read/parse error */
        return false;
    }
}

function tryAutoStartHarness(sessionId = null) {
    try {
        // Find harness server.js — prefer pre-compiled JS for fast startup.
        // CWD-relative dist is gated on the CWD being the interlinked-cli
        // source checkout (package.json name === "interlinked-cli").
        // Without the gate, any user repo that happens to have a
        // dist/harness/server.js artifact at that path would have its own
        // unrelated file spawned as the harness daemon — letting arbitrary
        // project-local code run and bypassing the installed CLI entirely.
        // The dev-loop convenience (a fresh \`npm run build\` is picked up
        // automatically) is preserved for the actual CLI checkout.
        const candidates = [];
        if (isInterlinkedCliCheckout(CWD)) {
            candidates.push(join(CWD, "dist", "harness", "server.js"));
        }
        candidates.push(
            join(CONFIG_DIR, "..", "cli", "dist", "harness", "server.js"),
            join(CONFIG_DIR, "..", "node_modules", "interlinked-cli", "dist", "harness", "server.js"),
            join(CONFIG_DIR, "..", "node_modules", ".bin", "interlinked-harness"),
        );

        // Also check global npm paths
        try {
            const globalDir = execSync("npm root -g", { encoding: "utf-8", timeout: 2000 }).trim();
            candidates.push(join(globalDir, "interlinked-cli", "dist", "harness", "server.js"));
        } catch (_err) { void 0; /* intentional: no-op */ }

        // Fall back to TypeScript source (slower — requires tsx or similar)
        candidates.push(
            join(CONFIG_DIR, "..", "cli", "src", "harness", "server.ts"),
            join(CONFIG_DIR, "..", "node_modules", "interlinked-cli", "src", "harness", "server.ts"),
        );

        let serverPath = null;
        for (const p of candidates) {
            if (existsSync(p)) { serverPath = p; break; }
        }

		if (!serverPath) {
			return { status: "server-artifact-missing", attempted: false };
		}

		if (!acquireHarnessStartLock()) {
			return { status: "startup-lock-held", attempted: false };
		}

        // Spawn detached harness daemon using node
        const nodePath = process.execPath;
        // Keep hook-driven recovery on the same bounded runtime contract as
        // the ordinary harness-start path and automatic handover. Recovery is
        // path most likely to run after a crash; silently restoring Node's
        // larger default heap here can turn self-healing into a system OOM.
        const rawHeapMb = process.env.INTERLINKED_HARNESS_HEAP_MB;
        const parsedHeapMb = rawHeapMb === undefined || rawHeapMb.trim() === "" ? NaN : Number(rawHeapMb);
        const requestedHeapMb = Number.isFinite(parsedHeapMb) && parsedHeapMb >= 1
            ? Math.floor(parsedHeapMb)
            : ${DEFAULT_DAEMON_HEAP_MB};
        const rawRssCeilingMb = process.env.INTERLINKED_HARNESS_RSS_CEILING_MB;
        const parsedRssCeilingMb = rawRssCeilingMb === undefined || rawRssCeilingMb.trim() === ""
            ? ${DEFAULT_RSS_CEILING_BYTES / (1024 * 1024)}
            : Number(rawRssCeilingMb);
        const rssCeilingMb = parsedRssCeilingMb === 0
            ? 0
            : Number.isFinite(parsedRssCeilingMb) && parsedRssCeilingMb > 0
                ? Math.max(${DEFAULT_RSS_CEILING_BYTES / (1024 * 1024)}, Math.min(Math.floor(parsedRssCeilingMb), 8192))
                : ${DEFAULT_RSS_CEILING_BYTES / (1024 * 1024)};
        const ceilingBoundMb = rssCeilingMb === 0 ? 4096 : Math.max(1, rssCeilingMb - 512);
        const heapMb = Math.min(requestedHeapMb, 4096, ceilingBoundMb);
        const args = ["--max-old-space-size=" + heapMb, "--expose-gc", serverPath, "--cwd", CWD, "--protocol", "dual"];
        if (sessionId) args.push("--session-id", String(sessionId));
		const child = nodeSpawn(nodePath, args, {
            detached: true,
            stdio: "ignore",
		});
		if (typeof child.pid !== "number") {
			try { child.kill("SIGTERM"); } catch (_err) { void 0; }
			releaseHarnessStartLock(process.pid);
			return { status: "spawn-failed", attempted: true };
		}
		// Transfer through an owner-checked atomic replacement. A failed transfer
		// must not leave an unleased daemon racing a later hook recovery.
		const holder = readHarnessStartHolder();
		if (!holder || holder.pid !== process.pid || !replaceHarnessStartHolder(holder, { pid: child.pid, at: Date.now() })) {
			try { child.kill("SIGTERM"); } catch (_err) { void 0; }
			releaseHarnessStartLock(process.pid);
			return { status: "spawn-failed", attempted: true };
		}
		child.unref();
		return { status: "launch-attempted", attempted: true };
	} catch (_err) {
		releaseHarnessStartLock(process.pid);
		return { status: "spawn-failed", attempted: true };
	}
}

function reportHarnessRecovery(result) {
	if (!result) return;
	if (result.status === "launch-attempted") {
		process.stderr.write("[interlinked:harness] daemon launch attempted; socket not yet verified — this call uses inline fallback\\n");
	} else if (result.status === "server-artifact-missing") {
		process.stderr.write("[interlinked:harness] daemon server artifact missing; no launch attempted — rebuild or reinstall Interlinked\\n");
	} else if (result.status === "spawn-failed") {
		process.stderr.write("[interlinked:harness] daemon launch attempted but spawn failed — this call uses inline fallback\\n");
	}
}

// --- Last-check file for status line visibility ---
// Structured pipe-delimited format so the bash statusline can render
// outcome language (\"caught 3 new issues before they landed\") without
// fragile string parsing. One line, key=value fields separated by ' | '.
//
// Schema (additive — bash falls back gracefully on missing keys):
//   result=clean|warn|block|no_harness
//   file=<repo-relative path or empty>
//   tool=<tool name>
//   count=<number, warn only>
//   ms=<elapsed milliseconds, optional>
//   rule=<rule id, block only>
//   summary=<short reason, block only>
const LAST_CHECK_PATH = join(DATA_DIR, "last-check.txt");
function writeLastCheck(fields) {
    try {
        const parts = [];
        for (const [k, v] of Object.entries(fields)) {
            if (v === undefined || v === null || v === "") continue;
            // Strip pipes/newlines from values so the delimiter is unambiguous.
            const safe = String(v).replace(/[|\\r\\n]+/g, " ").trim();
            parts.push(k + "=" + safe);
        }
        writeFileSync(LAST_CHECK_PATH, parts.join(" | ") + "\\n");
    } catch (_err) { void 0; /* intentional: no-op */ }
}

// Extract the edited file path from a hook event so the statusline can
// say "src/foo.ts" instead of just "Edit". Returns "" for tools without
// a file (Bash, Grep, etc.) — caller falls back to tool name.
function lastCheckFile(event, rawInput) {
    const ti = (event && event.tool_input) || (rawInput && rawInput.tool_input) || null;
    if (!ti || typeof ti !== "object") return "";
    const path = ti.file_path || ti.filePath || ti.path || ti.notebook_path || "";
    if (typeof path !== "string" || !path) return "";
    const cwd = (rawInput && rawInput.cwd) || (event && event.cwd) || process.cwd();
    if (path.startsWith(cwd + "/")) return path.slice(cwd.length + 1);
    return path;
}

${SESSION_STATE_CHUNK}

${COLLECTION_WRITER_CHUNK}

// Provider output is transactional. A response is staged in memory and
// written with one synchronous fd write only after the surrounding audit work
// completes. If main() rejects, the terminal handler discards the staged
// bytes before emitting its own native response, so a provider never sees a
// partial response followed by a second JSON object.
let pendingProviderStdout = null;
let providerStdoutCommitted = false;
let terminalHookProvider = "unknown";
let terminalHookEvent = null;

${NATIVE_GATE_DENY_RESPONSE_CHUNK}

function stageProviderStdout(response) {
    const serialized = JSON.stringify(response);
    if (pendingProviderStdout !== null && pendingProviderStdout !== serialized) {
        throw new Error("multiple provider responses were staged for one hook invocation");
    }
    pendingProviderStdout = serialized;
}

function commitProviderStdout() {
    if (providerStdoutCommitted || pendingProviderStdout === null) return;
    writeFileSync(1, pendingProviderStdout);
    providerStdoutCommitted = true;
    pendingProviderStdout = null;
}

function commitProviderResponseAndExit(code) {
    commitProviderStdout();
    process.exit(code);
}

function discardProviderStdout() {
    pendingProviderStdout = null;
}

function primeTerminalHookContext(rawInput) {
    const envProvider = process.env.INTERLINKED_CLIENT || "";
    terminalHookProvider = envProvider === "codex"
        ? "codex"
        : (envProvider === "" || envProvider === "claude" || envProvider === "claude-code")
            ? "claude"
            : envProvider;
    terminalHookEvent = rawInput && typeof rawInput.hook_event_name === "string"
        ? rawInput.hook_event_name
        : null;
}

function updateTerminalHookContext(provider, eventName) {
    if (provider) terminalHookProvider = provider;
    if (eventName) terminalHookEvent = eventName;
}

function terminalHookFailure() {
    discardProviderStdout();
    const reason = "[interlinked] hook runtime failed before returning a valid decision";
    const denyResponse = nativeGateDenyResponse(
        terminalHookProvider,
        terminalHookEvent,
        reason,
    );
    const action = denyResponse
        ? "the gate request was denied"
        : "this non-gating hook was skipped";
    try {
        writeFileSync(
            2,
            reason + " for " + terminalHookProvider + ":" + (terminalHookEvent || "unknown") +
                " — " + action + ". Run 'interlinked doctor' before retrying.\\n",
        );
    } catch (_err) { void 0; /* terminal stderr is best-effort */ }
    if (!denyResponse) process.exit(1);
    try {
        writeFileSync(1, JSON.stringify(denyResponse));
        process.exit(0);
    } catch (_err) {
        // Claude documents exit 2 as the emergency block path. Codex locally
        // honors the same non-zero gate failure if stdout itself is broken.
        process.exit(2);
    }
}

function readInitialHookInput() {
    let stdin = "";
    try { stdin = readFileSync(0, "utf-8"); }
    catch (_err) { void 0; return { ok: false, value: null }; }
    if (!stdin.trim()) return { ok: false, value: null };
    try { return { ok: true, value: JSON.parse(stdin) }; }
    catch (_err) { void 0; return { ok: false, value: null }; }
}

async function main(rawInput) {
    if (!rawInput || typeof rawInput !== "object" || Array.isArray(rawInput)) process.exit(0);
    const localConfig = existsSync(CONFIG_LOCAL_PATH)
        ? safeReadConfig(CONFIG_LOCAL_PATH)
        : null;
    const sharedConfig = existsSync(CONFIG_SHARED_PATH)
        ? safeReadConfig(CONFIG_SHARED_PATH)
        : null;
    if (!localConfig && !sharedConfig) process.exit(0);
    const config = {
        ...(sharedConfig || {}),
        ...(localConfig || {}),
    };

    // Resolve active server entry — pairs server_url with workspace_id
    const activeKey = config.active_server || "production";
    const activeServer = config.servers?.[activeKey];
    const serverUrl = activeServer?.server_url || config.server_url;
    const workspaceId = activeServer?.workspace_id || config.workspace_id;
    const workspaceKey = config.default_workspace_key || "main";
    const projectKey = config.default_project || "main";
    const syncMode = config.sync_mode || "realtime";

    // Resolve auth — prefer access_token, fall back to agent_handle
    const authHeader = config.access_token
        ? "Bearer " + config.access_token
        : config.agent_handle
          ? "Bearer " + config.agent_handle
          : null;

    // Retry any previously buffered realtime payloads first.
    if (syncMode !== "local" && serverUrl) {
        await flushRealtimeRetry(serverUrl, authHeader);
    }

    // --- Client Handler Registry ---
    // Each entry: { name, detect(input, source), normalize(input) }
    // First match wins. Claude is the catch-all for stdin — keep it last.
    // Codex's payload shape mirrors Claude's, so it must be detected via
    // the INTERLINKED_CLIENT environment variable (set by the hook command
    // installed into .codex/hooks.json) before falling through to Claude.
    // To add a new client (Cursor, Opencode, Amp, etc.):
    //   1. Add a normalizer function (normalizeXxxEvent)
    //   2. Add a detector entry below
    const RUNNER_ENV = process.env.INTERLINKED_CLIENT || "";
    const CLIENT_HANDLERS = [
        { name: "copilot", detect: (input, src) => src === "stdin" && !input.hook_event_name && typeof input.timestamp === "number", normalize: normalizeCopilotEvent },
        { name: "codex", detect: (_input, src) => src === "stdin" && RUNNER_ENV === "codex", normalize: normalizeCodexEvent },
        // Cursor: detect via INTERLINKED_CLIENT env var (set by the hook
        // command we install into .cursor/hooks.json) OR via Cursor-specific
        // payload fields (cursor_version, conversation_id+generation_id) so
        // we still recognise the client if the env var got dropped by the
        // shell. Must come BEFORE the Claude catch-all because Cursor sends
        // hook_event_name like Claude does for some events.
        { name: "cursor", detect: (input, src) => src === "stdin" && (RUNNER_ENV === "cursor" || !!input.cursor_version || (!!input.conversation_id && !!input.generation_id)), normalize: normalizeCursorEvent },
        // Gemini: detect via INTERLINKED_CLIENT env var (set by the hook
        // command we install into .gemini/settings.json) OR via Gemini-specific
        // payload fields (gemini_session_id) OR via the PascalCase
        // Before/After-(Tool/Model/Agent) hook event names. Must come BEFORE
        // the Claude catch-all — Gemini's PascalCase event names overlap
        // with Claude's so the catch-all would otherwise normalize them
        // through the wrong dispatcher and leave normalizeGeminiEvent dead.
        { name: "gemini", detect: (input, src) => src === "stdin" && (RUNNER_ENV === "gemini" || !!input.gemini_session_id || (typeof input.hook_event_name === "string" && /^(Before|After)(Tool|Model|Agent)$/.test(input.hook_event_name))), normalize: normalizeGeminiEvent },
        // Provider bridges send Claude-compatible aliases in hook_event_name
        // while preserving their native fields. Reusing the mature Claude
        // normalizer keeps the standalone .mjs fallback at guard parity; the
        // handler identity keeps attribution provider-correct.
        { name: "opencode", detect: (_input, src) => src === "stdin" && RUNNER_ENV === "opencode", normalize: normalizeClaudeEvent },
        { name: "opencode2", detect: (_input, src) => src === "stdin" && RUNNER_ENV === "opencode2", normalize: normalizeClaudeEvent },
        { name: "pi", detect: (_input, src) => src === "stdin" && RUNNER_ENV === "pi", normalize: normalizeClaudeEvent },
        { name: "claude", detect: (input, src) => src === "stdin", normalize: normalizeClaudeEvent },
    ];

    // Use the already-parsed stdin payload (Claude Code, GitHub Copilot CLI,
    // and future clients). Parsing happens at module scope so terminal recovery
    // knows the native event even if main() rejects before client detection.
    let hookEvent, sessionId;
    const inputSource = "stdin";

    hookEvent = rawInput.hook_event_name || null;
    sessionId = rawInput.session_id || rawInput.sessionId || null;
    // Capture the raw Cursor event name BEFORE normalization rewrites it to
    // a canonical PreToolUse/PostToolUse. Cursor's per-event response
    // capabilities (additional_context on postToolUse, ask on shell/MCP
    // gates) are encoded against the raw name in formatCursorResponse.
    const cursorNativeEvent = hookEvent;

    // Detect client and normalize event
    let event = null;
    let detectedClient = "unknown";
    for (const handler of CLIENT_HANDLERS) {
        if (handler.detect(rawInput, inputSource)) {
            event = handler.normalize(rawInput);
            detectedClient = handler.name;
            break;
        }
    }
    updateTerminalHookContext(detectedClient, hookEvent);

    if (!event) process.exit(0);

    // Always resolve hookEvent from the normalized event so it carries the
    // canonical name (PreToolUse / PostToolUse / UserPromptSubmit / ...).
    // The downstream isPreTool / isPostTool / isUserPrompt checks AND the
    // harness server (server.ts isPreToolUse / isPostToolUse) speak canonical
    // names only. Copilot doesn't send hook_event_name (the normalizer sets
    // event.hook_event from payload shape); Cursor sends camelCase native
    // names like "beforeShellExecution" that the normalizer maps to the
    // canonical "PreToolUse" — keeping the raw native name here would skip
    // guard evaluation entirely on Cursor (destructive shell/MCP calls would
    // be allowed without the guard ever running).
    if (event.hook_event) {
        hookEvent = event.hook_event;
    }
    updateTerminalHookContext(detectedClient, hookEvent);
    writeHookRuntimeReceipt(detectedClient, hookEvent);

    // Attach common fields available on all Claude Code events
    if (rawInput.cwd) event.cwd = rawInput.cwd;
    if (rawInput.permission_mode) event.permission_mode = rawInput.permission_mode;
    if (rawInput.transcript_path) event.transcript_path = rawInput.transcript_path;
    // Parent session linkage — Claude Code's Agent/Task tool fires the
    // child session with parent_tool_use_id pointing back at the launching
    // tool call, and the parent's session_id is reachable via the SubagentStart
    // / SubagentStop payload's parent_agent_name/parent_session_id field.
    if (rawInput.parent_session_id) event.parent_session_id = rawInput.parent_session_id;
    if (rawInput.parent_tool_use_id) event.parent_tool_use_id = rawInput.parent_tool_use_id;
    // Turn id — single identifier shared by every event between two
    // user_prompt events. Minted on user_prompt, stamped on everything else.
    stampTurnId(sessionId, event);

    // Extract new thinking blocks from transcript (real-time capture)
    const transcriptPath = rawInput.transcript_path || null;
    const thinkingContent = extractNewThinking(transcriptPath);
    if (thinkingContent) event.thinking = thinkingContent;

	const agentName = resolveAgentName(config, rawInput, event, detectedClient, sessionId);

	// Claude's WorktreeCreate hook replaces its default Git implementation.
	// Interlinked intentionally fails this event so agents cannot create new
	// worktrees; cleanup/listing of existing worktrees remains available.
	if (hookEvent === "WorktreeCreate") {
		process.stderr.write(agentWorktreeCreationBlockReason() + "\\n");
		process.exit(2);
	}

	// ===========================================
    // SessionStart: enter the same cross-process recovery path as every other
    // event. SessionStart is an opportunity, not a prerequisite.
    // ===========================================
    if (hookEvent === "SessionStart" && !existsSync(HARNESS_SOCK_PATH)) {
        reportHarnessRecovery(tryHealHarness());
    }
    // Daily graph snapshot — fires once per 24h on any SessionStart so
    // graph-history.jsonl carries a longitudinal trend without needing
    // a daemon. Cheap mtime check first, full walk only when stale.
    if (hookEvent === "SessionStart") {
        try { maybeSnapshotGraph(rawInput.cwd || event.cwd || process.cwd()); }
        catch (_err) { void 0; /* intentional: snapshot best-effort */ }
    }
    // Costs ledger — emit token-usage rows for any new model calls when a
    // root or subagent turn ends. Codex SubagentStop points at the child's
    // rollout via agent_transcript_path while retaining the parent session id,
    // so the emitter also receives provider/actor identity for cursor isolation.
    if (hookEvent === "Stop" || hookEvent === "SessionEnd" || hookEvent === "SubagentStop"
        || event.event_type === "agent_stop" || event.event_type === "subagent_stop") {
        const isSubagentCostEvent = hookEvent === "SubagentStop" || event.event_type === "subagent_stop";
        const tp = isSubagentCostEvent
            ? (rawInput.agent_transcript_path || event.agent_transcript_path || rawInput.transcript_path || event.transcript_path || null)
            : (rawInput.transcript_path || event.transcript_path || null);
        try {
            emitCostsFromTranscript(sessionId, tp, {
                provider: detectedClient,
                subagent_id: isSubagentCostEvent ? (event.subagent_id || rawInput.agent_id || null) : null,
                model: event.model || rawInput.model || null,
            });
        }
        catch (_err) { void 0; /* intentional: cost ledger best-effort */ }
    }
    // Rule-stats rollup + suggestion-outcome reconciler — fire on
    // SessionEnd / Stop. Both gate on file mtime / cursor so rapid
    // repeated triggers don't redo the work.
    if (hookEvent === "Stop" || hookEvent === "SessionEnd") {
        try { maybeRollupRulesStats(); }
        catch (_err) { void 0; /* intentional: rollup best-effort */ }
        try { reconcileSuggestionOutcomes(rawInput.cwd || event.cwd || process.cwd()); }
        catch (_err) { void 0; /* intentional: reconciler best-effort */ }
    }

    // ===========================================
    // Guard Evaluation (PreToolUse / BeforeTool)
    // ===========================================
${PROVIDER_RESPONSES_CHUNK}

    // For pre-execution tool and permission events: evaluate via the harness
    // (or inline fallback).
    // If blocked, output decision to stdout and exit.
    // The local write and server POST still happen for audit trail.

    const isPreTool = hookEvent === "PreToolUse"
        || hookEvent === "BeforeTool"
        || hookEvent === "PermissionRequest";
    const isPostTool = hookEvent === "PostToolUse" || hookEvent === "AfterTool" || hookEvent === "PostToolUseFailure";
    const isUserPrompt = hookEvent === "UserPromptSubmit" || hookEvent === "BeforeAgent";
    let guardDecision = null;
	let coldRecoveryResult = null;
	if (!existsSync(HARNESS_SOCK_PATH) && hookEvent !== "SessionStart") {
		coldRecoveryResult = tryHealHarness({
			tool_name: event.tool_name || rawInput.tool_name || null,
			tool_input: rawInput.tool_input || event.tool_input || null,
		});
		reportHarnessRecovery(coldRecoveryResult);
	}

    // PostToolUse skip_paths is intentionally resolved by the daemon after it
    // observes the filesystem ChangeSet. A hook-side shortcut based on the
    // tool-declared path can miss additional effects from Bash, apply_patch,
    // formatters, or unfamiliar writer tools. PreToolUse likewise always runs
    // deterministic safety guards regardless of skip_paths.

    // ===========================================
    // UserPromptSubmit: forward to harness for PII scan
    // ===========================================
    // If the content scanner is enabled and finds PII in the prompt, the
    // harness returns a redacted copy which we substitute into event.prompt
    // before the local JSONL write below. Never blocks — users can always
    // submit their prompt; we only mask the stored record.
    if (isUserPrompt && event.prompt) {
        const promptHarnessEvent = {
            hook_event: hookEvent,
            session_id: sessionId,
            agent_source: detectedClient,
            agent_name: agentName,
            tool_name: null,
            tool_input: null,
            prompt: event.prompt,
            cwd: rawInput.cwd || event.cwd || null,
            model: event.model || null,
            timestamp: new Date().toISOString(),
        };
        try {
            const promptDecision = await evaluateViaHarness(promptHarnessEvent);
            if (promptDecision && typeof promptDecision.redacted_prompt === "string") {
                event.prompt = promptDecision.redacted_prompt;
                if (event.tool_input_summary) {
                    // Keep the 200-char summary in sync with the masked prompt.
                    event.tool_input_summary = promptDecision.redacted_prompt.slice(0, 200);
                }
            }
			if (!promptDecision && !coldRecoveryResult) {
				coldRecoveryResult = tryHealHarness(promptHarnessEvent);
				reportHarnessRecovery(coldRecoveryResult);
			}
        } catch (_err) { void 0; /* fail-open: raw prompt still gets inline secrets scrub via scrubPayload below */ }
    }

    // On PreToolUse, drain only this session's late PostToolUse records. Modern
    // synchronous responses acknowledge their own token and never replay here.
    // Copilot ignores stderr, so its records are consumed silently.
    if (isPreTool) {
        drainPendingQualityWarnings(String(sessionId || ""), detectedClient !== "copilot");
    }

    if (isPreTool) {
        const preStartMs = Date.now();
        const harnessEvent = {
            hook_event: hookEvent,
            session_id: sessionId,
            agent_source: detectedClient,
            agent_name: agentName,
            tool_name: event.tool_name || rawInput.tool_name || null,
            tool_input: rawInput.tool_input || event.tool_input || null,
            tool_use_id: rawInput.tool_use_id || event.tool_use_id || null,
            cwd: rawInput.cwd || event.cwd || null,
            model: event.model || null,
            timestamp: new Date().toISOString(),
        };

        guardDecision = await evaluateViaHarness(harnessEvent);

        if (!guardDecision) {
			// No preflight ran when a stale socket existed. Try recovery now, but
			// never wait on daemon boot: deterministic inline gates decide THIS
			// call and a later call verifies the socket.
			if (!coldRecoveryResult) {
				coldRecoveryResult = tryHealHarness(harnessEvent);
				reportHarnessRecovery(coldRecoveryResult);
			}
        }

        if (!guardDecision) {
            // Pass harnessEvent.tool_input (post-normalization), NOT rawInput.tool_input.
            // Clients like Cursor (beforeShellExecution: command at top level) and
            // Copilot (toolArgs as JSON string) don't carry the canonical
            // tool_input shape on rawInput; the normalizers project it onto
            // event.tool_input. Without this, the inline fallback silently
            // returned null on Cursor/Copilot and let destructive shell calls
            // through whenever the harness was unavailable.
            guardDecision = inlineGuardCheck(hookEvent, harnessEvent.tool_name, harnessEvent.tool_input);
        }

		if (!guardDecision && ["Write", "Edit", "MultiEdit", "apply_patch", "write_file", "replace", "replace_string", "create_file"].includes(harnessEvent.tool_name)) {
			process.stderr.write("[interlinked:function-tokens:not-measured] function-token enforcement requires the running harness daemon and an exact language adapter; this cold-fallback edit was not measured\\n");
		}

        const preElapsedMs = Date.now() - preStartMs;

        if (guardDecision?.warnings && guardDecision.warnings.length > 0) {
            for (const w of guardDecision.warnings) {
                process.stderr.write(w + "\\n");
            }
        }

        // If blocked at a pre-execution gate, output its phase-specific
        // provider decision to stdout and exit.
        if (guardDecision?.decision === "block") {
            appendLocal(event, hookEvent, sessionId, agentName, workspaceKey, projectKey);
            appendCollectionRecord(event, DATA_DIR);
            appendGuardDecision("block", guardDecision, event, hookEvent, sessionId, agentName, workspaceKey, projectKey, preElapsedMs);
            updateSessionState(sessionId, agentName, event);

            // Feed the statusline kinetic segment so a freshly-blocked action
            // shows up as "✗ blocked rm -rf · 2s ago · rule: block_rm_rf".
            const blockToolLabel = event.tool_name || rawInput.tool_name || "tool";
            const blockFile = lastCheckFile(event, rawInput);
            const blockSummary = (guardDecision.reason || "Blocked by Interlinked guard").split(/\\r?\\n/)[0].slice(0, 80);
            const blockRule = guardDecision.rule_id || guardDecision.rule || "";
            writeLastCheck({ result: "block", tool: blockToolLabel, file: blockFile, summary: blockSummary, rule: blockRule });

            if (guardDecision.grep_stats) {
                const stats = guardDecision.grep_stats;
                const selectivity = stats.selectivity_pct != null ? stats.selectivity_pct.toFixed(1) : "?";
                const header = "[interlinked:index] Searched " + stats.candidates + " candidate files (from " + stats.total_files + " total, " + selectivity + "% selectivity)";
                const body = guardDecision.reason || "No matches found.";
                writeProviderResponse("pre_block_grep", { reason: header + "\\n" + body });
            } else {
                writeProviderResponse("pre_block", { reason: guardDecision.reason || "Blocked by Interlinked guard" });
            }
            commitProviderResponseAndExit(0);
        }

        // "ask" → user confirmation required. Surface Claude Code's permission
        // prompt so the human approves per-call. Reason includes rule id and
        // instruction for context.
        if (guardDecision?.decision === "ask") {
            appendLocal(event, hookEvent, sessionId, agentName, workspaceKey, projectKey);
            appendCollectionRecord(event, DATA_DIR);
            appendGuardDecision("ask", guardDecision, event, hookEvent, sessionId, agentName, workspaceKey, projectKey, preElapsedMs);
            updateSessionState(sessionId, agentName, event);
            const askTool = event.tool_name || rawInput.tool_name || "unknown";
            const askRule = guardDecision.rule_id || guardDecision.rule || null;
            const askCoreReason = guardDecision.reason || "Interlinked pre-block rule matched — please confirm.";
            const askReason = askRule
                ? "[interlinked:" + askRule + "] tool=" + askTool + " — " + askCoreReason
                : "[interlinked] tool=" + askTool + " — " + askCoreReason;
            writeProviderResponse("pre_ask", {
                reason: askReason,
                // Ensure Claude's permission UI always has a human-facing explanation
                // even when a detector returns ask without an explicit system message.
                systemMessage: guardDecision.system_message || askReason,
            });
            commitProviderResponseAndExit(0);
        }

        // Log PreToolUse warnings as guard_warn events
        if (guardDecision?.decision === "allow" && guardDecision.warnings?.length > 0) {
            appendGuardDecision("warn", guardDecision, event, hookEvent, sessionId, agentName, workspaceKey, projectKey, preElapsedMs);
        }

		// PermissionRequest does not accept generic additionalContext output.
		// An Interlinked allow is an abstention, not an auto-approval: keep any
		// non-blocking explanation on stderr and emit zero stdout bytes.
		if (guardDecision?.decision === "allow" && hookEvent === "PermissionRequest") {
			writeProviderResponse("pre_allow", {
				systemMessage: guardDecision.system_message,
				additionalContext: guardDecision.additional_context,
			});
		}

        // Log allow decisions (no warnings) so guard history is complete
        if (guardDecision?.decision === "allow" && (!guardDecision.warnings || guardDecision.warnings.length === 0)) {
            appendGuardDecision("allow", guardDecision, event, hookEvent, sessionId, agentName, workspaceKey, projectKey, preElapsedMs);
        }
    }

    // ===========================================
    // PostToolUse: Delegate quality checks to harness
    // ===========================================
    // The harness runs tsc, lint, secrets, strong_typing, and inline checks.
    // If harness is unavailable, degrade gracefully (no inline fallback).
    //
    // Phase 1 failure-recovery: every PostToolUse / PostToolUseFailure with
    // tool_outcome === "error" must reach the harness, regardless of tool
    // class — Channels 1/2/3/6 (recurrence, triage, recovery, explanation)
    // are tool-agnostic and need to see Bash/Read/Grep failures too. Only
    // known read-only tools may fast-path. Unknown tools reach the daemon
    // by default: a new writer must not reopen the bypass merely by using an
    // unfamiliar name. Shell effects are likewise judged from the observed
    // ChangeSet, not the command parser.
    // The list is interpolated from ../lib/hook-read-only-tools.ts so this
    // runtime and the daemon's path resolver share ONE definition of "cannot
    // write a file" instead of two drifting opinions. Bash is deliberately
    // absent — only a post-call filesystem comparison establishes its effects.
    const knownReadOnlyPostTools = new Set(${JSON.stringify(READ_ONLY_TOOL_NAMES)});
    // skipPostCheck: legacy gate kept disarmed so Phase 1 channels see every
    // failure. Any future "skip on this combo" logic threads through here.
    const skipPostCheck = false;

    // Fast-path: a successful PostToolUse on a known non-writing tool (for
    // example Read or Grep) is captured locally and skips the daemon. Bash is
    // deliberately excluded from this fast path even when it exits 0 because
    // only a post-call filesystem comparison can establish its actual effects.
    const postToolName = event.tool_name || rawInput.tool_name || "";
    const isKnownReadOnlyPost = knownReadOnlyPostTools.has(postToolName);
    const postOutcomeIsError = event.tool_outcome === "error";
    if (isPostTool && isKnownReadOnlyPost && !postOutcomeIsError && hookEvent !== "PostToolUseFailure") {
        appendLocal(event, hookEvent, sessionId, agentName, workspaceKey, projectKey);
        appendCollectionRecord(event, DATA_DIR);
        updateSessionState(sessionId, agentName, event);
        // Read/Grep/WebFetch ran no checks, so there is nothing to tell the
        // model — and under THE OUTPUT RULE nothing to write. Exit 0 with no
        // stdout is a successful no-op for every supported runner; the event
        // is already recorded locally above.
        writeProviderResponse("post_success", {});
        commitProviderResponseAndExit(0);
    }

    if (isPostTool && !skipPostCheck) {
        const postStartMs = Date.now();
        const postDeliveryToken = randomUUID();
        const harnessEvent = {
            hook_event: hookEvent,
            session_id: sessionId,
            agent_source: detectedClient,
            agent_name: agentName,
            tool_name: event.tool_name || rawInput.tool_name || null,
            tool_input: rawInput.tool_input || event.tool_input || null,
            tool_use_id: rawInput.tool_use_id || event.tool_use_id || null,
            post_delivery_token: postDeliveryToken,
			post_delivery_pid: process.pid,
            cwd: rawInput.cwd || event.cwd || null,
            model: event.model || null,
            timestamp: new Date().toISOString(),
            // Canonical post-event outcome fields populated by the per-client
            // normalizer's deriveToolOutcome step. Without these, Phase 1
            // failure-recovery channels (triage, recovery, recurrence) on
            // src/harness/server.ts can't see folded failures (Claude/Codex/
            // Gemini/Copilot deliver tool failures on the regular Post* event).
            tool_outcome: event.tool_outcome || null,
            error_message: event.error_message || null,
            exit_code: typeof event.exit_code === "number" ? event.exit_code : null,
            stderr: event.stderr || null,
            stdout: event.stdout || null,
            tool_response_sha256: event.tool_response_sha256 || null,
        };

        let postResult = await evaluateViaHarness(harnessEvent);
        if (postResult) {
            acknowledgePostToolDelivery(postDeliveryToken);
            // Rolling-upgrade bridge: an older daemon may have written the
			// same synchronous result to the retired shared file. Claim it now so
			// the next PreTool cannot repeat it, but do not merge an unscoped file
			// whose extra text could belong to another concurrent request.
			claimLegacyQualityWarnings();
        }

        if (!postResult) {
			if (!coldRecoveryResult) {
				coldRecoveryResult = tryHealHarness(harnessEvent);
				reportHarnessRecovery(coldRecoveryResult);
			}
        }

        if (!postResult) {
            postResult = inlinePostToolFallback(rawInput, event);
        }

        const postElapsedMs = Date.now() - postStartMs;

        if (postResult) {
            const warnings = postResult.warnings || [];
            // THE DECISION DECIDES, never the warning count. This branch used
            // to test the warning list FIRST, so a decision the harness type
            // fully permits — a block carrying a reason but an empty warnings
            // array — fell through to the clean path: recorded as allow, stdout
            // suppressed, refusal silently discarded. Today's PostToolUse
            // evaluator attaches warnings to every block, which made the hole
            // latent rather than live; cloud mutation verdicts add decision
            // paths that need not, and a swallowed block is the exact failure
            // this system exists to prevent. Never order a safety branch behind
            // an incidental property of its payload.
            const isBlockingPostDecision = postResult.decision === "block";

            if (isBlockingPostDecision || warnings.length > 0) {
                const issueList = warnings.join("\\n\\n");
                const toolLabel = event.tool_name || "unknown";
                const editedFile = lastCheckFile(event, rawInput);
                writeLastCheck({ result: isBlockingPostDecision ? "block" : "warn", tool: toolLabel, file: editedFile, count: warnings.length, ms: postElapsedMs });
                const responseType = isBlockingPostDecision ? "post_block" : "post_warn";
                const responsePayload = isBlockingPostDecision
                    ? {
                        // Prefer the harness-composed reason (blocking findings first,
                        // advisory tail demoted) so one deterministic error doesn't bury
                        // the actionable item under the heuristic pile. Fall back to the
                        // flat warning list for non-quality blocks that set no reason.
                        reason: (postResult.reason || issueList || "Blocked by the Interlinked harness.") + "\\n\\nFix the issues above by changing the actual code.",
                    }
                    : {
                        reason: issueList,
                        summary: "[interlinked:" + toolLabel + "] Advisory findings:\\n" + issueList,
                    };
                writeProviderResponse(responseType, responsePayload);
                appendLocal(event, hookEvent, sessionId, agentName, workspaceKey, projectKey);
                appendCollectionRecord(event, DATA_DIR);
                appendGuardDecision(
                    isBlockingPostDecision ? "block" : "warn",
                    postResult,
                    event,
                    hookEvent,
                    sessionId,
                    agentName,
                    workspaceKey,
                    projectKey,
                    postElapsedMs,
                );
                updateSessionState(sessionId, agentName, event);
                captureCodeEdit(sessionId, agentName, event);
                commitProviderResponseAndExit(0);
            }

            // Success: log allow decision with structured check results
            appendGuardDecision("allow", postResult, event, hookEvent, sessionId, agentName, workspaceKey, projectKey, postElapsedMs);

            const toolLabel = event.tool_name || "unknown";
            const cleanFile = lastCheckFile(event, rawInput);
            // A clean result is TELEMETRY, not conversation. The elapsed time
            // and the summary the daemon composed are recorded here (the
            // statusline reads writeLastCheck; the activity log keeps the full
            // decision) and deliberately NOT written to stdout — one
            // "[interlinked:Bash] all clean (354ms)" row per tool call, times
            // every parallel command, is the noise that made the hook UI
            // unusable. Only findings earn the model's attention.
            writeLastCheck({ result: "clean", tool: toolLabel, file: cleanFile, ms: postElapsedMs });
            writeProviderResponse("post_success", {});
            appendLocal(event, hookEvent, sessionId, agentName, workspaceKey, projectKey);
            appendCollectionRecord(event, DATA_DIR);
            updateSessionState(sessionId, agentName, event);
            captureCodeEdit(sessionId, agentName, event);
            commitProviderResponseAndExit(0);
        } else {
            // Harness unavailable — record the diagnostic locally for
            // \`interlinked doctor\` but don't surface "no harness" to the
            // model on every event. The user's harness status / statusline
            // is the right surface for "harness is down".
            const toolLabel = event.tool_name || "unknown";
            const elapsed = Date.now() - postStartMs;
            const naFile = lastCheckFile(event, rawInput);
            writeLastCheck({ result: "no_harness", tool: toolLabel, file: naFile, ms: elapsed });
            writeProviderResponse("post_success", {});
        }
    }

    // --- Always write locally (works offline) ---
    appendLocal(event, hookEvent, sessionId, agentName, workspaceKey, projectKey);
    appendCollectionRecord(event, DATA_DIR);
    updateSessionState(sessionId, agentName, event);

    // Capture code edits from PostToolUse Edit/Write events
    if (isPostTool) {
        captureCodeEdit(sessionId, agentName, event);
    }

    // Reconcile commits on session end or stop
    if (event.event_type === "session_end" || event.event_type === "agent_stop") {
        reconcileCommits(sessionId);
    }

    // --- Fire-and-forget POST to server ---
    // Skipped when sync_mode is "local"
    if (syncMode !== "local" && serverUrl) {
        const realtimePayload = {
            workspace_uuid: workspaceId,
            workspace_key: workspaceKey,
            project_key: projectKey,
            agent_name: agentName,
            event_type: event.event_type,
            tool_name: event.tool_name,
            tool_input_summary: event.tool_input_summary,
            hook_event: event.hook_event,
            duration_ms: event.duration_ms || undefined,
            tokens_input: event.tokens?.input || undefined,
            tokens_output: event.tokens?.output || undefined,
            tokens_cache_read: event.tokens?.cache_read || undefined,
            tokens_cache_creation: event.tokens?.cache_creation || undefined,
            parent_agent: event.parent_agent || undefined,
            subagent_id: event.subagent_id || undefined,
            files_modified: event.files_modified || undefined,
            error_message: event.error ? String(event.error) : undefined,
            // v4 full-capture fields
            tool_input_json: event.tool_input !== undefined ? (typeof event.tool_input === "string" ? event.tool_input : JSON.stringify(event.tool_input)) : undefined,
            tool_response_json: event.tool_response !== undefined ? (typeof event.tool_response === "string" ? event.tool_response : JSON.stringify(event.tool_response)) : undefined,
            prompt: event.prompt || undefined,
            last_assistant_message: event.last_assistant_message || undefined,
            cwd: event.cwd || undefined,
            model: event.model || undefined,
            source: event.source || undefined,
            agent_type_hook: event.agent_type || undefined,
            tool_use_id: event.tool_use_id || undefined,
            session_id: sessionId || undefined,
            is_interrupt: event.is_interrupt || undefined,
            error_detail: event.error ? String(event.error) : undefined,
            notification_type: event.notification_type || undefined,
            notification_title: event.notification_title || undefined,
            task_subject: event.task_subject || undefined,
            task_id_hook: event.task_id || undefined,
            task_description_hook: event.task_description || undefined,
            trigger: event.trigger || undefined,
            reason: event.reason || undefined,
            permission_mode: event.permission_mode || undefined,
            transcript_path: event.transcript_path || undefined,
            teammate_name: event.teammate_name || undefined,
            team_name: event.team_name || undefined,
            custom_instructions: event.custom_instructions || undefined,
            stop_hook_active: event.stop_hook_active || undefined,
            permission_suggestions: event.permission_suggestions ? (typeof event.permission_suggestions === "string" ? event.permission_suggestions : JSON.stringify(event.permission_suggestions)) : undefined,
            agent_transcript_path: event.agent_transcript_path || undefined,
            // Bounded copy for the server; the full reasoning trace stays in
            // the local activity.jsonl (extractNewThinking is uncapped). "Local for now."
            thinking: event.thinking ? truncate(event.thinking, 4000) : undefined,
        };

        // Scrub secrets before sending to server
        scrubPayload(realtimePayload);

        try {
            const res = await fetchWithTimeout(serverUrl + "/api/hooks/activity", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    ...(authHeader ? { Authorization: authHeader } : {}),
                },
                body: JSON.stringify(realtimePayload),
            }, REALTIME_POST_TIMEOUT_MS);

            if (!res.ok) {
                const transient = res.status === 429 || res.status >= 500;
                appendSyncError("realtime_post_http", "status " + res.status);
                if (transient) {
                    enqueueRealtimeRetry(realtimePayload);
                }
            }
        } catch (e) {
            appendSyncError(
                "realtime_post_network",
                e instanceof Error ? e.message : String(e),
            );
            enqueueRealtimeRetry(realtimePayload);
        }
    }

    // --- Batch sync on session end (realtime mode only) ---
    // Batch sync is cursor-based (only sends un-synced events), so this is a no-op
    // when all events were already sent via the realtime POST above.
    const isSessionEnd = event.event_type === "session_end" || event.event_type === "agent_stop";
    if (syncMode === "realtime" && isSessionEnd && serverUrl) {
        await batchSync(
            serverUrl,
            authHeader,
            workspaceId,
            workspaceKey,
            projectKey,
            agentName,
        );
    }
}

function safeReadConfig(path) {
    try {
        return JSON.parse(readFileSync(path, "utf-8"));
    } catch {
        return null;
    }
}

function sanitizeAgentName(value) {
    if (typeof value !== "string") return null;
    const trimmed = value.trim();
    if (!trimmed) return null;
    if (trimmed.toLowerCase() === "unknown") return null;
    return trimmed.slice(0, 80);
}

function readSessionAgent(sessionId) {
    if (!sessionId) return null;
    try {
        const sessionPath = safeSessionFilePath(sessionId, ".json");
        if (!sessionPath) return null;
        if (!existsSync(sessionPath)) return null;
        const session = JSON.parse(readFileSync(sessionPath, "utf-8"));
        return sanitizeAgentName(session?.agent);
    } catch {
        return null;
    }
}

function extractAgentName(rawInput, event) {
    const candidates = [
        rawInput?.agent_name,
        rawInput?.agentName,
        rawInput?.parent_agent_name,
        rawInput?.parentAgentName,
        rawInput?.sender_name,
        rawInput?.senderName,
        rawInput?.agent?.name,
        event?.parent_agent,
    ];
    for (const candidate of candidates) {
        const normalized = sanitizeAgentName(candidate);
        if (normalized) return normalized;
    }
    return null;
}

function buildSessionAgent(clientName, sessionId) {
    const sid = typeof sessionId === "string" && sessionId.length > 0
        ? sessionId.replace(/[^a-zA-Z0-9]/g, "").slice(0, 8)
        : "global";
    const normalizedClient = sanitizeAgentName(clientName || "") || "agent";
    return ("session-" + normalizedClient.toLowerCase() + "-" + sid).slice(0, 80);
}

function resolveAgentName(config, rawInput, event, clientName, sessionId) {
    const configured = sanitizeAgentName(config?.agent_name);
    if (configured) return configured;

    const discovered = extractAgentName(rawInput, event);
    if (discovered) return discovered;

    const existingSessionAgent = readSessionAgent(sessionId);
    if (existingSessionAgent) return existingSessionAgent;

    return buildSessionAgent(clientName, sessionId);
}

${EVENT_NORMALIZERS_CHUNK}

function extractFilePath(toolName, toolInput) {
    if (!toolName || !toolInput) return null;
    const fileTools = ["Read", "Write", "Edit", "Update", "ReadFile", "WriteFile", "EditFile",
        "read_file", "write_file", "edit_file", "CreateFile", "create_file", "apply_patch",
        "view", "str_replace", "create"];
    if (toolName === "apply_patch") {
        const rawPatch = String(toolInput.command || toolInput.patch || toolInput.content || toolInput._raw_patch || "");
        const moveMatch = rawPatch.match(/^\\*\\*\\* Move to:\\s+(.+)$/m);
        if (moveMatch && moveMatch[1]) return moveMatch[1].trim();
        const fileMatch = rawPatch.match(/^\\*\\*\\* (?:Update|Add|Delete) File:\\s+(.+)$/m);
        return fileMatch && fileMatch[1] ? fileMatch[1].trim() : null;
    }
    if (!fileTools.includes(toolName)) return null;
    const path = toolInput.file_path || toolInput.filePath || toolInput.path || null;
    return typeof path === "string" ? path : null;
}

function truncate(str, maxLen) {
    if (!str) return "";
    return str.length > maxLen ? str.slice(0, maxLen) : str;
}

function summarize(toolName, input) {
    if (!toolName || !input) return toolName || "";
    switch (toolName) {
        case "Read": case "Write": case "Edit": case "Update":
        case "ReadFile": case "WriteFile": case "EditFile":
        case "read_file": case "write_file": case "edit_file":
            return truncate(String(input.file_path || input.filePath || input.path || ""), 200);
        case "Bash": case "Shell": case "shell": case "run_command":
            return truncate(String(input.command || input.cmd || ""), 200);
        case "apply_patch": {
            const patchPath = extractFilePath(toolName, input);
            return truncate(String(patchPath || toolName), 200);
        }
        case "Glob": case "glob": case "ListFiles": case "list_files":
            return truncate(String(input.pattern || input.glob || ""), 200);
        case "Grep": case "grep": case "SearchFiles": case "search_files":
            return truncate((String(input.pattern || input.query || "") + " " + String(input.path || "")).trim(), 200);
        case "WebSearch": case "web_search":
            return truncate(String(input.query || ""), 200);
        case "WebFetch": case "web_fetch":
            return truncate(String(input.url || ""), 200);
        default:
            return toolName;
    }
}

const initialHookInput = readInitialHookInput();
if (!initialHookInput.ok) process.exit(0);
primeTerminalHookContext(initialHookInput.value);
main(initialHookInput.value)
    .then(() => commitProviderStdout())
    .catch(() => terminalHookFailure());
`;
