// Tests for the fs half of the gate-reach meta-metric: eligible-file
// enumeration (delegated to `isCappableFile`), the `.interlinked/` ledger, the
// per-session throttle, and the Stop-warning assembly.
//
// Every case runs against a real temp repo — the module's whole job is reading
// the tree and the harness's own artifacts, so mocking fs would test nothing.
// ONE exception, at the bottom of this file: a `closeSync` that fails on a
// valid descriptor, which no real filesystem produces. That mock closes the
// descriptor for real before throwing, and is off for every other case.

import { chmodSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import {
	buildGateReachStopWarning,
	collectGateReachSnapshot,
	enumerateEligibleFiles,
	GATE_REACH_LEDGER_REL,
	readLatestGateReachSnapshot,
	recordGateReach,
	shouldCollectGateReach,
} from "./gate-reach-collect.js";
import { buildGateReachSnapshot, type GateReachSnapshot } from "./gate-reach.js";

/** Set only by the descriptor-close case at the bottom of this file. */
let mockCloseSyncFails = false;

vi.mock("node:fs", async (importOriginal) => {
	const real = await importOriginal<typeof import("node:fs")>();
	return {
		...real,
		closeSync: (fd: number): void => {
			real.closeSync(fd); // close for real first — never leak a descriptor
			if (mockCloseSyncFails) throw new Error("EBADF: bad file descriptor, close");
		},
	};
});

let repo: string;

function write(rel: string, content: string): void {
	const abs = join(repo, rel);
	mkdirSync(join(abs, ".."), { recursive: true });
	writeFileSync(abs, content, "utf-8");
}

function writeCoverageBaseline(files: Record<string, unknown>): void {
	write(
		".interlinked/coverage-baseline.json",
		JSON.stringify({ version: 1, updated_at: new Date(0).toISOString(), files }),
	);
}

function gateOf(snapshot: GateReachSnapshot, gate: string) {
	return snapshot.gates.find((g) => g.gate === gate);
}

beforeEach(() => {
	repo = join(tmpdir(), `gate-reach-${process.pid}-${Math.random().toString(36).slice(2)}`);
	mkdirSync(repo, { recursive: true });
});

afterEach(() => {
	rmSync(repo, { recursive: true, force: true });
});

describe("enumerateEligibleFiles", () => {
	it("counts hand-written code modules", () => {
		write("src/a.ts", "export const a = 1;\n");
		write("src/nested/deep/b.tsx", "export const b = 2;\n");
		expect(enumerateEligibleFiles(repo).sort()).toEqual(["src/a.ts", "src/nested/deep/b.tsx"]);
	});

	it("defers every exemption to isCappableFile rather than re-deciding scope", () => {
		write("src/a.ts", "export const a = 1;\n");
		write("src/a.test.ts", "it('x', () => {});\n"); // test file
		write("src/types.d.ts", "export declare const t: number;\n"); // declaration
		write("src/thing.generated.ts", "export const g = 1;\n"); // generated by path
		write("src/marked.ts", "// @generated by a tool\nexport const m = 1;\n"); // generated by marker
		write("src/data.ts", "// @codegen-data\nexport const d = 1;\n"); // codegen data
		write("scratch/probe.ts", "export const p = 1;\n"); // repo probe dir
		write(".interlinked/tool.ts", "export const s = 1;\n"); // tool state
		write("docs/notes.md", "# not code\n"); // non-code extension
		write("node_modules/pkg/index.ts", "export const n = 1;\n"); // dependency
		expect(enumerateEligibleFiles(repo)).toEqual(["src/a.ts"]);
	});

	it("returns an empty list for a tree with no code", () => {
		write("README.md", "# hi\n");
		expect(enumerateEligibleFiles(repo)).toEqual([]);
	});

	it("excludes a candidate file that cannot be opened (unreadable permissions) rather than throwing", () => {
		write("src/a.ts", "export const a = 1;\n");
		const unreadable = join(repo, "src", "locked.ts");
		writeFileSync(unreadable, "export const locked = 1;\n");
		chmodSync(unreadable, 0o000);
		try {
			expect(enumerateEligibleFiles(repo)).toEqual(["src/a.ts"]);
		} finally {
			// Restore so the afterEach rmSync can clean the temp dir up.
			chmodSync(unreadable, 0o644);
		}
	});
});

describe("collectGateReachSnapshot", () => {
	it("reports an existing empty execution journal without inventing measurements", () => {
		write("src/a.ts", "export const a = 1;\n");
		write(".interlinked/metrics/executions.jsonl", "");
		const snapshot = collectGateReachSnapshot({ cwd: repo, sessionId: "s1", now: 1000, perEditCoverageEnabled: true });
		expect(gateOf(snapshot, "per_edit_coverage")).toMatchObject({ measured: 0, reason: "0_stale_or_unavailable_observations;_0_executions_recorded" });
	});

	it("reports corrupt execution evidence as unavailable", () => {
		write("src/a.ts", "export const a = 1;\n");
		write(".interlinked/metrics/executions.jsonl", "{broken\n");
		const snapshot = collectGateReachSnapshot({ cwd: repo, sessionId: "s1", now: 1000, perEditCoverageEnabled: true });
		expect(gateOf(snapshot, "per_edit_coverage")).toMatchObject({ status: "source_unavailable", measured: 0, reason: "Malformed_execution_record" });
	});

	it("reports the coverage ratchet's real reach over the eligible tree", () => {
		write("src/a.ts", "export const a = 1;\n");
		write("src/b.ts", "export const b = 2;\n");
		write("src/c.ts", "export const c = 3;\n");
		writeCoverageBaseline({
			"src/a.ts": { lines_pct: 100, branches_pct: 100 },
			"src/b.ts": { lines_pct: 0, branches_pct: 0 },
		});
		const snapshot = collectGateReachSnapshot({
			cwd: repo,
			sessionId: "s1",
			now: 1000,
			perEditCoverageEnabled: true,
		});
		const ratchet = gateOf(snapshot, "coverage_ratchet");
		expect(ratchet?.eligible).toBe(3);
		// A file recorded at 0% is MEASURED (the ratchet knows about it); only a
		// file the baseline never mentions is unmeasured.
		expect(ratchet?.measured).toBe(2);
		expect(ratchet?.unmeasured).toBe(1);
		expect(ratchet?.status).toBe("measured");
	});

	it("ignores baseline entries that are no longer eligible files", () => {
		write("src/a.ts", "export const a = 1;\n");
		writeCoverageBaseline({
			"src/a.ts": { lines_pct: 100, branches_pct: 100 },
			"src/deleted.ts": { lines_pct: 100, branches_pct: 100 },
			"src/a.test.ts": { lines_pct: 100, branches_pct: 100 },
		});
		const snapshot = collectGateReachSnapshot({
			cwd: repo,
			sessionId: "s1",
			now: 1000,
			perEditCoverageEnabled: true,
		});
		expect(gateOf(snapshot, "coverage_ratchet")?.measured).toBe(1);
	});

	it("marks the coverage ratchet unavailable when no baseline exists", () => {
		write("src/a.ts", "export const a = 1;\n");
		const snapshot = collectGateReachSnapshot({
			cwd: repo,
			sessionId: "s1",
			now: 1000,
			perEditCoverageEnabled: true,
		});
		const ratchet = gateOf(snapshot, "coverage_ratchet");
		expect(ratchet?.status).toBe("source_unavailable");
		expect(ratchet?.measured).toBe(0);
	});

	it("reports the per-edit coverage gate as disabled, with the config reason", () => {
		write("src/a.ts", "export const a = 1;\n");
		writeCoverageBaseline({ "src/a.ts": { lines_pct: 100, branches_pct: 100 } });
		const snapshot = collectGateReachSnapshot({
			cwd: repo,
			sessionId: "s1",
			now: 1000,
			perEditCoverageEnabled: false,
		});
		const perEdit = gateOf(snapshot, "per_edit_coverage");
		expect(perEdit?.status).toBe("disabled");
		expect(perEdit?.eligible).toBe(1);
		expect(perEdit?.measured).toBe(0);
		expect(perEdit?.reason).toContain("per_edit_coverage.enabled=false");
	});

	it("reports an enabled per-edit coverage gate as unmeasured, not as measured", () => {
		// The gate being ON does not prove it ran: nothing records per-edit
		// measurements yet, so claiming reach here would fabricate the exact
		// confidence this module exists to remove.
		write("src/a.ts", "export const a = 1;\n");
		const snapshot = collectGateReachSnapshot({
			cwd: repo,
			sessionId: "s1",
			now: 1000,
			perEditCoverageEnabled: true,
		});
		const perEdit = gateOf(snapshot, "per_edit_coverage");
		expect(perEdit?.status).toBe("source_unavailable");
		expect(perEdit?.reason).toContain("no_per_edit_measurement_ledger");
	});

	it("reports no gates at all for a tree with no product code", () => {
		// A docs-only checkout or a non-repo cwd has no domain, so there is no
		// reach question — asking it anyway would nag every Stop.
		write("README.md", "# hi\n");
		const snapshot = collectGateReachSnapshot({
			cwd: repo,
			sessionId: "s1",
			now: 1000,
			perEditCoverageEnabled: false,
		});
		expect(snapshot.gates).toEqual([]);
	});

	it("stamps the snapshot with session and time", () => {
		write("src/a.ts", "export const a = 1;\n");
		const snapshot = collectGateReachSnapshot({
			cwd: repo,
			sessionId: "abc",
			now: 1_700_000_000_000,
			perEditCoverageEnabled: false,
		});
		expect(snapshot.session_id).toBe("abc");
		expect(snapshot.at).toBe(new Date(1_700_000_000_000).toISOString());
	});
});

describe("recordGateReach / readLatestGateReachSnapshot", () => {
	const snapshotAt = (sessionId: string, at: number) =>
		buildGateReachSnapshot({ sessionId, at, inputs: [{ gate: "g", eligible: 2, measured: 1 }] });

	it("round-trips the newest appended snapshot", () => {
		recordGateReach(repo, snapshotAt("first", 1000));
		recordGateReach(repo, snapshotAt("second", 2000));
		expect(readLatestGateReachSnapshot(repo)?.session_id).toBe("second");
	});

	it("returns null when nothing has been recorded", () => {
		expect(readLatestGateReachSnapshot(repo)).toBeNull();
	});

	it("skips a torn or malformed trailing line instead of throwing", () => {
		recordGateReach(repo, snapshotAt("good", 1000));
		writeFileSync(join(repo, GATE_REACH_LEDGER_REL), '{"version":1,"at":"x"', { flag: "a" });
		expect(readLatestGateReachSnapshot(repo)?.session_id).toBe("good");
	});

	it("never throws when the ledger directory cannot be created", () => {
		// A regular FILE standing where the repo root should be makes the
		// `.interlinked/` mkdir fail with ENOTDIR — a portable unwritable-path
		// fixture that probes no system directory. The diary must never take the
		// daemon down.
		write("not-a-dir", "x\n");
		expect(() => recordGateReach(join(repo, "not-a-dir"), snapshotAt("x", 1))).not.toThrow();
	});

	it("appends rather than overwrites", () => {
		recordGateReach(repo, snapshotAt("first", 1000));
		recordGateReach(repo, snapshotAt("second", 2000));
		const rows = readFileSync(join(repo, GATE_REACH_LEDGER_REL), "utf-8").trim().split("\n");
		expect(rows).toHaveLength(2);
	});
});

describe("shouldCollectGateReach", () => {
	const record = (sessionId: string, at: number) =>
		recordGateReach(
			repo,
			buildGateReachSnapshot({ sessionId, at, inputs: [{ gate: "g", eligible: 1, measured: 1 }] }),
		);

	it("collects when nothing has been recorded yet", () => {
		expect(shouldCollectGateReach({ cwd: repo, sessionId: "s", now: 5000 })).toBe(true);
	});

	it("throttles a repeat within the interval for the same session", () => {
		record("s", 1000);
		expect(shouldCollectGateReach({ cwd: repo, sessionId: "s", now: 2000 })).toBe(false);
	});

	it("collects again once the interval has elapsed", () => {
		record("s", 1000);
		expect(
			shouldCollectGateReach({ cwd: repo, sessionId: "s", now: 1000, intervalMs: 0 }),
		).toBe(true);
	});

	it("collects for a different session even inside the interval", () => {
		record("s", 1000);
		expect(shouldCollectGateReach({ cwd: repo, sessionId: "other", now: 2000 })).toBe(true);
	});
});

describe("buildGateReachStopWarning", () => {
	it("is loud about the disabled per-edit coverage gate and records the snapshot", () => {
		write("src/a.ts", "export const a = 1;\n");
		writeCoverageBaseline({ "src/a.ts": { lines_pct: 100, branches_pct: 100 } });
		const warning = buildGateReachStopWarning({
			cwd: repo,
			sessionId: "s1",
			perEditCoverageEnabled: false,
			now: 1000,
		});
		expect(warning).toContain("[interlinked:gate-reach]");
		expect(warning).toContain("measured NOTHING");
		expect(warning).toContain("gate=per_edit_coverage");
		expect(warning).toContain("disabled=true");
		expect(warning).toContain("gate=coverage_ratchet");
		expect(existsSync(join(repo, GATE_REACH_LEDGER_REL))).toBe(true);
	});

	it("returns null on a throttled repeat within the same session", () => {
		write("src/a.ts", "export const a = 1;\n");
		const args = { cwd: repo, sessionId: "s1", perEditCoverageEnabled: false, now: 1000 };
		expect(buildGateReachStopWarning(args)).not.toBeNull();
		expect(buildGateReachStopWarning({ ...args, now: 2000 })).toBeNull();
	});

	it("reports a reach regression against the previously recorded snapshot", () => {
		write("src/a.ts", "export const a = 1;\n");
		writeCoverageBaseline({ "src/a.ts": { lines_pct: 100, branches_pct: 100 } });
		buildGateReachStopWarning({
			cwd: repo,
			sessionId: "s1",
			perEditCoverageEnabled: true,
			now: 1000,
		});
		// Nine more eligible files appear, none of them in the baseline: the
		// ratchet's reach over the tree collapses from 100% to 10%.
		for (let i = 0; i < 9; i++) write(`src/f${i}.ts`, `export const f${i} = ${i};\n`);
		const warning = buildGateReachStopWarning({
			cwd: repo,
			sessionId: "s2",
			perEditCoverageEnabled: true,
			now: 2000,
		});
		expect(warning).toContain("reach fell 100.0% -> 10.0%");
	});

	it("stays silent in a tree with no product code", () => {
		write("README.md", "# hi\n");
		expect(
			buildGateReachStopWarning({
				cwd: repo,
				sessionId: "s1",
				perEditCoverageEnabled: false,
				now: 1000,
			}),
		).toBeNull();
	});

	it("stays silent when every gate measured and nothing regressed", () => {
		write("src/a.ts", "export const a = 1;\n");
		writeCoverageBaseline({ "src/a.ts": { lines_pct: 100, branches_pct: 100 } });
		const warning = buildGateReachStopWarning({
			cwd: repo,
			sessionId: "s1",
			perEditCoverageEnabled: true,
			now: 1000,
			gates: ["coverage_ratchet"],
		});
		expect(warning).toBeNull();
	});

	it("falls back to Date.now() when `now` is omitted", () => {
		write("src/a.ts", "export const a = 1;\n");
		const warning = buildGateReachStopWarning({ cwd: repo, sessionId: "s1", perEditCoverageEnabled: false });
		expect(warning).not.toBeNull();
	});

	it("honors an explicit intervalMs override for the throttle", () => {
		write("src/a.ts", "export const a = 1;\n");
		const args = { cwd: repo, sessionId: "s1", perEditCoverageEnabled: false, now: 1000, intervalMs: 0 };
		expect(buildGateReachStopWarning(args)).not.toBeNull();
		// intervalMs: 0 means "always collect again" — a repeat one ms later still collects.
		expect(buildGateReachStopWarning({ ...args, now: 1001 })).not.toBeNull();
	});
});

describe("readLatestGateReachSnapshot — malformed-row handling", () => {
	it.each([
		null,
		{ gate: "coverage_ratchet" },
		{ gate: "coverage_ratchet", unit: "files", status: "measured", eligible: 1, measured: 1, skipped: { no_tests: "many" }, unmeasured: 0, reach: 1 },
	])("ignores a malformed nested gate and retains the last valid snapshot: %j", (gate) => {
		const valid = buildGateReachSnapshot({ sessionId: "good", inputs: [{ gate: "coverage_ratchet", eligible: 1, measured: 1 }], at: 1000 });
		recordGateReach(repo, valid);
		writeFileSync(join(repo, GATE_REACH_LEDGER_REL), `${JSON.stringify({ ...valid, session_id: "bad", gates: [gate] })}\n`, { flag: "a" });
		expect(readLatestGateReachSnapshot(repo)).toEqual(valid);
	});

	it("skips a non-object top-level JSON value", () => {
		mkdirSync(join(repo, ".interlinked"), { recursive: true });
		writeFileSync(join(repo, GATE_REACH_LEDGER_REL), "42\n", { flag: "a" });
		expect(readLatestGateReachSnapshot(repo)).toBeNull();
	});

	it("skips a row whose version is not 1", () => {
		mkdirSync(join(repo, ".interlinked"), { recursive: true });
		writeFileSync(
			join(repo, GATE_REACH_LEDGER_REL),
			`${JSON.stringify({ version: 2, at: "x", session_id: "s", gates: [] })}\n`,
		);
		expect(readLatestGateReachSnapshot(repo)).toBeNull();
	});

	it("skips a row whose at/session_id are not strings", () => {
		mkdirSync(join(repo, ".interlinked"), { recursive: true });
		writeFileSync(
			join(repo, GATE_REACH_LEDGER_REL),
			`${JSON.stringify({ version: 1, at: 123, session_id: "s", gates: [] })}\n`,
		);
		expect(readLatestGateReachSnapshot(repo)).toBeNull();
	});

	it("skips a row whose gates field is not an array", () => {
		mkdirSync(join(repo, ".interlinked"), { recursive: true });
		writeFileSync(
			join(repo, GATE_REACH_LEDGER_REL),
			`${JSON.stringify({ version: 1, at: "2026-01-01T00:00:00.000Z", session_id: "s", gates: "nope" })}\n`,
		);
		expect(readLatestGateReachSnapshot(repo)).toBeNull();
	});

	it("returns null (fails soft) when the ledger path is a directory, not a file", () => {
		mkdirSync(join(repo, GATE_REACH_LEDGER_REL), { recursive: true });
		expect(readLatestGateReachSnapshot(repo)).toBeNull();
	});

	it("slices to the tail and drops a torn leading line when the ledger exceeds the read-tail bound", () => {
		mkdirSync(join(repo, ".interlinked"), { recursive: true });
		const path = join(repo, GATE_REACH_LEDGER_REL);
		// Pad past READ_TAIL_BYTES (64KB) with filler lines before the real snapshot.
		const filler = `${"x".repeat(2000)}\n`.repeat(40); // ~80KB
		writeFileSync(path, filler);
		const good = buildGateReachSnapshot({
			sessionId: "tail-session",
			at: 5000,
			inputs: [{ gate: "g", eligible: 1, measured: 1 }],
		});
		writeFileSync(path, `${JSON.stringify(good)}\n`, { flag: "a" });
		expect(readLatestGateReachSnapshot(repo)?.session_id).toBe("tail-session");
	});
});

describe("enumerateEligibleFiles — descriptor-close failure", () => {
	afterEach(() => {
		mockCloseSyncFails = false;
	});

	it("enumerates every eligible file even when closing a header descriptor throws", () => {
		write("src/a.ts", "export const a = 1;\n");
		write("src/b.ts", "export const b = 2;\n");
		mockCloseSyncFails = true;
		// Returning BOTH files is the discriminating observable: the close of
		// the first file's descriptor throws, so without the inner catch the
		// error would escape readHeader's `finally` and abort the whole walk
		// instead of yielding a complete list.
		expect(enumerateEligibleFiles(repo).sort()).toEqual(["src/a.ts", "src/b.ts"]);
	});
});

describe("shouldCollectGateReach — unparsable previous timestamp", () => {
	it("collects again when the previous snapshot's `at` cannot be parsed as a date", () => {
		mkdirSync(join(repo, ".interlinked"), { recursive: true });
		writeFileSync(
			join(repo, GATE_REACH_LEDGER_REL),
			`${JSON.stringify({ version: 1, at: "not-a-real-date", session_id: "s", gates: [] })}\n`,
		);
		expect(shouldCollectGateReach({ cwd: repo, sessionId: "s", now: 2000 })).toBe(true);
	});
});
