// ===========================================
// Statusline Snapshot — Checks & Rules Markdown
// ===========================================
// Split out of statusline-snapshot.ts (2026-09) to keep both files under the
// per-file line cap. Owns the "loaded-rules.md" / "loaded-checks.md" click
// targets the statusline's OSC 8 hyperlinks point to, plus the check-count
// arithmetic (`countChecks`) both those markdown builders and the snapshot's
// `checks_enabled=` row share.

import { nonNull } from "../lib/non-null.js";
import { CHECK_REGISTRY } from "./check-registry/index.js";
import { BUILTIN_RULES } from "./rules/builtin-rules.js";
import type { GuardRule, GuardRulesConfig, QualityCheckConfig, StructuralChecksConfig } from "./types.js";

export interface CheckCounts {
	/** Subprocess wrappers — entries in `quality_checks` with a `command`. */
	tools: number;
	/**
	 * In-process detectors. Sum of:
	 * 1. `agent_safety` entries in `CHECK_REGISTRY` (unconditionally loaded;
	 *    every entry runs on every PostToolUse).
	 * 2. Inline `quality_checks` entries (no `command` — they dispatch to
	 *    in-process logic, e.g. `secrets_in_source`, `strong_typing`,
	 *    `inline_language_checks`, `css_syntax`, …).
	 * 3. The `structural_checks` bundle as one unit when enabled.
	 */
	inline: number;
}

/**
 * The pipeline tag we count toward `inline_checks_enabled`. Hoisted so the
 * filter below isn't a stringly-typed conditional, and so the meaning is
 * explicit when the registry grows new pipelines (e.g. `suggestion`, which
 * we deliberately exclude — it doesn't run on every PostToolUse).
 */
const AGENT_SAFETY_PIPELINE = "agent_safety" as const;

export function countChecks(rules: GuardRulesConfig): CheckCounts {
	let tools = 0;
	let inlineFromConfig = 0;
	// SAFETY: a malformed/partial config can omit a quality_checks entry or
	// structural_checks entirely — widened to match runtime reality.
	for (const cfg of Object.values(rules.quality_checks) as (QualityCheckConfig | undefined)[]) {
		if (!cfg?.enabled) continue;
		if (isToolRunner(cfg)) {
			tools++;
		} else {
			inlineFromConfig++;
		}
	}
	const inlineFromRegistry = CHECK_REGISTRY.filter(
		(c) => c.pipeline === AGENT_SAFETY_PIPELINE,
	).length;
	const structural = (rules.structural_checks as StructuralChecksConfig | undefined)?.enabled ? 1 : 0;
	return {
		tools,
		inline: inlineFromConfig + inlineFromRegistry + structural,
	};
}

function isToolRunner(cfg: QualityCheckConfig): boolean {
	return Boolean(cfg.command);
}

export function buildLoadedRulesMarkdown(rules: GuardRulesConfig): string {
	const builtinIds = new Set(BUILTIN_RULES.map((r) => r.id));
	const disabledIds = new Set(rules.disabled_rules ?? []);

	const active = [...rules.rules].sort(byCategoryThenId);

	const byCategory = new Map<string, GuardRule[]>();
	for (const r of active) {
		const cat = r.category || "uncategorized";
		const arr = byCategory.get(cat) ?? [];
		arr.push(r);
		byCategory.set(cat, arr);
	}

	const categories = [...byCategory.keys()].sort();

	const lines: string[] = [];
	lines.push("# Interlinked harness — loaded rules");
	lines.push("");
	lines.push(
		"_Auto-generated by the harness on rule load. Do not edit — see " +
			"`docs/generated/guard-rules.md` for the full reference, or edit " +
			"`.interlinked/guard-rules.json` / `.interlinked/guard-rules.local.json` " +
			"to change what's loaded here._",
	);
	lines.push("");
	lines.push(`Total active rules: **${active.length}**`);
	lines.push("");

	for (const cat of categories) {
		const entries = byCategory.get(cat);
		if (!entries) continue;
		lines.push(`## ${humanizeCategory(cat)} (${entries.length})`);
		lines.push("");
		for (const r of entries) {
			const source = builtinIds.has(r.id) ? "built-in" : "custom";
			lines.push(`- \`${r.id}\` — ${r.action} — ${r.severity} — ${source} — ${r.reason}`);
		}
		lines.push("");
	}

	if (disabledIds.size > 0) {
		lines.push(`## Disabled rules (${disabledIds.size})`);
		lines.push("");
		for (const id of [...disabledIds].sort()) {
			lines.push(`- ~~\`${id}\`~~ — disabled in \`guard-rules.local.json\``);
		}
		lines.push("");
	}

	return lines.join("\n");
}

interface QualityEntry {
	name: string;
	cfg: QualityCheckConfig;
}

export function buildLoadedChecksMarkdown(rules: GuardRulesConfig): string {
	// SAFETY: a malformed/partial config can supply an undefined entry value.
	const rawEntries: { name: string; cfg: QualityCheckConfig | undefined }[] = Object.entries(rules.quality_checks).map(([name, cfg]) => ({ name, cfg }));
	const entries = rawEntries.sort(byEntryName);

	const enabledTools = entries.filter((e): e is QualityEntry => e.cfg?.enabled === true && isToolRunner(e.cfg));
	const enabledInlineFromConfig = entries.filter((e): e is QualityEntry => e.cfg?.enabled === true && !isToolRunner(e.cfg));
	const disabled = entries.filter((e) => !e.cfg?.enabled);

	const inlineRegistryEntries = CHECK_REGISTRY.filter(
		(c) => c.pipeline === AGENT_SAFETY_PIPELINE,
	)
		.slice()
		.sort(byId);

	const counts = countChecks(rules);

	const sections: string[][] = [
		buildChecksHeaderSection(counts),
		buildToolRunnersSection(enabledTools),
		buildConfigInlineSection(enabledInlineFromConfig, (rules.structural_checks as StructuralChecksConfig | undefined)?.enabled === true),
		buildRegistryInlineSection(inlineRegistryEntries),
		buildDisabledSection(disabled),
	];

	return sections.flat().join("\n");
}

function byEntryName(a: { name: string }, b: { name: string }): number {
	if (a.name < b.name) return -1;
	if (a.name > b.name) return 1;
	return 0;
}

function buildChecksHeaderSection(counts: CheckCounts): string[] {
	return [
		"# Interlinked harness — loaded checks",
		"",
		"_Auto-generated by the harness on rule load. Do not edit — see " +
			"`.interlinked/check-policy.json` for the active mode (balanced/strict/lenient) " +
			"or `.interlinked/guard-rules.local.json` to flip individual checks on/off._",
		"",
		`Tool runners enabled: **${counts.tools}**`,
		`Inline detectors loaded: **${counts.inline}**`,
		"",
	];
}

function buildToolRunnersSection(enabled: QualityEntry[]): string[] {
	if (enabled.length === 0) return [];
	const lines = [
		`## Tool runners — enabled (${enabled.length})`,
		"",
		"_Subprocess wrappers (tsc, biome, gitleaks, …). Each spawns an " +
			"external command per matching edit._",
		"",
	];
	for (const { name, cfg } of enabled) {
		const desc =
			cfg.description ||
			`Runs on edits to ${cfg.file_types.join(", ") || "all files"}.`;
		const cmd = cfg.command ? ` — \`${cfg.command}\`` : "";
		lines.push(`- \`${name}\` — ${cfg.severity}${cmd} — ${desc}`);
	}
	lines.push("");
	return lines;
}

function buildConfigInlineSection(
	enabled: QualityEntry[],
	structuralEnabled: boolean,
): string[] {
	if (!structuralEnabled && enabled.length === 0) return [];
	const inlineCount = enabled.length + (structuralEnabled ? 1 : 0);
	const lines = [
		`## Inline detectors — config-driven (${inlineCount})`,
		"",
		"_In-process checks toggleable through `quality_checks` in " +
			"`guard-rules.local.json`. Each is a built-in detector dispatched " +
			"in-process — no subprocess spawn._",
		"",
	];
	if (structuralEnabled) {
		lines.push(
			"- `structural_checks` — error — bundle — Cross-file dependency " +
				"checks: export surface, import resolution, dependency cycles, " +
				"blast radius. Counts as one toggle, runs ~25 sub-checks.",
		);
	}
	for (const { name, cfg } of enabled) {
		const desc =
			cfg.description ||
			`Runs on edits to ${cfg.file_types.join(", ") || "all files"}.`;
		lines.push(`- \`${name}\` — ${cfg.severity} — ${desc}`);
	}
	lines.push("");
	return lines;
}

function buildRegistryInlineSection(
	registry: ReadonlyArray<(typeof CHECK_REGISTRY)[number]>,
): string[] {
	if (registry.length === 0) return [];
	const lines = [
		`## Inline detectors — registry (${registry.length})`,
		"",
		"_Built-in `agent_safety` detectors from `src/harness/check-registry/`. " +
			"Always loaded; gated per-edit by `content_keywords` and the active " +
			"check-policy mode. Authored by the harness team — not user-toggleable " +
			"from config._",
		"",
	];
	for (const c of registry) {
		lines.push(
			`- \`${c.id}\` — ${c.severity} — ${c.phase} — tier ${c.tier} — ${c.description}`,
		);
	}
	lines.push("");
	return lines;
}

function buildDisabledSection(disabled: { name: string; cfg: QualityCheckConfig | undefined }[]): string[] {
	if (disabled.length === 0) return [];
	const lines = [
		`## Quality checks — disabled (${disabled.length})`,
		"",
		"_Re-enable in `.interlinked/guard-rules.local.json` under " +
			"`quality_checks.<name>.enabled = true`._",
		"",
	];
	for (const { name, cfg } of disabled) {
		const desc = cfg?.description || "";
		lines.push(
			`- ~~\`${name}\`~~ — ${cfg?.severity || ""} ${desc ? "— " + desc : ""}`.trim(),
		);
	}
	lines.push("");
	return lines;
}

function byCategoryThenId(a: GuardRule, b: GuardRule): number {
	const ca = a.category || "uncategorized";
	const cb = b.category || "uncategorized";
	if (ca !== cb) return ca < cb ? -1 : 1;
	return byId(a, b);
}

function byId(a: { id: string }, b: { id: string }): number {
	if (a.id === b.id) return 0;
	return a.id < b.id ? -1 : 1;
}

function humanizeCategory(cat: string): string {
	return cat
		.split(/[_-]/)
		.map((p) => (p.length === 0 ? p : nonNull(p[0]).toUpperCase() + p.slice(1)))
		.join(" ");
}
