import { describe, expect, it } from "vitest";
import { balancedArgList, collectRegexLineMatches, shouldSkipFootgunScan } from "./scan-helpers.js";

describe("shouldSkipFootgunScan", () => {
	it("scans a plain TypeScript source file", () => {
		expect(shouldSkipFootgunScan("src/app.ts", "const a = 1;")).toBe(false);
	});

	it("scans .mjs and .tsx sources", () => {
		expect(shouldSkipFootgunScan("src/a.mjs", "x")).toBe(false);
		expect(shouldSkipFootgunScan("src/a.tsx", "x")).toBe(false);
	});

	it("skips a non-JS/TS extension", () => {
		expect(shouldSkipFootgunScan("README.md", "const a = 1;")).toBe(true);
		expect(shouldSkipFootgunScan("src/app.py", "x = 1")).toBe(true);
	});

	it("skips a test file", () => {
		expect(shouldSkipFootgunScan("src/app.test.ts", "const a = 1;")).toBe(true);
	});

	it("skips generated content", () => {
		expect(shouldSkipFootgunScan("src/app.ts", "// @generated by codegen\nconst a = 1;")).toBe(true);
	});
});

describe("balancedArgList", () => {
	it("returns the argument text of a simple call", () => {
		const src = "f(a, b)";
		expect(balancedArgList(src, src.indexOf("("))).toBe("a, b");
	});

	it("respects nested parens", () => {
		const src = "f(g(1), h(2))";
		expect(balancedArgList(src, src.indexOf("("))).toBe("g(1), h(2)");
	});

	it("returns an empty string for an empty argument list", () => {
		const src = "f()";
		expect(balancedArgList(src, src.indexOf("("))).toBe("");
	});

	it("returns null when the call is never closed", () => {
		const src = "f(a, b";
		expect(balancedArgList(src, src.indexOf("("))).toBeNull();
	});
});

describe("collectRegexLineMatches", () => {
	it("reports the 1-based line and trimmed text of each match", () => {
		const content = "const a = 1;\n\tdanger(x);\nconst b = 2;\ndanger(y);\n";
		expect(collectRegexLineMatches(content, /danger\(/g)).toEqual([
			{ line: 2, text: "danger(x);" },
			{ line: 4, text: "danger(y);" },
		]);
	});

	it("returns an empty array when nothing matches", () => {
		expect(collectRegexLineMatches("const a = 1;\n", /danger\(/g)).toEqual([]);
	});

	it("truncates the reported text to 150 characters", () => {
		const content = `danger(${"x".repeat(400)});`;
		const [only] = collectRegexLineMatches(content, /danger\(/g);
		expect(only?.text).toHaveLength(150);
	});

	it("resets lastIndex so a module-level /g regex is reusable", () => {
		const re = /danger\(/g;
		const content = "danger(a);\ndanger(b);\n";
		const first = collectRegexLineMatches(content, re);
		expect(collectRegexLineMatches(content, re)).toEqual(first);
		expect(first).toHaveLength(2);
	});
});
