// The shadow contract's pin is only worth what its INPUT SET is worth.
// `protocol/shadow-v1/contract-digest.json` is regenerated by hand
// (`npx tsx scripts/gen-shadow-contract-digest.mts`), so nothing but this test
// stops a package change from landing while the committed digest still
// describes the previous tree — and `interlinked-cloud` re-vendors against that
// digest, so a stale pin is a stale contract on BOTH sides.
//
// It recomputes the pin IN-PROCESS through the generator's own exported
// computation rather than a second copy of the rules: a divergence here is a
// divergence between the tree and the committed file, never between two
// re-implementations of the algorithm.
//
// The second obligation is the input set itself. Six package modules import
// `../../mutation/protocol-v3/canonical.js` — the canonicalizer that decides the
// BYTES every shadow hash is computed over. A pin covering only files beneath
// the package would let that module change while the shadow digest stayed
// valid, so the generator follows transitive relative imports out of the
// package and these cases pin that it still does.

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import {
	buildShadowContractDigest,
	relativeSpecifiersOf,
	resolveImportTarget,
	serializeShadowContractDigest,
	SHADOW_DIGEST_PATH,
	toPosixLabel,
} from "../../../../../scripts/gen-shadow-contract-digest.mjs";

const PACKAGE_PREFIX = "src/harness/shadow/protocol/";
const CANONICALIZER = "src/harness/mutation/protocol-v3/canonical.ts";

describe("shadow contract digest — positive (must hold)", () => {
	it("P1: the committed contract-digest.json matches the tree", () => {
		const committed = readFileSync(SHADOW_DIGEST_PATH, "utf8");
		expect(committed).toBe(serializeShadowContractDigest(buildShadowContractDigest()));
	});

	it("P2: the transitive canonicalizer outside the package is a normative source", () => {
		expect(buildShadowContractDigest().normative_sources).toContain(CANONICALIZER);
	});

	it("P3: every non-test module of the package is a normative source", () => {
		const sources = buildShadowContractDigest().normative_sources;
		const inPackage = sources.filter((source) => source.startsWith(PACKAGE_PREFIX));
		expect(inPackage).toContain(`${PACKAGE_PREFIX}registry.ts`);
		expect(inPackage).toContain(`${PACKAGE_PREFIX}canonical.ts`);
		expect(inPackage).toContain(`${PACKAGE_PREFIX}index.ts`);
		expect(inPackage.length).toBeGreaterThan(30);
	});

	it("P4: files counts the normative sources plus the contract directory", () => {
		const record = buildShadowContractDigest();
		expect(record.files).toBeGreaterThan(record.normative_sources.length);
		expect(record.digest).toMatch(/^[0-9a-f]{64}$/);
	});
});

describe("shadow contract digest — negative (must not hold)", () => {
	it("N1: no test file is pinned as a normative source", () => {
		const sources = buildShadowContractDigest().normative_sources;
		expect(sources.filter((source) => source.endsWith(".test.ts"))).toEqual([]);
	});

	it("N2: an unreachable mutation module is NOT pulled into the pin", () => {
		const sources = buildShadowContractDigest().normative_sources;
		expect(sources).not.toContain("src/harness/mutation/protocol-v3/verify.ts");
		expect(sources).not.toContain("src/harness/mutation/protocol-v3/receipts.ts");
	});

	it("N3: no normative-source label carries a Windows separator", () => {
		const sources = buildShadowContractDigest().normative_sources;
		expect(sources.filter((source) => source.includes("\\"))).toEqual([]);
	});

	it("N4: a changed source cannot leave the digest unchanged", () => {
		const record = buildShadowContractDigest();
		const otherLabels = record.normative_sources.filter((source) => source !== CANONICALIZER);
		expect(otherLabels.length).toBe(record.normative_sources.length - 1);
		expect(record.algorithm).toContain("sorted label order");
	});
});

// ── the discovery itself ───────────────────────────────────────────────────
// The pin's input set was found with a regex that recognized only
// double-quoted `from "…"` / `import "…"`. Every form below was invisible to
// it, and an invisible import is a normative source the digest silently does
// not cover. Discovery now reads the TypeScript AST and FAILS on anything it
// cannot follow, so these cases pin both halves: what it must see, and what it
// must refuse to guess at.

const PACKAGE_DIR = join(dirname(fileURLToPath(import.meta.url)), "..");

function specifiers(source: string): string[] {
	return relativeSpecifiersOf(join(PACKAGE_DIR, "probe.ts"), source);
}

describe("contract-digest import discovery — positive (must find)", () => {
	it("P5: a single-quoted import is found", () => {
		expect(specifiers("import { a } from './a.js';")).toEqual(["./a.js"]);
	});

	it("P6: a side-effect import with no bindings is found", () => {
		expect(specifiers("import './side-effect.js';")).toEqual(["./side-effect.js"]);
	});

	it("P7: `export … from` and `export * from` are found", () => {
		expect(specifiers("export { a } from './a.js';\nexport * from '../b.js';")).toEqual(["./a.js", "../b.js"]);
	});

	it("P8: a dynamic import() with a literal specifier is found", () => {
		expect(specifiers("async function load() { return import('./lazy.js'); }")).toEqual(["./lazy.js"]);
	});

	it("P9: `import type` and a nested `import … = require()` are found", () => {
		expect(specifiers('import type { T } from "./types.js";')).toEqual(["./types.js"]);
		expect(specifiers('import legacy = require("./legacy.js");')).toEqual(["./legacy.js"]);
	});

	it("P10: bare and `node:` specifiers are ignored — the lockfile pins those", () => {
		expect(specifiers('import { createHash } from "node:crypto";\nimport ts from "typescript";')).toEqual([]);
	});

	it("P11: a Windows-style label is normalized to POSIX", () => {
		expect(toPosixLabel(["src", "harness", "shadow", "protocol", "canonical.ts"].join("\\"))).toContain("canonical.ts");
		expect(toPosixLabel("src/harness/canonical.ts")).toBe("src/harness/canonical.ts");
	});

	it("P12: a real relative specifier resolves to the .ts file it compiles from", () => {
		const from = join(PACKAGE_DIR, "canonical.ts");
		expect(resolveImportTarget(from, "../../mutation/protocol-v3/canonical.js")).toMatch(/protocol-v3[/\\]canonical\.ts$/);
	});
});

describe("contract-digest import discovery — negative (must refuse)", () => {
	it("N5: an unresolved relative import FAILS the run instead of being skipped", () => {
		const from = join(PACKAGE_DIR, "canonical.ts");
		expect(() => resolveImportTarget(from, "./this-module-does-not-exist.js")).toThrow(/unresolved relative import/);
	});

	it("N6: a dynamic import() with a computed specifier FAILS — it cannot be pinned", () => {
		expect(() => specifiers("const name = 'x'; void import(`./${name}.js`);")).toThrow(/cannot be pinned/);
	});

	it("N7: a dynamic import() with no argument FAILS rather than being ignored", () => {
		expect(() => specifiers("void import();")).toThrow(/cannot be pinned/);
	});

	it("N8: a re-export with no module (`export { a }`) contributes no specifier", () => {
		expect(specifiers("const a = 1;\nexport { a };")).toEqual([]);
	});
});
