#!/usr/bin/env npx tsx
// ===========================================
// Documentation Generator
// ===========================================
// Generates reference documentation from code data structures.
// Run: npx tsx scripts/generate-docs.ts
// Output: docs/generated/*.md
//
// The Stainless principle: the code IS the documentation.
// These files are derived artifacts — edit the source data, not the output.

import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join } from "node:path";

// Import data structures from the harness
import { getDefaultConfig, getBuiltinRules } from "../src/harness/rules-loader.js";
import { STRUCTURAL_CHECK_META } from "../src/harness/check-metadata.js";
import {
	DEFAULT_METACODER_CONFIG,
	USER_PROMPT_HOOK_TIMEOUT_MS,
} from "../src/harness/metacoder/types.js";

const OUT_DIR = join(import.meta.dirname, "..", "docs", "generated");
if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });

// ===========================================
// Guard Rules Reference
// ===========================================

function generateGuardRules(): string {
	const rules = getBuiltinRules();
	const lines: string[] = [
		"<!-- Auto-generated by scripts/generate-docs.ts — do not edit manually -->",
		"# Guard Rules Reference",
		"",
		`${rules.length} built-in rules that block or warn on dangerous operations.`,
		"These evaluate on every PreToolUse event (before tool execution).",
		"",
	];

	// Group by category
	const byCategory = new Map<string, typeof rules>();
	for (const rule of rules) {
		const cat = (rule as { category?: string }).category || "uncategorized";
		if (!byCategory.has(cat)) byCategory.set(cat, []);
		byCategory.get(cat)!.push(rule);
	}

	// Sort categories for stable output
	const sortedCategories = [...byCategory.keys()].sort();

	for (const cat of sortedCategories) {
		const catRules = byCategory.get(cat)!;
		const displayName = cat
			.split("-")
			.map((w) => w.charAt(0).toUpperCase() + w.slice(1))
			.join(" ");

		lines.push(`## ${displayName}`);
		lines.push("");
		lines.push("| Rule | Severity | Action | Description |");
		lines.push("|------|----------|--------|-------------|");

		for (const rule of catRules) {
			const suggestion = rule.suggestion ? ` ${rule.suggestion}` : "";
			lines.push(
				`| \`${rule.id}\` | ${rule.severity} | ${rule.action} | ${rule.reason}${suggestion} |`,
			);
		}
		lines.push("");
	}

	return lines.join("\n");
}

// ===========================================
// Quality Checks Reference
// ===========================================

function generateQualityChecks(): string {
	const config = getDefaultConfig();
	const checks = config.quality_checks;

	const lines: string[] = [
		"<!-- Auto-generated by scripts/generate-docs.ts — do not edit manually -->",
		"# Quality Checks Reference",
		"",
		`${Object.keys(checks).length} PostToolUse checks that run after file edits.`,
		"Subprocess-based checks run external tools (tsc, biome, etc.); inline checks scan file content directly.",
		"",
		"| Check | Severity | File Types | Description |",
		"|-------|----------|------------|-------------|",
	];

	for (const [name, check] of Object.entries(checks)) {
		const types = check.file_types.slice(0, 5).join(", ");
		const overflow = check.file_types.length > 5 ? " ..." : "";
		const desc = check.description || name;
		const kind = check.command ? "subprocess" : "inline";
		lines.push(
			`| \`${name}\` (${kind}) | ${check.severity} | ${types}${overflow} | ${desc} |`,
		);
	}

	lines.push("");
	return lines.join("\n");
}

// ===========================================
// Structural Checks Reference
// ===========================================

function generateStructuralChecks(): string {
	const lines: string[] = [
		"<!-- Auto-generated by scripts/generate-docs.ts — do not edit manually -->",
		"# Structural Checks Reference",
		"",
		`${Object.keys(STRUCTURAL_CHECK_META).length} dependency-aware checks that run after file edits.`,
		"These analyze the project graph to detect cross-file issues that single-file lint can't catch.",
		"",
	];

	// Group by tier
	const byTier = new Map<number, [string, (typeof STRUCTURAL_CHECK_META)[string]][]>();
	for (const [key, meta] of Object.entries(STRUCTURAL_CHECK_META)) {
		if (!byTier.has(meta.tier)) byTier.set(meta.tier, []);
		byTier.get(meta.tier)!.push([key, meta]);
	}

	const tierLabels: Record<number, string> = {
		1: "Tier 1 — Fast (sub-100ms, every edit)",
		2: "Tier 2 — Medium (sub-1s, every edit)",
		3: "Tier 3 — Conditional (1-5s, only when needed)",
	};

	for (const tier of [1, 2, 3]) {
		const checks = byTier.get(tier);
		if (!checks || checks.length === 0) continue;

		lines.push(`## ${tierLabels[tier]}`);
		lines.push("");
		lines.push("| Check | Config Key | Description |");
		lines.push("|-------|-----------|-------------|");

		for (const [key, meta] of checks) {
			lines.push(`| ${meta.name} | \`${key}\` | ${meta.description} |`);
		}
		lines.push("");
	}

	return lines.join("\n");
}

// ===========================================
// Configuration Reference
// ===========================================

function generateConfigReference(): string {
	const config = getDefaultConfig();
	const lines: string[] = [
		"<!-- Auto-generated by scripts/generate-docs.ts — do not edit manually -->",
		"# Configuration Reference",
		"",
		"Default configuration for the Interlinked CLI harness.",
		"Override in `.interlinked/guard-rules.json` (team) or `.interlinked/guard-rules.local.json` (personal).",
		"",
		"## Diff-Aware Filtering",
		"",
		"Controls which checks suppress pre-existing findings when editing files.",
		"",
		"| Setting | Default | Description |",
		"|---------|---------|-------------|",
	];

	const da = config.diff_aware;
	if (da) {
		lines.push(`| \`enabled\` | \`${da.enabled}\` | Master switch for diff-aware filtering |`);
		if (da.missing_return_types) lines.push(`| \`missing_return_types\` | \`"${da.missing_return_types}"\` | Only report new findings via pre-edit baseline subtraction |`);
		if (da.complexity) lines.push(`| \`complexity\` | \`"${da.complexity}"\` | Only report complex functions in the edited region |`);
		if (da.no_test_file) lines.push(`| \`no_test_file\` | \`"${da.no_test_file}"\` | Only fire on new file creation (Write), not edits |`);
		if (da.undefined_env_vars) lines.push(`| \`undefined_env_vars\` | \`"${da.undefined_env_vars}"\` | Only report env vars introduced by the edit |`);
	}

	lines.push("");
	lines.push("## Structural Checks");
	lines.push("");
	lines.push("| Setting | Default | Description |");
	lines.push("|---------|---------|-------------|");

	const sc = config.structural_checks;
	for (const [key, value] of Object.entries(sc)) {
		if (typeof value === "boolean") {
			const meta = STRUCTURAL_CHECK_META[key];
			const desc = meta ? meta.description : key;
			lines.push(`| \`${key}\` | \`${value}\` | ${desc} |`);
		} else if (typeof value === "number") {
			lines.push(`| \`${key}\` | \`${value}\` | Threshold setting |`);
		}
	}

	lines.push("");
	lines.push("## Metacoder (per-prompt overlay)");
	lines.push("");
	lines.push(
		"On every `UserPromptSubmit` the metacoder runs a peer of the coding agent (Opus 4.7 max-effort for Claude sessions, GPT-5.5 xhigh for Codex sessions) to emit a session-scoped overlay of guard rules. Both transports use the user's existing **Claude Code / Codex CLI subscription** — no API key required. Plan: [docs/design/metacoding-agent-plan.md](../design/metacoding-agent-plan.md).",
	);
	lines.push("");
	lines.push("**Toggle from the CLI:**");
	lines.push("");
	lines.push("```");
	lines.push("interlinked metacoder status        # show current state + recent audit");
	lines.push("interlinked metacoder enable        # turn on (default)");
	lines.push("interlinked metacoder disable --reason \"burn rate\"   # turn off, with audit");
	lines.push("```");
	lines.push("");
	lines.push("**Or hand-edit `.interlinked/guard-rules.local.json`:**");
	lines.push("");
	lines.push("```json");
	lines.push("{");
	lines.push("  \"metacoder\": { \"enabled\": false }");
	lines.push("}");
	lines.push("```");
	lines.push("");
	lines.push("| Setting | Default | Description |");
	lines.push("|---------|---------|-------------|");
	const m = DEFAULT_METACODER_CONFIG;
	lines.push(`| \`enabled\` | \`${m.enabled}\` | Master switch for the per-prompt metacoder |`);
	lines.push(`| \`timeout_ms\` | \`${m.timeout_ms}\` | Metacoder LLM call timeout. Clamped at merge to keep < hook timeout (${USER_PROMPT_HOOK_TIMEOUT_MS - 2_000} ms). |`);
	lines.push(`| \`max_rules\` | \`${m.max_rules}\` | Hard cap on overlay rule count per emission |`);
	lines.push(`| \`max_pattern_length\` | \`${m.max_pattern_length}\` | Per-pattern regex char cap (bounds ReDoS / compile cost) |`);
	lines.push(`| \`max_patterns_per_rule\` | \`${m.max_patterns_per_rule}\` | Patterns-per-rule cap |`);
	lines.push(`| \`max_addendum_chars\` | \`${m.max_addendum_chars}\` | \`system_prompt_addendum\` length cap |`);
	lines.push("");
	lines.push(
		`**Hook timeout coordination:** the generated hook waits ${USER_PROMPT_HOOK_TIMEOUT_MS} ms (5 s buffer past the metacoder's internal timeout) so the harness can return a clean "metacoder timed out, allow" decision before the hook cold-falls back. Both \`hook-entry.ts\` (adapter path) and the generated \`.mjs\` (legacy path) honor this budget.`,
	);
	lines.push("");
	lines.push("**Latency / cost:** 5–30 s per prompt, $0.05–$0.30 per prompt (Opus 4.7 max-effort). Fail-open: any subprocess failure (CLI not installed, subscription quota hit, timeout) skips the overlay and lets the prompt reach the agent against floor rules only.");
	lines.push("");
	return lines.join("\n");
}

// ===========================================
// CLI Command Reference (from commander --help output)
// ===========================================

import { execFileSync } from "node:child_process";

function getHelpOutput(args: string[]): string {
	let raw: string;
	try {
		raw = execFileSync(
			process.execPath,
			["--import", "tsx", join(import.meta.dirname, "..", "src", "index.ts"), ...args, "--help"],
			{
				encoding: "utf-8",
				timeout: 10_000,
				env: { ...process.env, INTERLINKED_SKIP_IMPLICIT_ENTRY: "1" },
			},
		).trim();
	} catch (err) {
		// Commander writes help to stdout and exits with code 0, but execFileSync
		// may throw if the process exits before consuming all stdin. Try stderr fallback.
		const e = err as { stdout?: string; stderr?: string };
		raw = (e.stdout || e.stderr || "").trim();
	}
	// Strip the repeated "Interface boundaries" / "Quick start" footer that commander appends
	const footerIdx = raw.indexOf("\nInterface boundaries:");
	const withoutFooter = footerIdx >= 0 ? raw.slice(0, footerIdx).trimEnd() : raw;
	return sanitizeHelpOutput(withoutFooter);
}

function sanitizeHelpOutput(output: string): string {
	return output.split(process.cwd()).join("<cwd>");
}

function generateCliReference(): string {
	const lines: string[] = [
		"<!-- Auto-generated by scripts/generate-docs.ts — do not edit manually -->",
		"# Interlinked CLI Command Reference",
		"",
	];

	// Top-level help
	const topHelp = getHelpOutput([]);
	lines.push("## Overview", "", "```", topHelp, "```", "");

	// Extract top-level command names from help output
	const commandNames = [
		"structure",
		"verify",
		"harness",
		"checkpoint",
		"tasks",
		"workspace",
		"index",
		"trace",
		"guard",
		"git",
		"metacoder",
	];

	// Commands with subcommands — mirror the groups registered in src/index.ts.
	const commandsWithSubs: Record<string, string[]> = {
		structure: ["init", "scan", "status", "accept", "doctor", "baseline"],
		checkpoint: ["list", "show", "compare", "prune", "archive"],
		tasks: ["list", "create", "show", "claim", "complete"],
		workspace: ["list", "switch"],
		index: ["build", "update", "status", "query"],
		trace: ["export", "import"],
		harness: ["start", "stop", "restart", "status", "test"],
		guard: ["install", "check", "status", "uninstall"],
		git: ["context", "link-checkpoint"],
		reminder: ["add", "list", "remove"],
		coverage: ["check", "baseline"],
		mutation: ["check", "baseline"],
		completions: ["bash", "zsh", "fish"],
		metacoder: ["enable", "disable", "status"],
	};

	for (const cmd of commandNames) {
		const cmdHelp = getHelpOutput([cmd]);
		if (!cmdHelp) continue;

		const title = cmd.charAt(0).toUpperCase() + cmd.slice(1);
		lines.push(`## ${title}`, "", "```", cmdHelp, "```", "");

		const subs = commandsWithSubs[cmd];
		if (subs) {
			for (const sub of subs) {
				const subHelp = getHelpOutput([cmd, sub]);
				if (!subHelp) continue;
				lines.push(`### ${cmd} ${sub}`, "", "```", subHelp, "```", "");
			}
		}
	}

	// Also document standalone commands with notable options
	const standaloneCommands = [
		"enable", "disable", "status", "activity", "doctor", "clean",
		"login", "sync", "send", "inbox", "watch",
	];
	lines.push("## Other Commands", "");
	for (const cmd of standaloneCommands) {
		const cmdHelp = getHelpOutput([cmd]);
		if (!cmdHelp) continue;
		lines.push(`### ${cmd}`, "", "```", cmdHelp, "```", "");
	}

	return lines.join("\n");
}

// ===========================================
// Main
// ===========================================

const files = [
	{ name: "guard-rules.md", generator: generateGuardRules },
	{ name: "quality-checks.md", generator: generateQualityChecks },
	{ name: "structural-checks.md", generator: generateStructuralChecks },
	{ name: "configuration.md", generator: generateConfigReference },
	{ name: "cli-reference.md", generator: generateCliReference },
];

let generated = 0;
for (const { name, generator } of files) {
	const content = generator();
	const path = join(OUT_DIR, name);
	writeFileSync(path, content);
	console.log(`  Generated: docs/generated/${name}`);
	generated++;
}

console.log(`\n${generated} reference docs generated from code.`);
