#!/usr/bin/env npx tsx
// ===========================================
// Documentation Generator
// ===========================================
// Generates reference documentation from code data structures.
// Run: npx tsx scripts/generate-docs.ts
// Output: docs/generated/*.md
//
// The Stainless principle: the code IS the documentation.
// These files are derived artifacts — edit the source data, not the output.

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { STRUCTURAL_CHECK_META } from "../src/harness/check-metadata.js";
import { METRIC_DEFS } from "../src/harness/metric-caps.js";
// Import data structures from the harness
import { getBuiltinRules, getDefaultConfig } from "../src/harness/rules-loader.js";
import { ALL_SEQUENCE_DETECTORS } from "../src/harness/sequence-checks/registry.js";
import type {
	SequenceDetector,
	SequenceDetectorFamily,
} from "../src/harness/sequence-checks/types.js";

const OUT_DIR = join(import.meta.dirname, "..", "docs", "generated");
if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });

// ===========================================
// Guard Rules Reference
// ===========================================

function generateGuardRules(): string {
	const rules = getBuiltinRules();
	const lines: string[] = [
		"<!-- Auto-generated by scripts/generate-docs.ts — do not edit manually -->",
		"# Guard Rules Reference",
		"",
		`${rules.length} built-in rules that block or warn on dangerous operations.`,
		"These evaluate on every delivered PreToolUse event (before tool execution).",
		"",
	];

	// Group by category
	const byCategory = new Map<string, typeof rules>();
	for (const rule of rules) {
		const cat = (rule as { category?: string }).category || "uncategorized";
		if (!byCategory.has(cat)) byCategory.set(cat, []);
		byCategory.get(cat)!.push(rule);
	}

	// Sort categories for stable output
	const sortedCategories = [...byCategory.keys()].sort();

	for (const cat of sortedCategories) {
		const catRules = byCategory.get(cat)!;
		const displayName = cat
			.split("-")
			.map((w) => w.charAt(0).toUpperCase() + w.slice(1))
			.join(" ");

		lines.push(`## ${displayName}`);
		lines.push("");
		lines.push("| Rule | Severity | Action | Description |");
		lines.push("|------|----------|--------|-------------|");

		for (const rule of catRules) {
			const suggestion = rule.suggestion ? ` ${rule.suggestion}` : "";
			lines.push(
				`| \`${rule.id}\` | ${rule.severity} | ${rule.action} | ${rule.reason}${suggestion} |`,
			);
		}
		lines.push("");
	}

	return lines.join("\n");
}

// ===========================================
// Quality Checks Reference
// ===========================================

function generateQualityChecks(): string {
	const config = getDefaultConfig();
	const checks = config.quality_checks;

	const lines: string[] = [
		"<!-- Auto-generated by scripts/generate-docs.ts — do not edit manually -->",
		"# Quality Checks Reference",
		"",
		`${Object.keys(checks).length} PostToolUse checks that run after file edits.`,
		"Subprocess-based checks run external tools (tsc, biome, etc.); inline checks scan file content directly.",
		"",
		"| Check | Severity | File Types | Description |",
		"|-------|----------|------------|-------------|",
	];

	for (const [name, check] of Object.entries(checks)) {
		const types = check.file_types.slice(0, 5).join(", ");
		const overflow = check.file_types.length > 5 ? " ..." : "";
		const desc = check.description || name;
		const kind = check.command ? "subprocess" : "inline";
		lines.push(
			`| \`${name}\` (${kind}) | ${check.severity} | ${types}${overflow} | ${desc} |`,
		);
	}

	lines.push("");
	return lines.join("\n");
}

// ===========================================
// Structural Checks Reference
// ===========================================

function generateStructuralChecks(): string {
	const lines: string[] = [
		"<!-- Auto-generated by scripts/generate-docs.ts — do not edit manually -->",
		"# Structural Checks Reference",
		"",
		`${Object.keys(STRUCTURAL_CHECK_META).length} dependency-aware checks that run after file edits.`,
		"These analyze the project graph to detect cross-file issues that single-file lint can't catch.",
		"",
	];

	// Group by tier
	const byTier = new Map<number, [string, (typeof STRUCTURAL_CHECK_META)[string]][]>();
	for (const [key, meta] of Object.entries(STRUCTURAL_CHECK_META)) {
		if (!byTier.has(meta.tier)) byTier.set(meta.tier, []);
		byTier.get(meta.tier)!.push([key, meta]);
	}

	const tierLabels: Record<number, string> = {
		1: "Tier 1 — Fast (sub-100ms, every edit)",
		2: "Tier 2 — Medium (sub-1s, every edit)",
		3: "Tier 3 — Conditional (1-5s, only when needed)",
	};

	for (const tier of [1, 2, 3]) {
		const checks = byTier.get(tier);
		if (!checks || checks.length === 0) continue;

		lines.push(`## ${tierLabels[tier]}`);
		lines.push("");
		lines.push("| Check | Config Key | Description |");
		lines.push("|-------|-----------|-------------|");

		for (const [key, meta] of checks) {
			lines.push(`| ${meta.name} | \`${key}\` | ${meta.description} |`);
		}
		lines.push("");
	}

	return lines.join("\n");
}

// ===========================================
// Sequence Detectors Reference
// ===========================================

/**
 * Family order is fixed by spec: quality → security-shape → injection →
 * cross-agent. Detectors within each family are sorted by id for stable
 * output.
 */
const SEQUENCE_FAMILY_ORDER: ReadonlyArray<SequenceDetectorFamily> = [
	"quality",
	"security-shape",
	"injection",
	"cross-agent",
];

const SEQUENCE_FAMILY_HEADERS: Record<SequenceDetectorFamily, string> = {
	quality: "Quality",
	"security-shape": "Security-Shape",
	injection: "Injection",
	"cross-agent": "Cross-Agent",
};

/**
 * One-line family description used as the header preamble in the generated
 * doc. Sourced from `src/harness/sequence-checks/types.ts` (the
 * `SequenceDetectorFamily` docstring) so the file is single-sourced.
 */
const SEQUENCE_FAMILY_BLURBS: Record<SequenceDetectorFamily, string> = {
	quality:
		"Coverage, doc drift, refactor hygiene, and plan-adherence shapes the per-file checks can't see.",
	"security-shape":
		"Supply-chain, env injection, and repetition shapes — secret-then-network, download-then-execute, repeated-without-observe.",
	injection:
		"Lethal-trifecta / prompt-injection / exfiltration shapes — defense-in-depth across private data, untrusted content, and external comms.",
	"cross-agent":
		"Multi-player staleness / coordination shapes — stale-read-then-write, subagent-divergence, overwrite-after-other-agent.",
};

function generateSequenceDetectorsDoc(): string {
	const detectors = ALL_SEQUENCE_DETECTORS;
	const lines: string[] = [
		"<!-- Auto-generated by scripts/generate-docs.ts — do not edit manually -->",
		"# Trajectory Sequence Detectors",
		"",
		`${detectors.length} sequence detectors registered.`,
		"These run against the session trajectory (a per-session in-memory record of prior tool calls)",
		"on PreToolUse and Stop events. Sibling family to per-file content checks but the contract is",
		"different — sequence detectors fire on trajectory shape, not file content.",
		"",
	];

	// Group by family
	const byFamily = new Map<SequenceDetectorFamily, SequenceDetector[]>();
	for (const fam of SEQUENCE_FAMILY_ORDER) {
		byFamily.set(fam, []);
	}
	for (const detector of detectors) {
		const bucket = byFamily.get(detector.family);
		if (bucket) bucket.push(detector);
	}

	for (const family of SEQUENCE_FAMILY_ORDER) {
		const famDetectors = byFamily.get(family) ?? [];
		if (famDetectors.length === 0) continue;

		// Stable alphabetical sort within family
		const sorted = [...famDetectors].sort((a, b) => a.id.localeCompare(b.id));

		lines.push(`## ${SEQUENCE_FAMILY_HEADERS[family]}`);
		lines.push("");
		lines.push(SEQUENCE_FAMILY_BLURBS[family]);
		lines.push("");

		for (const detector of sorted) {
			const defaultState = detector.default_enabled ? "enabled" : "disabled";
			lines.push(`### \`${detector.id}\``);
			lines.push(`- **Phase:** \`${detector.phase}\``);
			lines.push(`- **Default:** \`${defaultState}\``);
			lines.push(`- **Determinism:** \`${detector.determinism}\``);
			lines.push(`- **Description:** ${detector.description}`);
			lines.push("");
		}
	}

	return lines.join("\n");
}

// ===========================================
// Configuration Reference
// ===========================================

type GuardRulesConfig = ReturnType<typeof getDefaultConfig>;

function buildDiffAwareLines(da: GuardRulesConfig["diff_aware"]): string[] {
	if (!da) return [];
	const lines: string[] = [`| \`enabled\` | \`${da.enabled}\` | Master switch for diff-aware filtering |`];
	if (da.missing_return_types) lines.push(`| \`missing_return_types\` | \`"${da.missing_return_types}"\` | Only report new findings via pre-edit baseline subtraction |`);
	if (da.complexity) lines.push(`| \`complexity\` | \`"${da.complexity}"\` | Only report complex functions in the edited region |`);
	if (da.no_test_file) lines.push(`| \`no_test_file\` | \`"${da.no_test_file}"\` | Only fire on new file creation (Write), not edits |`);
	if (da.undefined_env_vars) lines.push(`| \`undefined_env_vars\` | \`"${da.undefined_env_vars}"\` | Only report env vars introduced by the edit |`);
	return lines;
}

function buildStructuralCheckLines(sc: GuardRulesConfig["structural_checks"]): string[] {
	const lines: string[] = [];
	for (const [key, value] of Object.entries(sc)) {
		if (typeof value === "boolean") {
			const meta = STRUCTURAL_CHECK_META[key];
			const desc = meta ? meta.description : key;
			lines.push(`| \`${key}\` | \`${value}\` | ${desc} |`);
		} else if (typeof value === "number") {
			lines.push(`| \`${key}\` | \`${value}\` | Threshold setting |`);
		}
	}
	return lines;
}

function generateConfigReference(): string {
	const config = getDefaultConfig();
	const lines: string[] = [
		"<!-- Auto-generated by scripts/generate-docs.ts — do not edit manually -->",
		"# Configuration Reference",
		"",
		"Default configuration for the Interlinked CLI harness.",
		"Override in `.interlinked/guard-rules.json` (team) or `.interlinked/guard-rules.local.json` (personal).",
		"",
		"## Diff-Aware Filtering",
		"",
		"Controls which checks suppress pre-existing findings when editing files.",
		"",
		"| Setting | Default | Description |",
		"|---------|---------|-------------|",
		...buildDiffAwareLines(config.diff_aware),
		"",
		"## Structural Checks",
		"",
		"| Setting | Default | Description |",
		"|---------|---------|-------------|",
		...buildStructuralCheckLines(config.structural_checks),
		"",
	];

	return lines.join("\n");
}

// ===========================================
// CLI Command Reference (from commander --help output)
// ===========================================

import { execFileSync } from "node:child_process";

function getHelpOutput(args: string[]): string {
	let raw: string;
	try {
		raw = execFileSync(
			process.execPath,
			["--import", "tsx", join(import.meta.dirname, "..", "src", "index.ts"), ...args, "--help"],
			{
				encoding: "utf-8",
				timeout: 10_000,
				env: { ...process.env, INTERLINKED_SKIP_IMPLICIT_ENTRY: "1" },
			},
		).trim();
	} catch (err) {
		// Commander writes help to stdout and exits with code 0, but execFileSync
		// may throw if the process exits before consuming all stdin. Try stderr fallback.
		const e = err as { stdout?: string; stderr?: string };
		raw = (e.stdout || e.stderr || "").trim();
	}
	// Strip the repeated "Interface boundaries" / "Quick start" footer that commander appends
	const footerIdx = raw.indexOf("\nInterface boundaries:");
	const withoutFooter = footerIdx >= 0 ? raw.slice(0, footerIdx).trimEnd() : raw;
	return sanitizeHelpOutput(withoutFooter);
}

function sanitizeHelpOutput(output: string): string {
	return output.split(process.cwd()).join("<cwd>");
}

function generateCliReference(): string {
	const lines: string[] = [
		"<!-- Auto-generated by scripts/generate-docs.ts — do not edit manually -->",
		"# Interlinked CLI Command Reference",
		"",
	];

	// Top-level help
	const topHelp = getHelpOutput([]);
	lines.push("## Overview", "", "```", topHelp, "```", "");

	// Extract top-level command names from help output
	const commandNames = [
		"structure",
		"verify",
		"metrics",
		"harness",
		"checkpoint",
		"tasks",
		"workspace",
		"index",
		"trace",
		"guard",
		"git",
	];

	// Commands with subcommands — mirror the groups registered in src/index.ts.
	const commandsWithSubs: Record<string, string[]> = {
		structure: ["init", "scan", "status", "accept", "doctor", "baseline"],
		metrics: ["coupling", "arch", "rework"],
		checkpoint: ["list", "show", "compare", "prune", "archive"],
		tasks: ["list", "create", "show", "claim", "complete"],
		workspace: ["list", "switch"],
		index: ["build", "update", "status", "query"],
		trace: ["export", "import"],
		harness: ["start", "stop", "restart", "status", "test"],
		guard: ["install", "check", "status", "uninstall"],
		git: ["context", "link-checkpoint"],
		reminder: ["add", "list", "remove"],
		coverage: ["check", "baseline"],
		mutation: ["check", "baseline"],
		completions: ["bash", "zsh", "fish"],
	};

	for (const cmd of commandNames) {
		const cmdHelp = getHelpOutput([cmd]);
		if (!cmdHelp) continue;

		const title = cmd.charAt(0).toUpperCase() + cmd.slice(1);
		lines.push(`## ${title}`, "", "```", cmdHelp, "```", "");

		const subs = commandsWithSubs[cmd];
		if (subs) {
			for (const sub of subs) {
				const subHelp = getHelpOutput([cmd, sub]);
				if (!subHelp) continue;
				lines.push(`### ${cmd} ${sub}`, "", "```", subHelp, "```", "");
			}
		}
	}

	// Also document standalone commands with notable options
	const standaloneCommands = [
		"enable", "disable", "status", "activity", "doctor", "clean",
		"login", "sync", "send", "inbox", "watch",
	];
	lines.push("## Other Commands", "");
	for (const cmd of standaloneCommands) {
		const cmdHelp = getHelpOutput([cmd]);
		if (!cmdHelp) continue;
		lines.push(`### ${cmd}`, "", "```", cmdHelp, "```", "");
	}

	return lines.join("\n");
}

// ===========================================
// Main
// ===========================================

// ===========================================
// Quality-Metric Caps Reference (from metric-caps.ts METRIC_DEFS)
// ===========================================
function generateMetrics(): string {
	const lines: string[] = [
		"# Quality-Metric Caps",
		"",
		"<!-- Auto-generated by scripts/generate-docs.ts — do not edit manually -->",
		"",
		`The harness enforces ${METRIC_DEFS.length} quality metrics. Every user tunes their own caps in the`,
		"committed `.interlinked/metric-caps.json` (or `interlinked caps set <metric> <value>`);",
		"the values below are the shipped defaults. `interlinked caps` shows the effective cap",
		"per repo, and `interlinked caps explain <metric>` prints these same definitions — so an",
		"agent on any harness-running codebase is never unsure what a metric means.",
		"",
		"| Metric | Config key | Shipped default | Direction |",
		"|--------|-----------|-----------------|-----------|",
	];
	for (const d of METRIC_DEFS) {
		const unit = d.unit ? ` ${d.unit}` : "";
		lines.push(`| \`${d.key}\` | \`${d.configKey}\` | ${d.defaultValue}${unit} | ${d.stricter} is stricter |`);
	}
	lines.push("");
	for (const d of METRIC_DEFS) {
		const unit = d.unit ? ` ${d.unit}` : "";
		lines.push(`## ${d.label} (\`${d.key}\`)`, "");
		lines.push(d.definition, "");
		lines.push(`- **Shipped default:** ${d.defaultValue}${unit} (${d.stricter} is stricter)`);
		lines.push(`- **Configure:** ${d.howToConfigure}`);
		lines.push(`- **Fix when an edit is blocked:** ${d.fixHint}`, "");
	}
	return `${lines.join("\n")}\n`;
}

const files = [
	{ name: "guard-rules.md", generator: generateGuardRules },
	{ name: "quality-checks.md", generator: generateQualityChecks },
	{ name: "structural-checks.md", generator: generateStructuralChecks },
	{ name: "sequence-detectors.md", generator: generateSequenceDetectorsDoc },
	{ name: "configuration.md", generator: generateConfigReference },
	{ name: "cli-reference.md", generator: generateCliReference },
	{ name: "metrics.md", generator: generateMetrics },
];

let generated = 0;
for (const { name, generator } of files) {
	const content = generator();
	const path = join(OUT_DIR, name);
	writeFileSync(path, content);
	console.log(`  Generated: docs/generated/${name}`);
	generated++;
}

console.log(`\n${generated} reference docs generated from code.`);
