// A component render return does not dispose a timer. The effect callback
// must return its cleanup; expected finding locations are literal.
// Public requirement: https://react.dev/reference/react/useEffect#parameters
export const effectCleanupCases = [
    {
        name: "component render does not dispose its recurring timer",
        path: "src/components/PollingWidget.tsx",
        content: [
            "function PollingWidget() {",
            "  useEffect(() => {",
            "    const timer = window.setInterval(refresh, 5000);",
            "  }, []);",
            "  return <span>Polling</span>;",
            "}",
        ].join("\n"),
        lines: [2],
    },
    {
        name: "effect returns its timer teardown before component render",
        path: "src/components/PollingWidget.tsx",
        content: [
            "function PollingWidget() {",
            "  useEffect(() => {",
            "    const timer = window.setInterval(refresh, 5000);",
            "    return () => window.clearInterval(timer);",
            "  }, []);",
            "  return <span>Polling</span>;",
            "}",
        ].join("\n"),
        lines: [],
    },
    {
        name: "effect returns a named cleanup without a semicolon",
        path: "src/components/PollingWidget.tsx",
        content: [
            "function PollingWidget() {",
            "  useEffect(() => {",
            "    const timer = window.setInterval(refresh, 5000);",
            "    const cleanup = () => window.clearInterval(timer);",
            "    return cleanup",
            "  }, []);",
            "  return <span>Polling</span>;",
            "}",
        ].join("\n"),
        lines: [],
    },
    {
        name: "effect returns a parenthesized multi-line cleanup arrow",
        path: "src/components/PollingWidget.tsx",
        content: [
            "function PollingWidget() {",
            "  useEffect(() => {",
            "    const timer = window.setInterval(refresh, 5000);",
            "    return (",
            "      () => window.clearInterval(timer)",
            "    );",
            "  }, []);",
            "  return <span>Polling</span>;",
            "}",
        ].join("\n"),
        lines: [],
    },
    {
        name: "cleanup returns with a trailing comment, a typed arrow and a parenthesized identifier",
        path: "src/components/PollingWidget.tsx",
        content: [
            "function PollingWidget() {",
            "  useEffect(() => {",
            "    const timer = window.setInterval(refresh, 5000);",
            "    return cleanup; // dispose",
            "  }, []);",
            "  useEffect(() => {",
            "    const timer = window.setInterval(refresh, 5000);",
            "    return (): void => clearInterval(timer);",
            "  }, []);",
            "  useEffect(() => {",
            "    const timer = window.setInterval(refresh, 5000);",
            "    return (cleanup);",
            "  }, []);",
            "  return <span>Polling</span>;",
            "}",
        ].join("\n"),
        lines: [],
    },
    {
        name: "effect returns a subscription's disposer directly",
        path: "src/components/PollingWidget.tsx",
        content: [
            "function PollingWidget() {",
            "  useEffect(() => {",
            "    return store.subscribe(listener);",
            "  }, []);",
            "  useEffect(() => {",
            "    const timer = window.setInterval(refresh, 5000);",
            "    return this.disposer;",
            "  }, []);",
            "  return <span>Polling</span>;",
            "}",
        ].join("\n"),
        lines: [],
    },
    {
        name: "cleanup returns on one line with other syntax and across lines",
        path: "src/components/PollingWidget.tsx",
        content: [
            "function PollingWidget() {",
            "  useEffect(() => { const cleanup = store.subscribe(listener); return cleanup; }, []);",
            "  useEffect(() => {",
            "    const timer = window.setInterval(refresh, 5000);",
            "    return store.subscribe(",
            "      listener",
            "    );",
            "  }, []);",
            "  return <span>Polling</span>;",
            "}",
        ].join("\n"),
        lines: [],
    },
    {
        name: "a guard return before the cleanup return, and a URL string in the effect",
        path: "src/components/PollingWidget.tsx",
        content: [
            "function PollingWidget() {",
            "  useEffect(() => {",
            "    const cleanup = enabled ? store.subscribe(listener) : undefined;",
            "    if (!cleanup) return;",
            "    return cleanup;",
            "  }, []);",
            "  useEffect(() => { const cleanup = enabled ? store.subscribe(listener) : undefined; if (!cleanup) return; return cleanup; }, []);",
            '  useEffect(() => { const id = setInterval(() => fetch("https://example.com"), 1000); return () => clearInterval(id); }, []);',
            "  return <span>Polling</span>;",
            "}",
        ].join("\n"),
        lines: [],
    },
    {
        name: "cleanup returns after a semicolon-free statement and after else",
        path: "src/components/PollingWidget.tsx",
        content: [
            "function PollingWidget() {",
            "  useEffect(() => {",
            "    const cleanup = store.subscribe(listener)",
            "    cleanupRef.current = cleanup",
            "    return cleanup",
            "  }, []);",
            "  useEffect(() => {",
            "    const cleanup = enabled ? store.subscribe(listener) : undefined;",
            "    if (!cleanup) return; else return cleanup;",
            "  }, []);",
            "  return <span>Polling</span>;",
            "}",
        ].join("\n"),
        lines: [],
    },
    {
        name: "a bare return before a line break never returns the next statement",
        path: "src/components/PollingWidget.tsx",
        content: [
            "function PollingWidget() {",
            "  useEffect(() => {",
            "    if (!enabled) return",
            "    const id = setInterval(tick, 1000)",
            "  }, []);",
            "  return <span>Polling</span>;",
            "}",
        ].join("\n"),
        lines: [2],
    },
    {
        name: "cleanup returns after switch labels",
        path: "src/components/PollingWidget.tsx",
        content: [
            "function PollingWidget() {",
            "  useEffect(() => {",
            "    const cleanup = store.subscribe(listener);",
            "    switch (mode) {",
            '      case "active": return cleanup;',
            "      default: return cleanup;",
            "    }",
            "  }, []);",
            "  return <span>Polling</span>;",
            "}",
        ].join("\n"),
        lines: [],
    },
    {
        name: "a bare return before a closing brace is not a cleanup",
        path: "src/components/PollingWidget.tsx",
        content: [
            "function PollingWidget() {",
            "  useEffect(() => {",
            "    if (!enabled) { return }",
            "    setInterval(tick, 1000)",
            "  }, []);",
            "  return <span>Polling</span>;",
            "}",
        ].join("\n"),
        lines: [2],
    },
    {
        name: "commented-out setup and teardown are no subscription",
        path: "src/components/PollingWidget.tsx",
        content: [
            "function PollingWidget() {",
            "  useEffect(() => {",
            "    // const timer = setInterval(tick, 1000);",
            "    // return () => clearInterval(timer);",
            "  }, []);",
            "  useEffect(() => {",
            "    /* window.addEventListener('resize', onResize); */",
            '    const label = "subscribe(";',
            "  }, []);",
            "  return <span>Polling</span>;",
            "}",
        ].join("\n"),
        lines: [],
    },
    {
        name: "an object member named return is not a cleanup return",
        path: "src/components/PollingWidget.tsx",
        content: [
            "function PollingWidget() {",
            "  useEffect(() => {",
            "    const timer = setInterval(tick, 1000);",
            "    const iterator = { return: () => clearInterval(timer) };",
            "  }, []);",
            "  useEffect(() => {",
            "    const timer = setInterval(tick, 1000);",
            "    const iterator = { return() { clearInterval(timer); } };",
            "  }, []);",
            "  useEffect(() => {",
            "    const timer = setInterval(tick, 1000);",
            "    const iterator = { return: () => clearInterval(timer) };",
            "    return (iterator.return);",
            "  }, []);",
            "  return <span>Polling</span>;",
            "}",
        ].join("\n"),
        lines: [2, 6],
    },
    {
        name: "typed and nested-parameter methods named return are not cleanup returns",
        path: "src/components/PollingWidget.tsx",
        content: [
            "function PollingWidget() {",
            "  useEffect(() => {",
            "    const timer = setInterval(tick, 1000);",
            "    const iterator = { return(): void { clearInterval(timer); } };",
            "  }, []);",
            "  useEffect(() => {",
            "    const timer = setInterval(tick, 1000);",
            "    const iterator = { return(value = readValue()) { clearInterval(timer); } };",
            "  }, []);",
            "  useEffect(() => {",
            "    const timer = setInterval(tick, 1000);",
            "    return (value = readValue()) => clearInterval(timer);",
            "  }, []);",
            "  return <span>Polling</span>;",
            "}",
        ].join("\n"),
        lines: [2, 6],
    },
    {
        name: "cleanup arrows with destructured defaults, generics and a typed single parameter",
        path: "src/components/PollingWidget.tsx",
        content: [
            "function PollingWidget() {",
            "  useEffect(() => {",
            "    const id = setInterval(tick, 1000);",
            "    return ({ force = false } = {}) => clearInterval(id);",
            "  }, []);",
            "  useEffect(() => {",
            "    const id = setInterval(tick, 1000);",
            "    return <T,>(value?: T) => clearInterval(id);",
            "  }, []);",
            "  useEffect(() => {",
            "    const id = setInterval(tick, 1000);",
            "    return (value: number = 1): void => clearInterval(id);",
            "  }, []);",
            "  useEffect(() => {",
            "    const id = setInterval(tick, 1000);",
            "    return { force: false };",
            "  }, []);",
            "  return <span>Polling</span>;",
            "}",
        ].join("\n"),
        lines: [14],
    },
    {
        name: "parenthesized and constrained-generic cleanup arrows",
        // The line scanner (the fallback without `typescript`) cannot see through these; the parser route can.
        parserOnly: true,
        path: "src/components/PollingWidget.tsx",
        content: [
            "function PollingWidget() {",
            "  useEffect(() => {",
            "    const id = setInterval(tick, 1000);",
            "    return (({ force = false } = {}) => clearInterval(id));",
            "  }, []);",
            "  useEffect(() => {",
            "    const id = setInterval(tick, 1000);",
            "    return (<T,>(value?: T) => clearInterval(id));",
            "  }, []);",
            "  useEffect(() => {",
            "    const id = setInterval(tick, 1000);",
            "    return <T extends () => void>(value?: T) => clearInterval(id);",
            "  }, []);",
            "  return <span>Polling</span>;",
            "}",
        ].join("\n"),
        lines: [],
    },
    {
        name: "a parenthesized multi-line render return is not a cleanup",
        path: "src/components/PollingWidget.tsx",
        content: [
            "function PollingWidget() {",
            "  useEffect(() => {",
            "    const timer = window.setInterval(refresh, 5000);",
            "  }, []);",
            "  return (",
            "    <span>Polling</span>",
            "  );",
            "}",
        ].join("\n"),
        lines: [2],
    },
];
