// Generator-output detection and Bandit/eslint-noqa suppression-comment
// respect, extracted from shared.ts (no behavior change). Re-exported by
// shared.ts so existing importers keep resolving these from "./shared.js".

/**
 * Detect generator-output files by looking for tooling markers in the
 * first 20 lines. Generators routinely emit code that uses `any`,
 * file-level lint suppression headers, and `.test.<ext>` siblings that
 * don't exist — flagging that surface is pure noise (the fix is to
 * change the generator config, not the file).
 *
 * Origin: 139-repo FP audit. Supermodel's `sdk/src/apis/DefaultApi.ts`
 * (auto-generated by OpenAPI Generator) produced ~555 FPs in one file —
 * 290 strong_typing + 132 file_level_suppression + 67 files_without_test +
 * 66 suppressions — none real. Header includes:
 *   `NOTE: This class is auto generated by OpenAPI Generator`
 *
 * Bounded scan (first 20 lines) so a file with `// auto-generated`
 * mentioned in some deep doc-block doesn't accidentally exempt itself.
 * The marker has to be near the top — the standard generator convention.
 */
const GENERATOR_MARKERS: readonly string[] = [
	"auto generated",
	"auto-generated",
	"automatically generated",
	"openapi generator",
	"openapi-generator",
	"swagger-codegen",
	"do not edit by hand",
	"do not edit",
	"this file was generated",
	"code generated by protoc",
	"@generated",
];

export function isGeneratedFile(content: string): boolean {
	// Bounded scan: first 20 lines, lower-cased once. Linear over a small
	// window — cheaper than firing the suppressed checks downstream.
	const head = content.split("\n", 20).join("\n").toLowerCase();
	return GENERATOR_MARKERS.some((m) => head.includes(m));
}

/**
 * Bandit/eslint suppression-comment respect — when an author has
 * explicitly acknowledged a finding via `# noqa: <code>` (Python /
 * Bandit) or equivalent, the harness should not double-fire. Maps the
 * Bandit code namespace to our internal check ids.
 *
 * Origin: 139-repo FP audit. Supermodel's `mcpbr/src/mcpbr/tutorial.py`
 * contained `subprocess.run(  # noqa: S602 -- tutorial validation runs
 * user-defined shell commands by design, ...)` — explicit, reasoned,
 * intentional. `custom_metrics.py:347` had `value = float(eval(
 * metric_def.compute_fn, {"__builtins__": {}}, ns))  # noqa: S307` —
 * sandboxed eval, suppression carries the intent.
 *
 * The mapping is conservative: codes with no equivalent in our
 * registry (S311 `random`-for-security) map to `[]` and never
 * suppress. Bare `# noqa` (no code) is treated as suppress-everything
 * per Python convention — same as flake8's behavior.
 */
const BANDIT_TO_CHECK_ID: Record<string, readonly string[]> = {
	S102: ["ubs_eval_input_tainted"], // exec
	S301: ["ubs_pickle_untrusted_load"], // pickle
	S307: ["ubs_eval_input_tainted"], // eval
	S310: ["ubs_unchecked_redirect"], // urllib.request urlopen
	S311: [], // random for security — no equivalent in registry
	S314: ["ubs_xml_external_entity"], // xml ElementTree
	S320: ["ubs_xml_external_entity"], // lxml.etree
	S324: ["weak_hash"], // weak MD5/SHA1
	S501: ["tls_verify_disabled"], // verify=False
	S602: ["ubs_subprocess_shell_true"], // subprocess shell=True
	S603: ["ubs_subprocess_shell_true"],
	S605: ["child_process_exec_user_input"],
	S608: ["ubs_sql_string_concat"], // SQL injection
};

const NOQA_RE = /#\s*noqa(?::\s*([A-Z]\d+(?:\s*,\s*[A-Z]\d+)*))?/;

export function lineHasNoqaSuppression(line: string, checkId: string): boolean {
	const m = NOQA_RE.exec(line);
	if (!m) return false;
	// Bare `# noqa` suppresses everything (Python/flake8 convention).
	if (!m[1]) return true;
	const codes = m[1].split(/\s*,\s*/);
	return codes.some((code) => BANDIT_TO_CHECK_ID[code]?.includes(checkId));
}
