// Companion test for shared-generated-and-suppression.ts — moved verbatim
// from shared.ts as part of the shared.ts line-cap split. Behavior unchanged.

import { describe, expect, it } from "vitest";
import {
	isGeneratedFile,
	lineHasNoqaSuppression,
} from "./shared-generated-and-suppression.js";

describe("isGeneratedFile — positive (must fire)", () => {
	it("detects an OpenAPI Generator header", () => {
		const content = "// NOTE: This class is auto generated by OpenAPI Generator\nexport const x = 1;";
		expect(isGeneratedFile(content)).toBe(true);
	});

	it("detects '@generated' marker", () => {
		expect(isGeneratedFile("// @generated\nexport const x = 1;")).toBe(true);
	});
});

describe("isGeneratedFile — negative (must not fire)", () => {
	it("does not fire on ordinary hand-written source", () => {
		expect(isGeneratedFile("export function foo() { return 1; }")).toBe(false);
	});

	it("does not fire when the marker appears after line 20", () => {
		const filler = Array.from({ length: 25 }, (_, i) => `// line ${i}`).join("\n");
		expect(isGeneratedFile(`${filler}\n// auto-generated`)).toBe(false);
	});
});

describe("lineHasNoqaSuppression — positive (must fire)", () => {
	it("suppresses when a bare '# noqa' is present (suppress-everything convention)", () => {
		expect(lineHasNoqaSuppression("eval(x)  # noqa", "ubs_eval_input_tainted")).toBe(true);
	});

	it("suppresses when the mapped Bandit code matches the check id", () => {
		expect(
			lineHasNoqaSuppression("subprocess.run(cmd, shell=True)  # noqa: S602", "ubs_subprocess_shell_true"),
		).toBe(true);
	});
});

describe("lineHasNoqaSuppression — negative (must not fire)", () => {
	it("does not suppress when there is no noqa comment", () => {
		expect(lineHasNoqaSuppression("eval(x)", "ubs_eval_input_tainted")).toBe(false);
	});

	it("does not suppress when the noqa code has no mapping to the given check id", () => {
		expect(lineHasNoqaSuppression("eval(x)  # noqa: S311", "ubs_eval_input_tainted")).toBe(false);
	});
});
