// Regression test: the shell snippet generated by `installCodexHooks`
// (and the other relative-path installers) must parse and execute correctly
// under bash, sh, and zsh — Codex / Claude / Copilot all invoke hooks via
// the user's configured shell, and many CI environments use bash or dash.
// An earlier version of `buildHookCommand` joined the body with `"; "`,
// producing `while :; do; if ...` which is rejected by bash/sh/dash (only
// zsh tolerates the empty statement after `do`). This test pins the fix.

import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { parseWire, wireObject, wireArray, wireRecord, wireString, wireNumber, wireAbsentOptional, wireBoolean } from "../value-validation.js";
import {
	CURSOR_FAIL_CLOSED_EVENTS,
	installCodexHooks,
	installCursorHooks,
} from "../hook-installers.js";

interface HookEntry {
	type: string;
	command: string;
}
interface HookGroup {
	matcher: string;
	hooks: HookEntry[];
}
interface HookFile {
	hooks: Record<string, HookGroup[]>;
}

const isHookFile = wireObject<HookFile>({
	hooks: wireRecord(wireArray(wireObject<HookGroup>({
		matcher: wireString,
		hooks: wireArray(wireObject<HookEntry>({ type: wireString, command: wireString })),
	}))),
});

// zsh isn't installed on GitHub Actions ubuntu-latest runners. The bash/sh
// cases already cover the original regression (the old `[...].join("; ")`
// form produced `do;` / `then;` which only zsh tolerates and bash/sh reject),
// so the zsh case is a sanity check that good code still works on zsh — fine
// to skip when zsh is missing rather than fail with a confusing
// `.toMatch(undefined)` error.
const HAS_ZSH = spawnSync("zsh", ["-c", "true"], { stdio: "ignore" }).status === 0;

let tmp: string;

beforeEach(() => {
	tmp = mkdtempSync(join(tmpdir(), "codex-shell-"));
});

afterEach(() => {
	rmSync(tmp, { recursive: true, force: true });
});

function readPreToolCommand(): string {
	const path = join(tmp, ".codex", "hooks.json");
	const parsed = parseWire(JSON.parse(readFileSync(path, "utf-8")), isHookFile, "installed Codex hooks");
	return parsed.hooks.PreToolUse[0].hooks[0].command;
}

function shellExits(shell: string, command: string): { code: number; stderr: string } {
	const res = spawnSync(shell, ["-c", command], {
		encoding: "utf-8",
		cwd: tmp,
	});
	return { code: res.status ?? -1, stderr: res.stderr };
}

describe("Codex hook command — shell portability", () => {
	it("parses without error under bash", () => {
		installCodexHooks(tmp, ".interlinked/hooks/interlinked-activity.mjs");
		const command = readPreToolCommand();
		// Replace the actual node invocation with a no-op echo so the test
		// doesn't depend on an installed hook script. We're testing parse
		// + control-flow, not script execution.
		const safeCommand = command.replace(/INTERLINKED_CLIENT[^|]*\|\| true/, 'echo "RAN"');
		const result = shellExits("bash", safeCommand);
		expect(result.stderr).not.toMatch(/syntax error/i);
		expect(result.code).toBe(0);
	});

	it("parses without error under sh", () => {
		installCodexHooks(tmp, ".interlinked/hooks/interlinked-activity.mjs");
		const command = readPreToolCommand();
		const safeCommand = command.replace(/INTERLINKED_CLIENT[^|]*\|\| true/, 'echo "RAN"');
		const result = shellExits("sh", safeCommand);
		expect(result.stderr).not.toMatch(/syntax error/i);
		expect(result.code).toBe(0);
	});

	it.skipIf(!HAS_ZSH)("parses without error under zsh", () => {
		installCodexHooks(tmp, ".interlinked/hooks/interlinked-activity.mjs");
		const command = readPreToolCommand();
		const safeCommand = command.replace(/INTERLINKED_CLIENT[^|]*\|\| true/, 'echo "RAN"');
		const result = shellExits("zsh", safeCommand);
		expect(result.stderr).not.toMatch(/syntax error/i);
		expect(result.code).toBe(0);
	});

	it("walks up from a subdirectory and finds the hook script at the repo root", () => {
		// Drop a fake hook script at the repo root; cd into a deep subdir;
		// run the generated command from there. The walk-up logic should
		// find the script and execute it.
		mkdirSync(join(tmp, ".interlinked", "hooks"), { recursive: true });
		writeFileSync(
			join(tmp, ".interlinked", "hooks", "interlinked-activity.mjs"),
			"#!/usr/bin/env node\nprocess.stdout.write('FOUND');\n",
		);
		mkdirSync(join(tmp, "deep", "nested", "subdir"), { recursive: true });
		installCodexHooks(tmp, ".interlinked/hooks/interlinked-activity.mjs");
		const command = readPreToolCommand();

		const res = spawnSync("bash", ["-c", command], {
			encoding: "utf-8",
			cwd: join(tmp, "deep", "nested", "subdir"),
			input: "{}",
		});
		expect(res.stderr).not.toMatch(/syntax error/i);
		expect(res.stdout).toContain("FOUND");
	});

	it("exits cleanly when the hook script is missing (no error to the user's shell)", () => {
		// Don't create the script; the walk-up should hit the filesystem
		// root and exit with status 0.
		installCodexHooks(tmp, ".interlinked/hooks/interlinked-activity.mjs");
		const command = readPreToolCommand();
		const result = shellExits("bash", command);
		expect(result.code).toBe(0);
	});

	it("emits the file via the legacy installCodexHooks pipeline", () => {
		installCodexHooks(tmp, ".interlinked/hooks/interlinked-activity.mjs");
		expect(existsSync(join(tmp, ".codex", "hooks.json"))).toBe(true);
	});
});

interface CursorHookEntry {
	type: string;
	command: string;
	failClosed?: boolean;
}
interface CursorHookFile {
	version: number;
	hooks: Record<string, CursorHookEntry[]>;
}

const isCursorHookFile = wireObject<CursorHookFile>({
	version: wireNumber,
	hooks: wireRecord(wireArray(wireObject<CursorHookEntry>({
		type: wireString, command: wireString, failClosed: wireAbsentOptional(wireBoolean),
	}))),
});

function readCursorBeforeShellCommand(): string {
	return readCursorEventCommand("beforeShellExecution");
}

function readCursorEventCommand(eventName: string): string {
	const path = join(tmp, ".cursor", "hooks.json");
	const parsed = parseWire(JSON.parse(readFileSync(path, "utf-8")), isCursorHookFile, "installed Cursor hooks");
	const entry = parsed.hooks[eventName]?.[0];
	if (!entry) throw new Error(`no ${eventName} hook entry`);
	return entry.command;
}

describe("Cursor hook command — fail-closed propagation", () => {
	it("does NOT terminate in `|| true` for fail-closed events", () => {
		// `failClosed: true` Cursor events (`beforeShellExecution`,
		// `beforeMCPExecution`, `beforeReadFile`, `preToolUse`) require the
		// shell to exit non-zero when the hook startup or runtime fails.
		// Earlier versions used the shared command builder that ended in
		// `|| true`, swallowing every failure and silently letting destructive
		// shell commands run unguarded.
		installCursorHooks(tmp, ".interlinked/hooks/interlinked-activity.mjs");
		const command = readCursorBeforeShellCommand();
		expect(command).not.toMatch(/\|\|\s*true/);
	});

	it("exits NON-ZERO when the hook script is missing", () => {
		// Don't create the script. The walk-up should hit the filesystem
		// root and `exit 1` so Cursor's failClosed actually fails closed.
		installCursorHooks(tmp, ".interlinked/hooks/interlinked-activity.mjs");
		const command = readCursorBeforeShellCommand();
		const result = shellExits("bash", command);
		expect(result.code).not.toBe(0);
	});

	it("propagates the hook script's exit code (allow → 0, deny → non-zero)", () => {
		// Create a hook script that always exits 1 (mimics a deny decision).
		// Cursor expects the wrapper's exit code to mirror node's.
		mkdirSync(join(tmp, ".interlinked", "hooks"), { recursive: true });
		writeFileSync(
			join(tmp, ".interlinked", "hooks", "interlinked-activity.mjs"),
			"#!/usr/bin/env node\nprocess.exit(1);\n",
		);
		installCursorHooks(tmp, ".interlinked/hooks/interlinked-activity.mjs");
		const command = readCursorBeforeShellCommand();
		const res = spawnSync("bash", ["-c", command], { encoding: "utf-8", cwd: tmp });
		expect(res.status).toBe(1);
	});

	it("absolute-path form also fails closed when the script is missing", () => {
		// Use a fully-qualified path that doesn't exist on disk. Cursor's
		// absolute-path branch is a different code path from the walk-up
		// branch and needs its own coverage.
		const missingAbs = join(tmp, "definitely-not-here", "interlinked-activity.mjs");
		installCursorHooks(tmp, missingAbs);
		const command = readCursorBeforeShellCommand();
		const result = shellExits("bash", command);
		expect(result.code).not.toBe(0);
	});

	it("parses without error under sh and bash", () => {
		// Cursor's command builder uses different control flow (`exec` instead
		// of `node ... || true; break`) so re-run the shell-portability
		// regression that already covers the Codex form.
		mkdirSync(join(tmp, ".interlinked", "hooks"), { recursive: true });
		writeFileSync(
			join(tmp, ".interlinked", "hooks", "interlinked-activity.mjs"),
			"#!/usr/bin/env node\nprocess.exit(0);\n",
		);
		installCursorHooks(tmp, ".interlinked/hooks/interlinked-activity.mjs");
		const command = readCursorBeforeShellCommand();
		expect(shellExits("bash", command).stderr).not.toMatch(/syntax error/i);
		expect(shellExits("sh", command).stderr).not.toMatch(/syntax error/i);
	});
});

// ===========================================
// Parametric contract: every fail-closed event must actually fail closed
// ===========================================
// `CURSOR_FAIL_CLOSED_EVENTS` declares the events that need their hook to
// exit non-zero on missing/crashed script. Adding a new event there must
// come with a command-shape that propagates the failure — otherwise a
// destructive command runs unguarded. This `it.each(...)` walks the actual
// constant so any future addition is automatically pinned.
describe.each(Array.from(CURSOR_FAIL_CLOSED_EVENTS))(
	"Cursor fail-closed contract: %s",
	(eventName) => {
		it("exits non-zero when the hook script is missing", () => {
			// No `.interlinked/hooks/...` exists; walk-up should hit
			// filesystem root and `exit 1`.
			installCursorHooks(tmp, ".interlinked/hooks/interlinked-activity.mjs");
			const command = readCursorEventCommand(eventName);
			expect(command).not.toMatch(/\|\|\s*true/);
			const result = shellExits("bash", command);
			expect(result.code).not.toBe(0);
		});

		it("propagates the hook script's deny exit code (1) to Cursor", () => {
			mkdirSync(join(tmp, ".interlinked", "hooks"), { recursive: true });
			writeFileSync(
				join(tmp, ".interlinked", "hooks", "interlinked-activity.mjs"),
				"#!/usr/bin/env node\nprocess.exit(1);\n",
			);
			installCursorHooks(tmp, ".interlinked/hooks/interlinked-activity.mjs");
			const command = readCursorEventCommand(eventName);
			const res = spawnSync("bash", ["-c", command], {
				encoding: "utf-8",
				cwd: tmp,
			});
			expect(res.status).toBe(1);
		});
	},
);
